### ISSUE TITLE
Is there a scala 2.12 spark 3.x compatible jar

### ISSUE THREAD

**Issue by asahalyft** [Azure/mmlspark#1012]
**Describe the bug**
I am using `mmlspark_2.11-1.0.0-rc3.jar`. However, `pip install mmlspark` does not install `mmlspark.lightgbm._LightGBMRegressor`

So, I had to manually unjar the jar and paste those python files in the `site-packages` folder.

Now, I hit another error with 
```
from mmlspark.lightgbm import LightGBMRegressor
model = LightGBMRegressor(objective='quantile',
                          alpha=0.2,
                          learningRate=0.3,
                          numLeaves=31).fit(train)
```

**Info:**
 - MMLSpark Version: v1.0.0
 - Spark Version [e.g. 3.0.1]

**Stacktrace**

```
Py4JJavaError: An error occurred while calling None.com.microsoft.ml.spark.lightgbm.LightGBMRegressor.
: java.lang.NoClassDefFoundError: org/apache/spark/ml/util/MLWritable$class
	at com.microsoft.ml.spark.lightgbm.LightGBMRegressor.<init>(LightGBMRegressor.scala:37)
	at com.microsoft.ml.spark.lightgbm.LightGBMRegressor.<init>(LightGBMRegressor.scala:39)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at py4j.reflection.MethodInvoker.invoke(MethodInvoker.java:247)
	at py4j.reflection.ReflectionEngine.invoke(ReflectionEngine.java:357)
	at py4j.Gateway.invoke(Gateway.java:238)
	at py4j.commands.ConstructorCommand.invokeConstructor(ConstructorCommand.java:80)
	at py4j.commands.ConstructorCommand.execute(ConstructorCommand.java:69)
	at py4j.GatewayConnection.run(GatewayConnection.java:238)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.ClassNotFoundException: org.apache.spark.ml.util.MLWritable$class
	at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:419)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:352)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:352)
	... 13 more
```
If the bug pertains to a specific feature please tag the appropriate [CODEOWNER](https://github.com/Azure/mmlspark/blob/master/CODEOWNERS) for better visibility

**Additional context**

**Comment by asahalyft** [comment]
@mhamilton723 If you could please comment/suggest.

**Comment by mhamilton723** [comment]
@asahalyft 
Yes please use latest build for spark 3.0.1

Build
MMLSpark Build and Release Information
Maven Coordinates
com.microsoft.ml.spark:mmlspark_2.12:1.0.0-rc3-43-54379bf7-SNAPSHOT

Maven Resolver
https://mmlspark.azureedge.net/maven
