### ISSUE TITLE
Install script action fails on HDInsight cluster

### ISSUE THREAD

**Issue by mawah** [Azure/mmlspark#121]
Hi folks,

I recently provisioned an HDInsight Spark 2.1 cluster and tried to install MMLSpark using the [script action URI](https://mmlspark.azureedge.net/buildartifacts/0.7/install-mmlspark.sh) and [instructions](https://github.com/Azure/mmlspark), as I've previously done for MMLSpark 0.6 without any issues. The script action fails, showing the following "Debug information" in Azure Portal:
```
{
    "href": "http://10.0.0.23:8080/api/v1/clusters/mawahwasb3/requests/40",
    "tasks": [
        {
            "href": "http://10.0.0.23:8080/api/v1/clusters/mawahwasb3/requests/40/tasks/156",
            "Tasks": {
                "attempt_cnt": 1,
                "command": "ACTIONEXECUTE",
                "command_detail": "run_customscriptaction ACTIONEXECUTE",
                "end_time": 1503679947306,
                "error_log": "/var/lib/ambari-agent/data/errors-156.txt",
                "exit_code": 1,
                "host_name": "hn0-mawahw.3ejwtsbjuzpurdzrrmda4wm3nd.gx.internal.cloudapp.net",
                "id": "156",
                "output_log": "/var/lib/ambari-agent/data/output-156.txt",
                "request_id": "40",
                "role": "run_customscriptaction",
                "stage_id": "0",
                "start_time": 1503679944176,
                "status": "FAILED",
                "stderr": null,
                "stdout": null,
                "structured_out": null
            }
        }, [...and all other tasks "COMPLETED"]
```

The last few lines printed to the mentioned output log (`/var/lib/ambari-agent/data/output-156.txt`) are:
```
Setting up ocl-icd-libopencl1:amd64 (2.2.8-1) ...
Setting up libhwloc-plugins (1.11.2-3) ...
Processing triggers for libc-bin (2.23-0ubuntu9) ...
[azureml_327951dc2df6f88e104edcd22c5f680e] ('Start downloading script locally: ', u'https://mmlspark.azureedge.net/buildartifacts/0.7/install-mmlspark.sh')
Fromdos line ending conversion successful
('Unexpected error:', "('Execution of custom script failed with exit code', 1)")
Removing temp location of the script
```
And the last few lines of the mentioned error log (`/var/lib/ambari-agent/data/errors-156.txt`) are:
```
/tmp/tmpyhsA9w: line 50: CNTK_WHEELS[$env]: Unknown conda env for CNTK: azureml_327951dc2df6f88e104edcd22c5f680e
Traceback (most recent call last):
  File "/var/lib/ambari-agent/cache/custom_actions/scripts/run_customscriptaction.py", line 194, in <module>
    ExecuteScriptAction().execute()
  File "/usr/lib/python2.6/site-packages/resource_management/libraries/script/script.py", line 329, in execute
    method(env)
  File "/var/lib/ambari-agent/cache/custom_actions/scripts/run_customscriptaction.py", line 179, in actionexecute
    ExecuteScriptAction.execute_bash_script(bash_script, scriptpath, scriptparams)
  File "/var/lib/ambari-agent/cache/custom_actions/scripts/run_customscriptaction.py", line 149, in execute_bash_script
    raise Exception("Execution of custom script failed with exit code",exitcode)
Exception: ('Execution of custom script failed with exit code', 1)
```
Is there any other info I can provide to help identify the problem? Thanks in advance for your help!

**Comment by mawah** [comment]
Hi folks,

I wasn't able to reproduce this problem when I created a brand new cluster. I had executed a few scripts remotely on this cluster using a utility that I believe could have created the conda environment mentioned in the error message above. In the future I'll ensure I perform all script actions before using that utility. Sorry for the false alarm!
