### ISSUE TITLE
LightGBMRegressor Odd Behavior on Azure Databricks

### ISSUE THREAD

**Issue by JeffMacaluso** [Azure/mmlspark#317]
I'm running into two problems with the mmlspark.LightGBMRegressor function on Azure Databricks:

1) The port binding tends to fail fairly consistently. The solution from [this issue](https://github.com/Azure/mmlspark/issues/173) of changing the default port binding doesn't seem to solve this problem in all cases. It seems like this happens more consistently for quantile regression models, but that could just be from random chance.

![databrickslightgbmregressor2](https://user-images.githubusercontent.com/13501239/41481700-8d9aed38-7098-11e8-8d7d-386b4ed5099d.JPG)

2) Quantile regression sometimes throws the following error: 
`org.apache.spark.SparkException: Job aborted due to stage failure: Task 0 in stage 58.0 failed 4 times, most recent failure: Lost task 0.3 in stage 58.0 (TID 246, 10.139.64.5, executor 14): java.lang.Exception: Network init call failed in LightGBM with error: Machine list file doesn&apos;t contain the local machine`
![databrickslightgbmregressor1](https://user-images.githubusercontent.com/13501239/41481403-66b8c39e-7097-11e8-8823-04abb87ee67a.JPG)

When running [this example notebook from the docs](https://github.com/Azure/mmlspark/blob/master/notebooks/samples/106%20-%20Quantile%20Regression%20with%20LightGBM.ipynb) everything works fine, but I'm running into these issues when expanding to a larger data set.

**Comment by imatiach-msft** [comment]
@JeffMacaluso sorry, this was already fixed here:
https://github.com/Azure/mmlspark/issues/292
It's just not released yet.
You can try using this build which has several fixes:

Maven package uploaded, use 
--packages com.microsoft.ml.spark:mmlspark_2.11:0.12.dev18+1.g6fbf39c 
--repositories https://mmlspark.azureedge.net/maven

We will have the fixes in the next release.  There is still another issue @ywskycn noticed where as we increase the number of executors the accuracy metrics gets worse which I still need to look into.

**Comment by imatiach-msft** [comment]
@JeffMacaluso 
Please see this PR here for more context:
https://github.com/Azure/mmlspark/pull/296

**Comment by JeffMacaluso** [comment]
@imatiach-msft My apologies, I saw that and thought it in the most recent release - I guess I need more coffee today 😅

Thank you very much! Closing this issue.

**Comment by imatiach-msft** [comment]
@JeffMacaluso here is a newer build off of latest master in case the other one I sent has been deleted or will be deleted soon (there is a retention policy for old builds, but I think it's at least one month):

--packages com.microsoft.ml.spark:mmlspark_2.11:0.12.dev19
--repositories https://mmlspark.azureedge.net/maven

**Comment by JeffMacaluso** [comment]
@imatiach-msft after attaching that version to my cluster, I was able to train regular regression models fine, but ran into a few issues when using the quantile regression method. 

Using the same data set, I was able to train a regression model in <15 seconds, but had to cancel the first quantile model (model_upper_bound) after 47 since it somehow got stuck. The second quantile model (model_lower_bound) triggered this area after ~26 minutes:
`org.apache.spark.SparkException: Job aborted due to stage failure: Task 0 in stage 49.0 failed 4 times, most recent failure: Lost task 0.3 in stage 49.0 (TID 1160, 10.139.64.9, executor 26): java.util.NoSuchElementException: key not found: 26`

![databrickslightgbmregressor3](https://user-images.githubusercontent.com/13501239/41489076-3b1bc656-70b4-11e8-9459-75d52df726cf.JPG)

I didn't see anything about this in the issues either here or in the LightGBM repository. Let me know if I should re-open this issue for those.

**Comment by gopinutakki** [comment]
Hello,

I believe there is a need to re-open this issue.
I am trying to perform 'Quantile Regression' with v0.13 and I keep getting the above mentioned error.
My dataset contains around 20 Integer features and around 10 million rows. Regular regression modeling seems to be working fine even for 1000 iterations, but Quantile Regression modeling fails even for 100 iterations.

This is the error:


---------------------------------------------------------------------------
Py4JJavaError                             Traceback (most recent call last)
<command-887568235758862> in <module>()
----> 1 model.fit(train_set_cat)

/databricks/spark/python/pyspark/ml/base.py in fit(self, dataset, params)
    130                 return self.copy(params)._fit(dataset)
    131             else:
--> 132                 return self._fit(dataset)
    133         else:
    134             raise ValueError("Params must be either a param map or a list/tuple of param maps, "

/databricks/spark/python/pyspark/ml/wrapper.py in _fit(self, dataset)
    286 
    287     def _fit(self, dataset):
--> 288         java_model = self._fit_java(dataset)
    289         model = self._create_model(java_model)
    290         return self._copyValues(model)

/databricks/spark/python/pyspark/ml/wrapper.py in _fit_java(self, dataset)
    283         """
    284         self._transfer_params_to_java()
--> 285         return self._java_obj.fit(dataset._jdf)
    286 
    287     def _fit(self, dataset):

/databricks/spark/python/lib/py4j-0.10.6-src.zip/py4j/java_gateway.py in __call__(self, *args)
   1158         answer = self.gateway_client.send_command(command)
   1159         return_value = get_return_value(
-> 1160             answer, self.gateway_client, self.target_id, self.name)
   1161 
   1162         for temp_arg in temp_args:

/databricks/spark/python/pyspark/sql/utils.py in deco(*a, **kw)
     61     def deco(*a, **kw):
     62         try:
---> 63             return f(*a, **kw)
     64         except py4j.protocol.Py4JJavaError as e:
     65             s = e.java_exception.toString()

/databricks/spark/python/lib/py4j-0.10.6-src.zip/py4j/protocol.py in get_return_value(answer, gateway_client, target_id, name)
    318                 raise Py4JJavaError(
    319                     "An error occurred while calling {0}{1}{2}.\n".
--> 320                     format(target_id, ".", name), value)
    321             else:
    322                 raise Py4JError(

Py4JJavaError: An error occurred while calling o1831.fit.
: org.apache.spark.SparkException: Job aborted due to stage failure: Task 57 in stage 196.0 failed 4 times, most recent failure: Lost task 57.3 in stage 196.0 (TID 28893, 10.139.64.12, executor 16): java.util.NoSuchElementException: key not found: 16
	at scala.collection.MapLike$class.default(MapLike.scala:228)
	at scala.collection.AbstractMap.default(Map.scala:59)
	at scala.collection.MapLike$class.apply(MapLike.scala:141)
	at scala.collection.AbstractMap.apply(Map.scala:59)
	at com.microsoft.ml.spark.TrainUtils$$anonfun$4.apply(TrainUtils.scala:195)
	at com.microsoft.ml.spark.TrainUtils$$anonfun$4.apply(TrainUtils.scala:189)
	at com.microsoft.ml.spark.StreamUtilities$.using(StreamUtilities.scala:29)
	at com.microsoft.ml.spark.TrainUtils$.trainLightGBM(TrainUtils.scala:188)
	at com.microsoft.ml.spark.LightGBMRegressor$$anonfun$1.apply(LightGBMRegressor.scala:79)
	at com.microsoft.ml.spark.LightGBMRegressor$$anonfun$1.apply(LightGBMRegressor.scala:79)
	at org.apache.spark.sql.execution.MapPartitionsExec$$anonfun$5.apply(objects.scala:189)
	at org.apache.spark.sql.execution.MapPartitionsExec$$anonfun$5.apply(objects.scala:186)
	at org.apache.spark.rdd.RDD$$anonfun$mapPartitionsInternal$1$$anonfun$apply$25.apply(RDD.scala:838)
	at org.apache.spark.rdd.RDD$$anonfun$mapPartitionsInternal$1$$anonfun$apply$25.apply(RDD.scala:838)
	at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:38)
	at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:332)
	at org.apache.spark.rdd.RDD.iterator(RDD.scala:296)
	at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:38)
	at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:332)
	at org.apache.spark.rdd.RDD.iterator(RDD.scala:296)
	at org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:87)
	at org.apache.spark.scheduler.Task.run(Task.scala:111)
	at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:350)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

Driver stacktrace:
	at org.apache.spark.scheduler.DAGScheduler.org$apache$spark$scheduler$DAGScheduler$$failJobAndIndependentStages(DAGScheduler.scala:1718)
	at org.apache.spark.scheduler.DAGScheduler$$anonfun$abortStage$1.apply(DAGScheduler.scala:1706)
	at org.apache.spark.scheduler.DAGScheduler$$anonfun$abortStage$1.apply(DAGScheduler.scala:1705)
	at scala.collection.mutable.ResizableArray$class.foreach(ResizableArray.scala:59)
	at scala.collection.mutable.ArrayBuffer.foreach(ArrayBuffer.scala:48)
	at org.apache.spark.scheduler.DAGScheduler.abortStage(DAGScheduler.scala:1705)
	at org.apache.spark.scheduler.DAGScheduler$$anonfun$handleTaskSetFailed$1.apply(DAGScheduler.scala:943)
	at org.apache.spark.scheduler.DAGScheduler$$anonfun$handleTaskSetFailed$1.apply(DAGScheduler.scala:943)
	at scala.Option.foreach(Option.scala:257)
	at org.apache.spark.scheduler.DAGScheduler.handleTaskSetFailed(DAGScheduler.scala:943)
	at org.apache.spark.scheduler.DAGSchedulerEventProcessLoop.doOnReceive(DAGScheduler.scala:1941)
	at org.apache.spark.scheduler.DAGSchedulerEventProcessLoop.onReceive(DAGScheduler.scala:1889)
	at org.apache.spark.scheduler.DAGSchedulerEventProcessLoop.onReceive(DAGScheduler.scala:1877)
	at org.apache.spark.util.EventLoop$$anon$1.run(EventLoop.scala:48)
	at org.apache.spark.scheduler.DAGScheduler.runJob(DAGScheduler.scala:740)
	at org.apache.spark.SparkContext.runJob(SparkContext.scala:2109)
	at org.apache.spark.SparkContext.runJob(SparkContext.scala:2206)
	at org.apache.spark.rdd.RDD$$anonfun$reduce$1.apply(RDD.scala:1037)
	at org.apache.spark.rdd.RDDOperationScope$.withScope(RDDOperationScope.scala:151)
	at org.apache.spark.rdd.RDDOperationScope$.withScope(RDDOperationScope.scala:112)
	at org.apache.spark.rdd.RDD.withScope(RDD.scala:371)
	at org.apache.spark.rdd.RDD.reduce(RDD.scala:1019)
	at org.apache.spark.sql.Dataset.reduce(Dataset.scala:1619)
	at com.microsoft.ml.spark.LightGBMRegressor.train(LightGBMRegressor.scala:81)
	at com.microsoft.ml.spark.LightGBMRegressor.train(LightGBMRegressor.scala:37)
	at org.apache.spark.ml.Predictor.fit(Predictor.scala:118)
	at org.apache.spark.ml.Predictor.fit(Predictor.scala:82)
	at com.microsoft.ml.spark.TrainRegressor.fit(TrainRegressor.scala:118)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at py4j.reflection.MethodInvoker.invoke(MethodInvoker.java:244)
	at py4j.reflection.ReflectionEngine.invoke(ReflectionEngine.java:380)
	at py4j.Gateway.invoke(Gateway.java:295)
	at py4j.commands.AbstractCommand.invokeMethod(AbstractCommand.java:132)
	at py4j.commands.CallCommand.execute(CallCommand.java:79)
	at py4j.GatewayConnection.run(GatewayConnection.java:226)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.util.NoSuchElementException: key not found: 16
	at scala.collection.MapLike$class.default(MapLike.scala:228)
	at scala.collection.AbstractMap.default(Map.scala:59)
	at scala.collection.MapLike$class.apply(MapLike.scala:141)
	at scala.collection.AbstractMap.apply(Map.scala:59)
	at com.microsoft.ml.spark.TrainUtils$$anonfun$4.apply(TrainUtils.scala:195)
	at com.microsoft.ml.spark.TrainUtils$$anonfun$4.apply(TrainUtils.scala:189)
	at com.microsoft.ml.spark.StreamUtilities$.using(StreamUtilities.scala:29)
	at com.microsoft.ml.spark.TrainUtils$.trainLightGBM(TrainUtils.scala:188)
	at com.microsoft.ml.spark.LightGBMRegressor$$anonfun$1.apply(LightGBMRegressor.scala:79)
	at com.microsoft.ml.spark.LightGBMRegressor$$anonfun$1.apply(LightGBMRegressor.scala:79)
	at org.apache.spark.sql.execution.MapPartitionsExec$$anonfun$5.apply(objects.scala:189)
	at org.apache.spark.sql.execution.MapPartitionsExec$$anonfun$5.apply(objects.scala:186)
	at org.apache.spark.rdd.RDD$$anonfun$mapPartitionsInternal$1$$anonfun$apply$25.apply(RDD.scala:838)
	at org.apache.spark.rdd.RDD$$anonfun$mapPartitionsInternal$1$$anonfun$apply$25.apply(RDD.scala:838)
	at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:38)
	at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:332)
	at org.apache.spark.rdd.RDD.iterator(RDD.scala:296)
	at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:38)
	at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:332)
	at org.apache.spark.rdd.RDD.iterator(RDD.scala:296)
	at org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:87)
	at org.apache.spark.scheduler.Task.run(Task.scala:111)
	at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:350)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	... 1 more

**Comment by imatiach-msft** [comment]
@gopinutakki I believe you are hitting the issue here:
https://github.com/Azure/mmlspark/issues/341
which will be in the next release.
Could you try this custom build instead, from [this PR](https://github.com/Azure/mmlspark/pull/358):

--packages com.microsoft.ml.spark:mmlspark_2.11:0.13.dev28+1.g2753705
--repositories https://mmlspark.azureedge.net/maven.

**Comment by imatiach-msft** [comment]
@gopinutakki several relevant issues that were fixed in latest release:
https://github.com/Microsoft/LightGBM/pull/1593
https://github.com/Microsoft/LightGBM/pull/1605
https://github.com/Microsoft/LightGBM/pull/1611

**Comment by gopinutakki** [comment]
@imatiach-msft Thank you for the message. Seems like the issue is resolved. I am testing Quantile Regression with several categorical features.

**Comment by imatiach-msft** [comment]
@gopinutakki how are you passing the categoricals?  I believe I still need to pass to the native lightgbm learner the list of categoricals (this should be a TODO).  Otherwise, you will need to one-hot-encode them for now.  Let me create an issue to track this.

**Comment by gopinutakki** [comment]
@imatiach-msft 
I am following this example: https://github.com/Azure/mmlspark/blob/master/notebooks/samples/105%20-%20Regression%20with%20DataConversion.ipynb

Do you think that the categorical column ids are not provided to the underlying LightGBM?
Thank you for opening a new ticket for this issue.

**Comment by imatiach-msft** [comment]
@gopinutakki it looks like it should be an easy fix, see here:
https://github.com/Microsoft/LightGBM/blob/93764fda72ed3f7144455abd1e616f98be71c554/docs/Parameters.rst#categorical_feature
and here:
https://github.com/Microsoft/LightGBM/blob/93764fda72ed3f7144455abd1e616f98be71c554/docs/Advanced-Topics.rst#categorical-feature-support
We just need to supply this parameter with the known categorical columns to lightgbm.  We can expose this parameter to the user in case the user knows they are categorical and also we can automatically infer the columns that are categorical if they have been string indexed/value indexed based on the DataFrame metadata

**Comment by imatiach-msft** [comment]
@gopinutakki as a workaround for now you can just one-hot-encode the features though (but maybe you won't get as good results) using spark's OneHotEncoderEstimator

**Comment by gopinutakki** [comment]
@imatiach-msft I see, for now I will follow your advise. Thank you.

**Comment by imatiach-msft** [comment]
@land1725 sorry about the error you are encountering - might you perchance have dynamic allocation enabled (autoscale)?  It is currently one of my todos.  For now you could disable dynamic allocation.
It looks like the error is coming from this line:
(getNodes(networkParams, networkParams.executorIdToHost(executorId), localListenPort, log), localListenPort)
specifically networkParams.executorIdToHost(executorId)
so the executor was not found in the original map in networkParams.  Might you be able to share your spark logs?

**Comment by land1725** [comment]
[Uploading sparkErrorLog.txt…]()
@imatiach-msft hello I am very happy that got your reply
this is my whole spark log,Please try to help me . LightGBM is the most important thing in my work.

**Comment by land1725** [comment]
@imatiach-msft hello I am very happy that got your reply
this is my whole spark log,Please try to help me . LightGBM is the most important thing in my work.
[sparkErrorLog.txt](https://github.com/Azure/mmlspark/files/2467070/sparkErrorLog.txt)

**Comment by land1725** [comment]
@imatiach-msft hello I have checked my spark ,Dynamic Allocation  has already disabled,and still got the error. spark.shuffle.service.enabled has been set true.Is it possible to make the error?

**Comment by imatiach-msft** [comment]
@land1725 to me it seems like you have autoscale enabled - these are the nodes found by lightgbm based on the log, it looks like there are only 2 executors, 1 and 2 at this point: 
```
18/10/10 22:12:49 INFO spark.LightGBMRegressor: Nodes used for LightGBM: (1,10.111.1.205),(2,10.111.1.204),(2,10.111.1.204),(1,10.111.1.205),(2,10.111.1.204),(1,10.111.1.205),(2,10.111.1.204),(1,10.111.1.205),(2,10.111.1.204),(1,10.111.1.205),(2,10.111.1.204),(1,10.111.1.205),(2,10.111.1.204),(1,10.111.1.205),(2,10.111.1.204),(1,10.111.1.205),(2,10.111.1.204),(1,10.111.1.205),(2,10.111.1.204),(1,10.111.1.205),(2,10.111.1.204),(1,10.111.1.205),(2,10.111.1.204),(1,10.111.1.205),(2,10.111.1.204),(1,10.111.1.205),(2,10.111.1.204),(1,10.111.1.205),(2,10.111.1.204),(1,10.111.1.205)
```
then, I see in the logs:
```
18/10/10 22:12:49 INFO scheduler.TaskSetManager: Starting task 0.0 in stage 92.0 (TID 3563, bigdata.node8, executor 1, partition 0, PROCESS_LOCAL, 8398 bytes)
18/10/10 22:12:49 INFO scheduler.TaskSetManager: Starting task 1.0 in stage 92.0 (TID 3564, bigdata.node7, executor 2, partition 1, PROCESS_LOCAL, 8398 bytes)
18/10/10 22:12:49 INFO storage.BlockManagerInfo: Added broadcast_141_piece0 in memory on bigdata.node7:42745 (size: 54.4 KB, free: 3.5 GB)
18/10/10 22:12:49 INFO storage.BlockManagerInfo: Added broadcast_141_piece0 in memory on bigdata.node8:44826 (size: 54.4 KB, free: 3.5 GB)
18/10/10 22:12:55 INFO scheduler.TaskSetManager: Starting task 2.0 in stage 92.0 (TID 3565, bigdata.node5, executor 5, partition 2, RACK_LOCAL, 8398 bytes)
18/10/10 22:12:55 INFO scheduler.TaskSetManager: Starting task 3.0 in stage 92.0 (TID 3566, bigdata.node6, executor 4, partition 3, RACK_LOCAL, 8398 bytes)
18/10/10 22:12:55 INFO scheduler.TaskSetManager: Starting task 4.0 in stage 92.0 (TID 3567, bigdata.node4, executor 3, partition 4, RACK_LOCAL, 8398 bytes)
18/10/10 22:12:56 INFO storage.BlockManagerInfo: Added broadcast_141_piece0 in memory on bigdata.node5:35133 (size: 54.4 KB, free: 3.6 GB)
18/10/10 22:12:56 INFO storage.BlockManagerInfo: Added broadcast_141_piece0 in memory on bigdata.node4:34584 (size: 54.4 KB, free: 3.6 GB)
18/10/10 22:12:56 INFO storage.BlockManagerInfo: Added broadcast_141_piece0 in memory on bigdata.node6:42863 (size: 54.4 KB, free: 3.6 GB)
18/10/10 22:12:56 INFO scheduler.TaskSetManager: Starting task 5.0 in stage 92.0 (TID 3568, bigdata.node5, executor 5, partition 5, RACK_LOCAL, 8398 bytes)
```
could you try decreasing the number of partitions used by LightGBM to be just below the number of cores?  It might work but will be slow.  I might need to get this PR to work for you: https://github.com/Azure/mmlspark/pull/369

**Comment by land1725** [comment]
@imatiach-msft hello,I need to rebuild the lightGBM myself like below,Do you have the Adding dynamic allocation package address to help me rebuild ?
git clone --recursive https://github.com/Microsoft/LightGBM ; cd LightGBM
mkdir build ; cd build
cmake -DUSE_SWIG=ON ..
make -j4

**Comment by land1725** [comment]
@imatiach-msft hello I an so sorry to tell you ,now I got no errors ,but I got stacked.
I got some log like below.you can see the full drivers logs and workers log at the end  

INFO spark.LightGBMRegressor: driver received socket from worker: 10.111.1.204:24009
INFO spark.LightGBMRegressor: driver accepting a new connection...

in LightGBMUtils.scala 
I think some nodes some port are not connected to the socket server successfully

while (hostAndPorts.size < numWorkers) {
        log.info("driver accepting a new connection...")
        val driverSocket = driverServerSocket.accept()
        val reader = new BufferedReader(new InputStreamReader(driverSocket.getInputStream))
        val comm = reader.readLine()
        log.info(s"driver received socket from worker: $comm")
        val socketAndComm = (driverSocket, comm)
        hostAndPorts += socketAndComm
      }

But I don not think this is my spark setting error ,because I found there five nodes connected to the socket server successfully

[hadoop@bigdata.node3 root]$ ss | grep 37910
tcp    ESTAB      0      0      10.222.1.128:37910                10.111.1.205:54254
tcp    ESTAB      0      0      10.222.1.128:37910                10.111.1.199:52370
tcp    ESTAB      0      0      10.222.1.128:37910                10.111.1.204:41638
tcp    ESTAB      0      0      10.222.1.128:37910                10.111.1.196:45526
tcp    ESTAB      0      0      10.222.1.128:37910                10.111.1.198:60512

in the workers log you can see  log below ,But I did not find the  log "LightGBM worker listening on"
18/10/11 16:49:48 INFO spark.LightGBMRegressor: Successfully bound to port 12408
18/10/11 16:49:48 INFO spark.LightGBMRegressor: LightGBM worker connecting to host: 10.222.1.128 and port: 32790

so after all, I think there are some reasons cause  a little workers not connected to drivers.
could you modify something to adjust this kind of errors

1: I think the best way to find ,why there are some nodes failed 
2:fix the while() code ,to adjust if some node is dead ,the lightgbm could alse run successfully

[driverLog.txt](https://github.com/Azure/mmlspark/files/2468614/driverLog.txt)
[worker_log.txt](https://github.com/Azure/mmlspark/files/2468620/worker_log.txt)

**Comment by imatiach-msft** [comment]
@land1725 the connection refused is a red herring, there should be another error on one of the other workers

**Comment by imatiach-msft** [comment]
@land1725 I've thought about (2) as well, I agree that if some nodes are dead it shouldn't wait for all of them, but it's tricky to figure out the right balance.  When there are a lot of machines, some take more than others to connect to the driver, in some cases a lot more than you would expect.  It's tricky to figure out a good threshold for this, which is why I never did it when I wrote the code at first.  It might be good to add some threshold logic though.
