### ISSUE TITLE
Flaky Tests: HTTPSource

### ISSUE THREAD

**Issue by mhamilton723** [Azure/mmlspark#322]
HTTP Tests: 

 Python Client sometimes fail with:
```
org.scalatest.exceptions.TestFailedException: "[Exception in thread Thread-3:
Traceback (most recent call last):
File "/home/eli/lib/conda/lib/python3.6/site-packages/urllib3/connectionpool.py", line 387, in _make_request
six.raise_from(e, None)
File "<string>", line 2, in raise_from
File "/home/eli/lib/conda/lib/python3.6/site-packages/urllib3/connectionpool.py", line 383, in _make_request
httplib_response = conn.getresponse()
File "/home/eli/lib/conda/lib/python3.6/http/client.py", line 1331, in getresponse
response.begin()
File "/home/eli/lib/conda/lib/python3.6/http/client.py", line 297, in begin
version, status, reason = self._read_status()
File "/home/eli/lib/conda/lib/python3.6/http/client.py", line 258, in _read_status
line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
File "/home/eli/lib/conda/lib/python3.6/socket.py", line 586, in readinto
return self._sock.recv_into(b)
socket.timeout: timed out
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
File "/home/eli/lib/conda/lib/python3.6/site-packages/requests/adapters.py", line 440, in send
timeout=timeout
File "/home/eli/lib/conda/lib/python3.6/site-packages/urllib3/connectionpool.py", line 639, in urlopen
_stacktrace=sys.exc_info()[2])
File "/home/eli/lib/conda/lib/python3.6/site-packages/urllib3/util/retry.py", line 357, in increment
raise six.reraise(type(error), error, _stacktrace)
File "/home/eli/lib/conda/lib/python3.6/site-packages/urllib3/packages/six.py", line 686, in reraise
raise value
File "/home/eli/lib/conda/lib/python3.6/site-packages/urllib3/connectionpool.py", line 601, in urlopen
chunked=chunked)
File "/home/eli/lib/conda/lib/python3.6/site-packages/urllib3/connectionpool.py", line 389, in _make_request
self._raise_timeout(err=e, url=url, timeout_value=read_timeout)
File "/home/eli/lib/conda/lib/python3.6/site-packages/urllib3/connectionpool.py", line 309, in _raise_timeout
raise ReadTimeoutError(self, url, "Read timed out. (read timeout=%s)" % timeout_value)
urllib3.exceptions.ReadTimeoutError: HTTPConnectionPool(host='localhost', port=35015): Read timed out. (read timeout=15)
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
File "/home/eli/lib/conda/lib/python3.6/threading.py", line 916, in _bootstrap_inner
self.run()
File "/tmp/MML-Test-1168536756193524612/pythonClient.py", line 18, in run
timeout=15)
File "/home/eli/lib/conda/lib/python3.6/site-packages/requests/sessions.py", line 555, in post
return self.request('POST', url, data=data, json=json, **kwargs)
File "/home/eli/lib/conda/lib/python3.6/site-packages/requests/sessions.py", line 508, in request
resp = self.send(prep, **send_kwargs)
File "/home/eli/lib/conda/lib/python3.6/site-packages/requests/sessions.py", line 618, in send
r = adapter.send(request, **kwargs)
File "/home/eli/lib/conda/lib/python3.6/site-packages/requests/adapters.py", line 521, in send
raise ReadTimeout(e, request=request)
requests.exceptions.ReadTimeout: HTTPConnectionPool(host='localhost', port=35015): Read timed out. (read timeout=15)
]" did not equal "[]"
at org.scalatest.Assertions$class.newAssertionFailedException(Assertions.scala:528)
at org.scalatest.FunSuite.newAssertionFailedException(FunSuite.scala:1560)
at org.scalatest.Assertions$AssertionsHelper.macroAssert(Assertions.scala:501)
at com.microsoft.ml.spark.DistributedHTTPSuite$$anonfun$2$$anonfun$apply$mcV$sp$3.apply(DistributedHTTPSuite.scala:145)
at com.microsoft.ml.spark.DistributedHTTPSuite$$anonfun$2$$anonfun$apply$mcV$sp$3.apply(DistributedHTTPSuite.scala:141)
at scala.collection.Iterator$class.foreach(Iterator.scala:893)
at scala.collection.AbstractIterator.foreach(Iterator.scala:1336)
at scala.collection.IterableLike$class.foreach(IterableLike.scala:72)
at scala
```
async client:

```
Cannot start query with name foo as a query with that name is already active
```

**Comment by mhamilton723** [comment]
Havent seen this in a while
