### ISSUE TITLE
java.lang.NoClassDefFoundError: spray/json/JsonFormat 

### ISSUE THREAD

**Issue by anaveenan** [Azure/mmlspark#359]
Trying to test regression model and getting the following error (python 2.7 and spark 2.0.1). Any pointers. Thanks

```
data = df.select(["education", "marital_status", "hours_per_week", "income"])
#train, test = data.randomSplit([0.75, 0.25], seed=123)
from pyspark.sql.types import DoubleType
data = data.withColumn("hours_per_week", data["hours_per_week"].cast(DoubleType()))
model = TrainClassifier(model=LogisticRegression(), labelCol="income").fit(train)

```

---------------------------------------------------------------------------
Py4JJavaError                             Traceback (most recent call last)
<ipython-input-8-ce128a3a3113> in <module>()
----> 1 model = TrainClassifier(model=LogisticRegression(), labelCol="income").fit(train)

/var/user/spark-2.0.1/python/pyspark/ml/base.py in fit(self, dataset, params)
     62                 return self.copy(params)._fit(dataset)
     63             else:
---> 64                 return self._fit(dataset)
     65         else:
     66             raise ValueError("Params must be either a param map or a list/tuple of param maps, "

/var/user/spark-2.0.1/python/pyspark/ml/wrapper.py in _fit(self, dataset)
    211 
    212     def _fit(self, dataset):
--> 213         java_model = self._fit_java(dataset)
    214         return self._create_model(java_model)
    215 

/var/user/spark-2.0.1/python/pyspark/ml/wrapper.py in _fit_java(self, dataset)
    208         """
    209         self._transfer_params_to_java()
--> 210         return self._java_obj.fit(dataset._jdf)
    211 
    212     def _fit(self, dataset):

/var/user/spark-2.0.1/python/lib/py4j-0.10.3-src.zip/py4j/java_gateway.py in __call__(self, *args)
   1131         answer = self.gateway_client.send_command(command)
   1132         return_value = get_return_value(
-> 1133             answer, self.gateway_client, self.target_id, self.name)
   1134 
   1135         for temp_arg in temp_args:

/var/user/spark-2.0.1/python/pyspark/sql/utils.py in deco(*a, **kw)
     61     def deco(*a, **kw):
     62         try:
---> 63             return f(*a, **kw)
     64         except py4j.protocol.Py4JJavaError as e:
     65             s = e.java_exception.toString()

/var/user/spark-2.0.1/python/lib/py4j-0.10.3-src.zip/py4j/protocol.py in get_return_value(answer, gateway_client, target_id, name)
    317                 raise Py4JJavaError(
    318                     "An error occurred while calling {0}{1}{2}.\n".
--> 319                     format(target_id, ".", name), value)
    320             else:
    321                 raise Py4JError(

Py4JJavaError: An error occurred while calling o78.fit.
: java.lang.NoClassDefFoundError: spray/json/JsonFormat
	at com.microsoft.ml.spark.Featurize.<init>(Featurize.scala:31)
	at com.microsoft.ml.spark.Featurize.<init>(Featurize.scala:26)
	at com.microsoft.ml.spark.TrainClassifier.fit(TrainClassifier.scala:162)
	at com.microsoft.ml.spark.TrainClassifier.fit(TrainClassifier.scala:40)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at py4j.reflection.MethodInvoker.invoke(MethodInvoker.java:237)
	at py4j.reflection.ReflectionEngine.invoke(ReflectionEngine.java:357)
	at py4j.Gateway.invoke(Gateway.java:280)
	at py4j.commands.AbstractCommand.invokeMethod(AbstractCommand.java:132)
	at py4j.commands.CallCommand.execute(CallCommand.java:79)
	at py4j.GatewayConnection.run(GatewayConnection.java:214)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.ClassNotFoundException: spray.json.JsonFormat
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 15 more

**Comment by imatiach-msft** [comment]
could you update spark to the latest version (2.3)?  or is that not an option?

**Comment by imatiach-msft** [comment]
it looks like this library is now working for you:
https://github.com/spray/spray-json
what version of java and scala are you using?

**Comment by anaveenan** [comment]
Getting same with 2.3.1
Scala version 2.11.8
Java version 1.8.0_51


---------------------------------------------------------------------------
Py4JJavaError                             Traceback (most recent call last)
<ipython-input-8-ce128a3a3113> in <module>()
----> 1 model = TrainClassifier(model=LogisticRegression(), labelCol="income").fit(train)

/var/user/spark-2.3.1/python/pyspark/ml/base.py in fit(self, dataset, params)
    130                 return self.copy(params)._fit(dataset)
    131             else:
--> 132                 return self._fit(dataset)
    133         else:
    134             raise ValueError("Params must be either a param map or a list/tuple of param maps, "

/var/user/spark-2.3.1/python/pyspark/ml/wrapper.py in _fit(self, dataset)
    286 
    287     def _fit(self, dataset):
--> 288         java_model = self._fit_java(dataset)
    289         model = self._create_model(java_model)
    290         return self._copyValues(model)

/var/user/spark-2.3.1/python/pyspark/ml/wrapper.py in _fit_java(self, dataset)
    283         """
    284         self._transfer_params_to_java()
--> 285         return self._java_obj.fit(dataset._jdf)
    286 
    287     def _fit(self, dataset):

/var/user/spark-2.3.1/python/lib/py4j-0.10.7-src.zip/py4j/java_gateway.py in __call__(self, *args)
   1255         answer = self.gateway_client.send_command(command)
   1256         return_value = get_return_value(
-> 1257             answer, self.gateway_client, self.target_id, self.name)
   1258 
   1259         for temp_arg in temp_args:

/var/user/spark-2.3.1/python/pyspark/sql/utils.py in deco(*a, **kw)
     61     def deco(*a, **kw):
     62         try:
---> 63             return f(*a, **kw)
     64         except py4j.protocol.Py4JJavaError as e:
     65             s = e.java_exception.toString()

/var/user/spark-2.3.1/python/lib/py4j-0.10.7-src.zip/py4j/protocol.py in get_return_value(answer, gateway_client, target_id, name)
    326                 raise Py4JJavaError(
    327                     "An error occurred while calling {0}{1}{2}.\n".
--> 328                     format(target_id, ".", name), value)
    329             else:
    330                 raise Py4JError(

Py4JJavaError: An error occurred while calling o91.fit.
: java.lang.NoClassDefFoundError: spray/json/JsonFormat
	at com.microsoft.ml.spark.Featurize.<init>(Featurize.scala:31)
	at com.microsoft.ml.spark.Featurize.<init>(Featurize.scala:26)
	at com.microsoft.ml.spark.TrainClassifier.fit(TrainClassifier.scala:162)
	at com.microsoft.ml.spark.TrainClassifier.fit(TrainClassifier.scala:40)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at py4j.reflection.MethodInvoker.invoke(MethodInvoker.java:244)
	at py4j.reflection.ReflectionEngine.invoke(ReflectionEngine.java:357)
	at py4j.Gateway.invoke(Gateway.java:282)
	at py4j.commands.AbstractCommand.invokeMethod(AbstractCommand.java:132)
	at py4j.commands.CallCommand.execute(CallCommand.java:79)
	at py4j.GatewayConnection.run(GatewayConnection.java:238)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.ClassNotFoundException: spray.json.JsonFormat
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 15 more

**Comment by anaveenan** [comment]
It worked by adding jars from my code. Thanks for helping. Is there document for lightgbm on spark (specifically looking for all parmaters for loss function). Thanks
`--jars Azure_mmlspark-0.13.jar,spray-json_2.10-1.2.5.jar`

**Comment by imatiach-msft** [comment]
@anaveenan does this overview help:
https://github.com/Azure/mmlspark/blob/master/docs/lightgbm.md
also we have a lot of notebooks here:
https://github.com/Azure/mmlspark/tree/master/notebooks/samples
here is one small example with LightGBM:
https://github.com/Azure/mmlspark/blob/master/notebooks/samples/106%20-%20Quantile%20Regression%20with%20LightGBM.ipynb
since you are using python you can also type help(...)

**Comment by imatiach-msft** [comment]
@anaveenan if you are using lightgbm you will also need to include the lightgbm jar as a dependency.  But really, you shouldn't need any of this at all.  How did you install and run spark?  Did you specify --packages when running pyspark?

**Comment by imatiach-msft** [comment]
eg if you are running pyspark you would run it via:
pyspark --packages Azure:mmlspark:0.13
[see here](https://github.com/Azure/mmlspark#spark-package)

**Comment by anaveenan** [comment]
I am using this production environment to develop models in ipython
notebook (I don't have control over installation of spark and Scala).

pyspark --packages Azure:mmlspark:0.13 option for some reason is not
working for notebook (I can try again)

export SPARK_HOME=/var/user/spark-2.3.1
export PATH=$SPARK_HOME/bin:$PATH
export PYTHONPATH=$SPARK_HOME/python/lib/py4j-0.10.7-src.zip/:$PYTHONPATH
export PYTHONPATH=./Azure_mmlspark-0.13.jar
export PYSPARK_DRIVER_PYTHON=/home/user/anaconda/envs/sparkpy27/bin/ipython
export PYSPARK_DRIVER_PYTHON_OPTS="notebook
--NotebookApp.open_browser=False --NotebookApp.ip='10.20.71.88'
--NotebookApp.port=27456"
/var/user/spark-2.3.1/bin/pyspark --master yarn --deploy-mode client
--packages com.databricks:spark-csv_2.11:1.5.0 --queue public
--executor-memory 10g --driver-memory 3g --executor-cores 4 --jars
Azure_mmlspark-0.13.jar,spray-json_2.10-1.2.5.jar

**Comment by mhamilton723** [comment]
@anaveenan thanks for reaching out! Lets try to unblock you from using the 0.13 version first. Then we can see if we can repro this on our side and push any needed fixes. What is happening with your 0.13 version?

**Comment by mhamilton723** [comment]
closing this due to inactivity. Please re-open if the issue persists with the latest version on maven
