### ISSUE TITLE
Support higher bit depth images with ImageSchema

### ISSUE THREAD

**Issue by luzlab** [Azure/mmlspark#360]
We're developing machine vision solutions for in-process monitoring of manufacturing processes, including collecting wide-field absorbance maps. The camera is 16-bit and optimized for collecting low-noise quantitative data suitable for feeding deconvolution/superresolution analysis pipelines.

We currently use OpenCV to process the images, and generate 16-bit unsigned single channel and 32-bit floating point single channel data. Both formats are supported by OpenCV.

The current implementation of ImageSchema creates only 8bit image dataframes.

How challenging would it be to support additional types? If someone could provide guidance, I'd be willing to work on this.

**Comment by imatiach-msft** [comment]
the schema should allow any type:
https://github.com/Azure/mmlspark/blob/0deeca8304fae8734b5eb0a23ac68c3412f25446/src/core/schema/src/main/scala/ImageSchema.scala#L17

**Comment by imatiach-msft** [comment]
maybe you could send some example code with a few sample images and we could take a look?

**Comment by imatiach-msft** [comment]
@luzlab if it is failing, I think it should not be difficult to add support

**Comment by luzlab** [comment]
It's definitely failing when I try to import some images. I've gotten errors loading 8bit RGBA images and 16bit gray (1 channel) images.

```
java.lang.Exception: Results too large
	at com.databricks.backend.daemon.driver.OutputAggregator$.maybeApplyOutputAggregation(OutputAggregator.scala:193)
	at com.databricks.backend.daemon.driver.OutputAggregator$.withOutputAggregation0(OutputAggregator.scala:122)
	at com.databricks.backend.daemon.driver.OutputAggregator$.withOutputAggregation(OutputAggregator.scala:51)
	at com.databricks.backend.daemon.driver.PythonDriverLocal$$anonfun$getResultBufferInternal$1.apply(PythonDriverLocal.scala:553)
	at com.databricks.backend.daemon.driver.PythonDriverLocal$$anonfun$getResultBufferInternal$1.apply(PythonDriverLocal.scala:518)
	at com.databricks.backend.daemon.driver.PythonDriverLocal.withInterpLock(PythonDriverLocal.scala:471)
	at com.databricks.backend.daemon.driver.PythonDriverLocal.getResultBufferInternal(PythonDriverLocal.scala:518)
	at com.databricks.backend.daemon.driver.DriverLocal.getResultBuffer(DriverLocal.scala:321)
	at com.databricks.backend.daemon.driver.PythonDriverLocal.com$databricks$backend$daemon$driver$PythonDriverLocal$$outputSuccess(PythonDriverLocal.scala:505)
	at com.databricks.backend.daemon.driver.PythonDriverLocal$$anonfun$repl$3.apply(PythonDriverLocal.scala:221)
	at com.databricks.backend.daemon.driver.PythonDriverLocal$$anonfun$repl$3.apply(PythonDriverLocal.scala:218)
	at com.databricks.backend.daemon.driver.PythonDriverLocal.withInterpLock(PythonDriverLocal.scala:471)
	at com.databricks.backend.daemon.driver.PythonDriverLocal.repl(PythonDriverLocal.scala:218)
	at com.databricks.backend.daemon.driver.DriverLocal$$anonfun$execute$3.apply(DriverLocal.scala:248)
	at com.databricks.backend.daemon.driver.DriverLocal$$anonfun$execute$3.apply(DriverLocal.scala:228)
	at com.databricks.logging.UsageLogging$$anonfun$withAttributionContext$1.apply(UsageLogging.scala:188)
	at scala.util.DynamicVariable.withValue(DynamicVariable.scala:58)
	at com.databricks.logging.UsageLogging$class.withAttributionContext(UsageLogging.scala:183)
	at com.databricks.backend.daemon.driver.DriverLocal.withAttributionContext(DriverLocal.scala:40)
	at com.databricks.logging.UsageLogging$class.withAttributionTags(UsageLogging.scala:221)
	at com.databricks.backend.daemon.driver.DriverLocal.withAttributionTags(DriverLocal.scala:40)
	at com.databricks.backend.daemon.driver.DriverLocal.execute(DriverLocal.scala:228)
	at com.databricks.backend.daemon.driver.DriverWrapper$$anonfun$tryExecutingCommand$2.apply(DriverWrapper.scala:595)
	at com.databricks.backend.daemon.driver.DriverWrapper$$anonfun$tryExecutingCommand$2.apply(DriverWrapper.scala:595)
	at scala.util.Try$.apply(Try.scala:192)
	at com.databricks.backend.daemon.driver.DriverWrapper.tryExecutingCommand(DriverWrapper.scala:590)
	at com.databricks.backend.daemon.driver.DriverWrapper.getCommandOutputAndError(DriverWrapper.scala:474)
	at com.databricks.backend.daemon.driver.DriverWrapper.executeCommand(DriverWrapper.scala:548)
	at com.databricks.backend.daemon.driver.DriverWrapper.runInnerLoop(DriverWrapper.scala:380)
	at com.databricks.backend.daemon.driver.DriverWrapper.runInner(DriverWrapper.scala:327)
	at com.databricks.backend.daemon.driver.DriverWrapper.run(DriverWrapper.scala:215)
	at java.lang.Thread.run(Thread.java:748)
java.lang.Ex
```

**Comment by imatiach-msft** [comment]
@luzlab hmm it looks like the error is "results too large", maybe there isn't enough memory on the cluster?  I don't see any mmlspark code in the stack trace above.  Strange.  If the images are not confidential, can you send some sample images (even 5 or 6) that generate the error?

**Comment by luzlab** [comment]
Also, why doesn't this library display a preview of the image like spark-deep-learning?

**Comment by luzlab** [comment]
Here are some sample images.
![8bit3channel](https://user-images.githubusercontent.com/9924835/44699686-3a6f5500-aa3a-11e8-8965-f547a9309dde.png)
![16bit1channel](https://user-images.githubusercontent.com/9924835/44699687-3b07eb80-aa3a-11e8-871b-111f0e23eeb1.png)
![8bit1channel](https://user-images.githubusercontent.com/9924835/44699688-3b07eb80-aa3a-11e8-8da8-6da2ca2b5ecd.png)

**Comment by imatiach-msft** [comment]
@luzlab thanks, I've never heard of the preview feature for images, interesting.  I'm not sure how a preview can be generated.

**Comment by luzlab** [comment]
When you display the dataframe, you get a nice preview image. It's not a necessity, but definitely nice to have. This just makes me wonder about why there's two different implementations for reading images into a Data Frame... 

![image](https://user-images.githubusercontent.com/9924835/44699745-7f938700-aa3a-11e8-8698-cdb52806b0e3.png)

**Comment by imatiach-msft** [comment]
it's interesting to me because I was the one who added image schema/support in apache spark :) https://github.com/apache/spark/pull/19439

**Comment by luzlab** [comment]
I'll confess I'm a little confused about the differences between the libraries in regards to processing images.

![image](https://user-images.githubusercontent.com/9924835/44699865-14968000-aa3b-11e8-8bf8-0f4a9bccc964.png)

**Comment by imatiach-msft** [comment]
It's the same, we merged from mmlspark to apache/spark.  We've updated it more in mmlspark though, eventually we need to do another merge.  Otherwise, we would just take the version from apache/spark, which we should eventually do.

**Comment by luzlab** [comment]
OK... Given there's some differences in the API, like "path" vs "origin" and "mode" vs "type", which one should I expect to be in the final API?

Were you able to reproduce the errors reading the attached images?

**Comment by imatiach-msft** [comment]
what is the difference between cmd 5 and 6?  It looks like 6 shows the image but 5 does not?  Interesting, will have to take a look in DataBricks, that's very cool that they added this feature!

**Comment by luzlab** [comment]
There's a checkbox called "Show Preview Image" that's unchecked in command 5.

**Comment by imatiach-msft** [comment]
sorry, I'm finishing up something else right now, will take a look as soon as I'm done with the current task

**Comment by imatiach-msft** [comment]
"OK... Given there's some differences in the API, like "path" vs "origin" and "mode" vs "type", which one should I expect to be in the final API?"
good point, there were some code review changes during the merge, we should probably merge some of those back.  Sorry for the confusion, I will need to discuss more with @mhamilton723 .

**Comment by imatiach-msft** [comment]
I agree that it is confusing to have multiple different implementations, that is very good feedback!

**Comment by luzlab** [comment]
Thank you for responding so quickly!

**Comment by imatiach-msft** [comment]
@luzlab how large is your cluster (machines/memory per machine)?  how many images are you trying to load?  if you do have a lot of nodes you might not have optimally configured your cluster, the configuration is sometimes half of the battle.

**Comment by luzlab** [comment]
I'm loading a single image. I just restarted the cluster. The cluster uses DS3V2 machines (4 cores, 16gb ram, 2 workers).

Can you check the bit depth of the images you downloaded? Perhaps Github resamples/optimizes image attachments and converts them to 8- or lower bits/pixel to save space?

![image](https://user-images.githubusercontent.com/9924835/44777490-a5e71e80-ab2f-11e8-88bd-fac24898480d.png)

**Comment by imatiach-msft** [comment]
@luzlab you're right, I just checked on my ubuntu machine:
```
~/mmlspark/src/io/image/src/test/scala/16bit$ file 44699686-3a6f5500-aa3a-11e8-8965-f547a9309dde.png
44699686-3a6f5500-aa3a-11e8-8965-f547a9309dde.png: PNG image data, 3060 x 2100, 8-bit/color RGBA, non-interlaced
```
It looks like github downsamples.  Could you send the images to me directly at mmlspark-support@microsoft.com ?  I can take another look.

**Comment by luzlab** [comment]
I just two images - 16-bit monochrome and 32-bit floating point monochrome.

**Comment by luzlab** [comment]
@imatiach-msft Did you receive the sample images? Were you able to reproduce the errors?

BTW - I also [cross posted](https://github.com/databricks/spark-deep-learning/issues/154) this issue

**Comment by luzlab** [comment]
@imatiach-msft Any update?

**Comment by imatiach-msft** [comment]
hi @luzlab , sorry for the delay, I updated the branch I had with the 16-bit image you sent me and it still works fine:
https://github.com/imatiach-msft/mmlspark/tree/ilmat/16-bit-images
sorry, I'm really not sure what is causing your errors, it sounds like a cluster configuration issue - but you can run the test in my branch on any images you have to verify that they work.  Hope this helps!

**Comment by imatiach-msft** [comment]
@luzlab sorry, were you able to take another look at this issue?

**Comment by luzlab** [comment]
Unfortunately, I'm no longer at the company and so I don't have access to Databricks anymore. I'll try to get this installed on my personal computer and test...

When you imported the images, what was the reported image type?

**Comment by mhamilton723** [comment]
We changed our image schema to be exactly aligned with the schema in core, and added a few additional checks to improve stability. Closing the issue but feel free to re-open if you are running into trouble
