### ISSUE TITLE
lightgbm: many executor id have change

### ISSUE THREAD

**Issue by flybywind** [Azure/mmlspark#397]
I use spark to train lightgbm, in driver it would save a map for every exector id and its ip address, however I noticed that my executor's id will change while running, so the exception will be thrown out:

```
18/10/16 10:59:53 WARN scheduler.TaskSetManager: Lost task 33.1 in stage 5.0 (TID 596, zjy-hadoop-prc-st2076.bj, executor 32): java.util.NoSuchElementException: key not found: 32 
    at scala.collection.MapLike$class.default(MapLike.scala:228)
    at scala.collection.AbstractMap.default(Map.scala:59)
    at scala.collection.MapLike$class.apply(MapLike.scala:141)
    at scala.collection.AbstractMap.apply(Map.scala:59)
    at com.microsoft.ml.spark.TrainUtils$$anonfun$4.apply(TrainUtils.scala:201)
    at com.microsoft.ml.spark.TrainUtils$$anonfun$4.apply(TrainUtils.scala:195)
    at com.microsoft.ml.spark.StreamUtilities$.using(StreamUtilities.scala:29)
    at com.microsoft.ml.spark.TrainUtils$.trainLightGBM(TrainUtils.scala:194)
    at com.microsoft.ml.spark.LightGBMRegressor$$anonfun$1.apply(LightGBMRegressor.scala:81)
    at com.microsoft.ml.spark.LightGBMRegressor$$anonfun$1.apply(LightGBMRegressor.scala:81)
    at org.apache.spark.sql.execution.MapPartitionsExec$$anonfun$6.apply(objects.scala:186)
    at org.apache.spark.sql.execution.MapPartitionsExec$$anonfun$6.apply(objects.scala:183)
    at org.apache.spark.rdd.RDD$$anonfun$mapPartitionsInternal$1$$anonfun$apply$25.apply(RDD.scala:826)
    at org.apache.spark.rdd.RDD$$anonfun$mapPartitionsInternal$1$$anonfun$apply$25.apply(RDD.scala:826)
    at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:38)
    at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:323)
    at org.apache.spark.rdd.RDD.iterator(RDD.scala:287)
    at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:38)
    at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:323)
    at org.apache.spark.rdd.RDD.iterator(RDD.scala:287)
    at org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:87)
    at org.apache.spark.scheduler.Task.run(Task.scala:99)
    at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:318)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
    at java.lang.Thread.run(Thread.java:748)
```

the logs in driver is:
```
18/10/16 10:36:53 INFO spark.LightGBMRegressor: driver expecting 64 connections...
18/10/16 10:36:53 INFO spark.LightGBMRegressor: driver accepting a new connection...
18/10/16 10:36:53 INFO spark.LightGBMRegressor: driver waiting for connections on host: 10.101.11.57 and port: 5920
...... 
// notice that there is no executor id 32
18/10/16 10:38:11 INFO spark.LightGBMRegressor: Nodes used for LightGBM: (4,10.152.116.7),(29,10.152.69.47),(52,10.152.75.26),(33,10.152.115.16),(35,10.152.46.2),(64,10.152.85.10),(14,10.152.88.10),(63,10.152.73.21),(21,10.152.49.6),(13,10.152.106.29),(47,10.152.69.23),(49,10.152.44.43),(17,10.152.46.8),(45,10.152.40.7),(5,10.152.116.7),(24,10.152.118.14),(27,10.152.111.2),(25,10.152.47.27),(53,10.152.44.15),(23,10.152.44.23),(7,10.152.96.46),(12,10.152.106.29),(31,10.152.46.9),(54,10.152.93.30),(55,10.152.80.4),(1,10.152.46.43),(40,10.152.78.21),(24,10.152.118.14),(9,10.152.81.50),(23,10.152.44.23),(49,10.152.44.43),(17,10.152.46.8),(45,10.152.40.7),(12,10.152.106.29),(52,10.152.75.26),(33,10.152.115.16),(31,10.152.46.9),(53,10.152.44.15),(5,10.152.116.7),(4,10.152.116.7),(35,10.152.46.2),(22,10.152.43.13),(55,10.152.80.4),(47,10.152.69.23),(63,10.152.73.21),(24,10.152.118.14),(54,10.152.93.30),(11,10.152.111.27),(7,10.152.96.46),(25,10.152.47.27),(13,10.152.106.29),(27,10.152.111.2),(1,10.152.46.43),(29,10.152.69.47),(37,10.152.81.47),(14,10.152.88.10),(21,10.152.49.6),(23,10.152.44.23),(45,10.152.40.7),(17,10.152.46.8),(64,10.152.85.10),(40,10.152.78.21),(52,10.152.75.26),(12,10.152.106.29)

```
so the executor will repeatedly failed.

**Comment by flybywind** [comment]
add a pull request:
https://github.com/Azure/mmlspark/pull/399
