### ISSUE TITLE
`GLIBCXX_3.4.20' not found error in version 0.16

### ISSUE THREAD

**Issue by land1725** [Azure/mmlspark#533]
@imatiach-msft
Hello,I am so sorry to tell that I faced the same problems when I use released 0.16 version on Centos 7.

Could you rebuild the 0.16 version on CentOs 7 and provide me the maven address to download?

    <dependency>
        <groupId>Azure</groupId>
        <artifactId>mmlspark</artifactId>
        <version>0.16</version>
    </dependency>
19/04/08 18:07:01 WARN scheduler.TaskSetManager: Lost task 2.0 in stage 71.0 (TID 8298, bigdata.node4, executor 3): java.lang.UnsatisfiedLinkError: /data/cdh/yarn/nm/usercache/hadoop/appcache/application_1551665533369_5974/container_1551665533369_5974_01_000004/tmp/mml-natives5619078166263179450/lib_lightgbm.so: /lib64/libstdc++.so.6: version `GLIBCXX_3.4.20' not found (required by /data/cdh/yarn/nm/usercache/hadoop/appcache/application_1551665533369_5974/container_1551665533369_5974_01_000004/tmp/mml-natives5619078166263179450/lib_lightgbm.so)
at java.lang.ClassLoader$NativeLibrary.load(Native Method)
at java.lang.ClassLoader.loadLibrary0(ClassLoader.java:1941)
at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1824)
at java.lang.Runtime.load0(Runtime.java:809)
at java.lang.System.load(System.java:1086)
at com.microsoft.ml.spark.NativeLoader.loadLibraryByName(NativeLoader.java:59)
at com.microsoft.ml.spark.LightGBMUtils$.initializeNativeLibrary(LightGBMUtils.scala:38)
at com.microsoft.ml.spark.TrainUtils$$anonfun$5.apply(TrainUtils.scala:208)
at com.microsoft.ml.spark.TrainUtils$$anonfun$5.apply(TrainUtils.scala:205)
at com.microsoft.ml.spark.StreamUtilities$.using(StreamUtilities.scala:29)
at com.microsoft.ml.spark.TrainUtils$.trainLightGBM(TrainUtils.scala:204)
at com.microsoft.ml.spark.LightGBMClassifier$$anonfun$3.apply(LightGBMClassifier.scala:83)
at com.microsoft.ml.spark.LightGBMClassifier$$anonfun$3.apply(LightGBMClassifier.scala:83)
at org.apache.spark.sql.execution.MapPartitionsExec$$anonfun$5.apply(objects.scala:188)
at org.apache.spark.sql.execution.MapPartitionsExec$$anonfun$5.apply(objects.scala:185)
at org.apache.spark.rdd.RDD$$anonfun$mapPartitionsInternal$1$$anonfun$apply$25.apply(RDD.scala:830)
at org.apache.spark.rdd.RDD$$anonfun$mapPartitionsInternal$1$$anonfun$apply$25.apply(RDD.scala:830)
at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:38)
at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:324)
at org.apache.spark.rdd.RDD.iterator(RDD.scala:288)
at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:38)
at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:324)
at org.apache.spark.rdd.RDD.iterator(RDD.scala:288)
at org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:87)
at org.apache.spark.scheduler.Task.run(Task.scala:109)
at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:345)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:748)

**Comment by imatiach-msft** [comment]
@land1725 sure, would you be able to build LightGBM with SWIG on centos:
https://github.com/Microsoft/LightGBM/blob/master/docs/Installation-Guide.rst#build-java-wrapper
I can then create a PR referencing that jar and create a build similar to last time.
If you are not able to create the jar, I can try to install cent OS or get a VM with it when I have some free time, but it might take a couple days (as I am busy working on next release of explain model package: https://pypi.org/project/azureml-explain-model/).

**Comment by land1725** [comment]
> @land1725 sure, would you be able to build LightGBM with SWIG on centos:
> https://github.com/Microsoft/LightGBM/blob/master/docs/Installation-Guide.rst#build-java-wrapper
> I can then create a PR referencing that jar and create a build similar to last time.
> If you are not able to create the jar, I can try to install cent OS or get a VM with it when I have some free time, but it might take a couple days (as I am busy working on next release of explain model package: https://pypi.org/project/azureml-explain-model/).

thanks for your quick reply , and I will rebuild the LightGBM myself.

**Comment by imatiach-msft** [comment]
closing as now we use the official linux .so files produced from Microsoft/LightGBM build, which uses ubuntu 14.04 docker that does not have the glibc issue.
This was fixed with the PR:
https://github.com/Azure/mmlspark/pull/526
Which updates the lightgbm version to:
"com.microsoft.ml.lightgbm" %  "lightgbmlib" % "2.2.350"
It should be available in next release.  For now, you can use the latest builds from master, eg the build for that PR was:

--packages 
com.microsoft.ml.spark:mmlspark_2.11:0.17.dev1+1.g5e0b2a0
and --repositories 
https://mmlspark.azureedge.net/maven
