### ISSUE TITLE
java.lang.UnsatisfiedLinkError: Could not load all CNTK libraries because we encountered the following error: No space left on device

### ISSUE THREAD

**Issue by rupeshmore85** [Azure/mmlspark#535]
I am trying to run below example on Spark v2.3.cloudera4 on yarn hadoop cluster: https://github.com/Azure/mmlspark/blob/master/notebooks/samples/DeepLearning%20-%20Flower%20Image%20Classification.ipynb

```
$ pyspark2 --master yarn --deploy-mode client --packages Azure:mmlspark:0.16 --conf "spark.local.dir=/way/tmp/"
Python 3.6.0 |Anaconda 4.3.0 (64-bit)| (default, Dec 23 2016, 12:22:00) 
[GCC 4.4.7 20120313 (Red Hat 4.4.7-1)] on linux
Type "help", "copyright", "credits" or "license" for more information.
[main] INFO com.unraveldata.agent.ResourceCollector - Unravel Sensor 4.5.0.4rc0012/1.3.11.3 initializing.
Ivy Default Cache set to: /csnzoo/rmore/.ivy2/cache
The jars for the packages stored in: /csnzoo/rmore/.ivy2/jars
:: loading settings :: url = jar:file:/opt/cloudera/parcels/SPARK2-2.3.0.cloudera4-1.cdh5.13.3.p0.611179/lib/spark2/jars/ivy-2.4.0.jar!/org/apache/ivy/core/settings/ivysettings.xml
Azure#mmlspark added as a dependency
:: resolving dependencies :: org.apache.spark#spark-submit-parent-6c2a2bc6-2027-423d-9f6f-b7f96405dcf6;1.0
	confs: [default]
	found Azure#mmlspark;0.16 in spark-packages
	found io.spray#spray-json_2.11;1.3.2 in central
	found com.microsoft.cntk#cntk;2.4 in central
	found org.openpnp#opencv;3.2.0-1 in central
	found com.jcraft#jsch;0.1.54 in central
	found org.apache.httpcomponents#httpclient;4.5.6 in central
	found org.apache.httpcomponents#httpcore;4.4.10 in central
	found commons-logging#commons-logging;1.2 in central
	found commons-codec#commons-codec;1.10 in central
	found com.microsoft.ml.lightgbm#lightgbmlib;2.2.200 in central
:: resolution report :: resolve 1594ms :: artifacts dl 160ms
	:: modules in use:
	Azure#mmlspark;0.16 from spark-packages in [default]
	com.jcraft#jsch;0.1.54 from central in [default]
	com.microsoft.cntk#cntk;2.4 from central in [default]
	com.microsoft.ml.lightgbm#lightgbmlib;2.2.200 from central in [default]
	commons-codec#commons-codec;1.10 from central in [default]
	commons-logging#commons-logging;1.2 from central in [default]
	io.spray#spray-json_2.11;1.3.2 from central in [default]
	org.apache.httpcomponents#httpclient;4.5.6 from central in [default]
	org.apache.httpcomponents#httpcore;4.4.10 from central in [default]
	org.openpnp#opencv;3.2.0-1 from central in [default]
	---------------------------------------------------------------------
	|                  |            modules            ||   artifacts   |
	|       conf       | number| search|dwnlded|evicted|| number|dwnlded|
	---------------------------------------------------------------------
	|      default     |   10  |   0   |   0   |   0   ||   10  |   0   |
	---------------------------------------------------------------------
:: retrieving :: org.apache.spark#spark-submit-parent-6c2a2bc6-2027-423d-9f6f-b7f96405dcf6
	confs: [default]
	0 artifacts copied, 10 already retrieved (0kB/55ms)
Setting default log level to "WARN".
To adjust logging level use sc.setLogLevel(newLevel). For SparkR, use setLogLevel(newLevel).
19/04/09 15:13:23 WARN spark.SparkConf: In Spark 1.0 and later spark.local.dir will be overridden by the value set by the cluster manager (via SPARK_LOCAL_DIRS in mesos/standalone and LOCAL_DIRS in YARN).
19/04/09 15:13:31 WARN yarn.Client: Same path resource file:///csnzoo/rmore/.ivy2/jars/Azure_mmlspark-0.16.jar added multiple times to distributed cache.
19/04/09 15:13:31 WARN yarn.Client: Same path resource file:///csnzoo/rmore/.ivy2/jars/io.spray_spray-json_2.11-1.3.2.jar added multiple times to distributed cache.
19/04/09 15:13:31 WARN yarn.Client: Same path resource file:///csnzoo/rmore/.ivy2/jars/com.microsoft.cntk_cntk-2.4.jar added multiple times to distributed cache.
19/04/09 15:13:31 WARN yarn.Client: Same path resource file:///csnzoo/rmore/.ivy2/jars/org.openpnp_opencv-3.2.0-1.jar added multiple times to distributed cache.
19/04/09 15:13:31 WARN yarn.Client: Same path resource file:///csnzoo/rmore/.ivy2/jars/com.jcraft_jsch-0.1.54.jar added multiple times to distributed cache.
19/04/09 15:13:31 WARN yarn.Client: Same path resource file:///csnzoo/rmore/.ivy2/jars/org.apache.httpcomponents_httpclient-4.5.6.jar added multiple times to distributed cache.
19/04/09 15:13:31 WARN yarn.Client: Same path resource file:///csnzoo/rmore/.ivy2/jars/com.microsoft.ml.lightgbm_lightgbmlib-2.2.200.jar added multiple times to distributed cache.
19/04/09 15:13:31 WARN yarn.Client: Same path resource file:///csnzoo/rmore/.ivy2/jars/org.apache.httpcomponents_httpcore-4.4.10.jar added multiple times to distributed cache.
19/04/09 15:13:31 WARN yarn.Client: Same path resource file:///csnzoo/rmore/.ivy2/jars/commons-logging_commons-logging-1.2.jar added multiple times to distributed cache.
19/04/09 15:13:31 WARN yarn.Client: Same path resource file:///csnzoo/rmore/.ivy2/jars/commons-codec_commons-codec-1.10.jar added multiple times to distributed cache.
19/04/09 15:13:39 WARN util.Json: Json Factory has already been set up. Ignoring this attempt.
Welcome to
      ____              __
     / __/__  ___ _____/ /__
    _\ \/ _ \/ _ `/ __/  '_/
   /__ / .__/\_,_/_/ /_/\_\   version 2.3.0.cloudera4
      /_/

Using Python version 3.6.0 (default, Dec 23 2016 12:22:00)
SparkSession available as 'spark'.
>>> 
>>> import pyspark
>>> from pyspark.sql.functions import udf, col
>>> from pyspark.sql.types import IntegerType, StringType, DoubleType
>>> from pyspark.ml import Transformer, Estimator, Pipeline
>>> from pyspark.ml.classification import LogisticRegression
>>> from mmlspark import *
>>> 
>>> import numpy as np, pandas as pd, os, sys, time
>>> from os.path import join, abspath, exists
>>> model = ModelDownloader(spark, "/models").downloadByName("ResNet50")
>>> model = ModelDownloader(spark, "models").downloadByName("ResNet50")
>>> 
>>> 
>>> imagesWithLabels = spark.read.parquet("wasbs://publicwasb@mmlspark.blob.core.windows.net/flowers_and_labels2.parquet") \
...     .withColumnRenamed("bytes","image").sample(.1)
19/04/09 15:16:53 WARN impl.MetricsConfig: Cannot locate configuration: tried hadoop-metrics2-azure-file-system.properties,hadoop-metrics2.properties
19/04/09 15:17:07 ERROR security.JniBasedUnixGroupsMapping: error looking up the name of group 52497: No such file or directory
>>> 
>>> imagesWithLabels.printSchema()
root
 |-- filename: string (nullable = true)
 |-- image: binary (nullable = true)
 |-- labels: double (nullable = true)

>>> it = ImageTransformer()\
...     .setOutputCol("scaled")\
...     .resize(height = 60, width = 60)
>>> 
>>> ur = UnrollImage()\
...     .setInputCol("scaled")\
...     .setOutputCol("features")
>>>     
... dc1 = DropColumns().setCols(["scaled", "image"])
>>> 
>>> lr1 = LogisticRegression().setFeaturesCol("features").setLabelCol("labels")
>>> 
>>> dc2 = DropColumns().setCols(["features"])
>>> 
>>> basicModel = Pipeline(stages=[it, ur, dc1, lr1, dc2])
>>> resnet = ImageFeaturizer()\
...     .setInputCol("image")\
...     .setOutputCol("features")\
...     .setModelLocation(model.uri)\
...     .setLayerNames(model.layerNames)\
...     .setCutOutputLayers(1)
Traceback (most recent call last):
  File "<stdin>", line 4, in <module>
  File "/way/tmp/rmore/spark-ea3eab5f-88d4-4e6d-bdc2-54b24d65ecae/userFiles-69094a20-eb0d-4dff-a6dd-360566d30627/Azure_mmlspark-0.16.jar/mmlspark/ImageFeaturizer.py", line 22, in setModelLocation
  File "/opt/cloudera/parcels/SPARK2-2.3.0.cloudera4-1.cdh5.13.3.p0.611179/lib/spark2/python/lib/py4j-0.10.7-src.zip/py4j/java_gateway.py", line 1257, in __call__
  File "/opt/cloudera/parcels/SPARK2-2.3.0.cloudera4-1.cdh5.13.3.p0.611179/lib/spark2/python/pyspark/sql/utils.py", line 63, in deco
    return f(*a, **kw)
  File "/opt/cloudera/parcels/SPARK2-2.3.0.cloudera4-1.cdh5.13.3.p0.611179/lib/spark2/python/lib/py4j-0.10.7-src.zip/py4j/protocol.py", line 328, in get_return_value
py4j.protocol.Py4JJavaError: An error occurred while calling o90.setModelLocation.
: java.lang.UnsatisfiedLinkError: Could not load all CNTK libraries because we encountered the following error: No space left on device
	at com.microsoft.CNTK.CNTKNativeUtils.loadAll(CNTKNativeUtils.java:72)
	at com.microsoft.CNTK.CNTKLibJNI.<clinit>(CNTKLibJNI.java:189)
	at com.microsoft.CNTK.DeviceDescriptor.useDefaultDevice(DeviceDescriptor.java:88)
	at com.microsoft.CNTK.SerializableFunction$.loadModelFromBytes$default$2(SerializableFunction.scala:80)
	at com.microsoft.ml.spark.CNTKModel.setModelLocation(CNTKModel.scala:176)
	at com.microsoft.ml.spark.ImageFeaturizer.setModelLocation(ImageFeaturizer.scala:70)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at py4j.reflection.MethodInvoker.invoke(MethodInvoker.java:244)
	at py4j.reflection.ReflectionEngine.invoke(ReflectionEngine.java:357)
	at py4j.Gateway.invoke(Gateway.java:282)
	at py4j.commands.AbstractCommand.invokeMethod(AbstractCommand.java:132)
	at py4j.commands.CallCommand.execute(CallCommand.java:79)
	at py4j.GatewayConnection.run(GatewayConnection.java:238)
	at java.lang.Thread.run(Thread.java:748)

>>> 

```
I have specified the `spark.local.dir` to avoid defaulting to `/tmp` but still i get (No space left I see space available). Am I missing something ?
````
$ df -h /way/tmp
Filesystem               Size  Used Avail Use% Mounted on
/dev/mapper/VG0-way   50G   16G   35G  32% /way
```
Thank you!

**Comment by mhamilton723** [comment]
Hey @rupeshmore85 thanks for the feedback. CNTK and other jars with native dependencies use tmp to mount natives for use. Try rebooting the nodes or clearing out Tmp to free up space. We clean up these files if the process exits correctly but if it’s killed or force quit these tmp files won’t be cleaned. Hope that helps!
