### ISSUE TITLE
TabularLime errors

### ISSUE THREAD

**Issue by phillyfan1138** [Azure/mmlspark#570]
I'm getting the following errors when using TabularLime:
"java.lang.ClassCastException: org.apache.spark.ml.classification.RandomForestClassifier cannot be cast to org.apache.spark.ml.Transformer"

Based off the [tests ](https://github.com/Azure/mmlspark/blob/99d267a407c07301dcada42f788ef7b92ef15aa5/src/image-featurizer/src/test/scala/LIMESuite.scala) for TabularLime, I should be calling a "fit" on TabularLime and then a "transform".  The following  shows my code to replicate this error:

```python
from pyspark.sql import SparkSession
from pyspark.ml.feature import VectorAssembler
from pyspark.ml import Pipeline
from pyspark.ml.classification import RandomForestClassifier

spark = SparkSession\
    .builder\
    .appName("pyspark")\
    .getOrCreate()

from mmlspark import *
from mmlspark import FluentAPI   

def generateDataFrame(spark):
  data=[
    {'x1':3, 'x2':4, 'y':1}, 
    {'x1':2, 'x2':1, 'y':0}, 
    {'x1':2, 'x2':2, 'y':0}, 
    {'x1':3, 'x2':5, 'y':1}
  ]
  return spark.createDataFrame(data)


vectorAssembler = VectorAssembler()\
  .setInputCols(["x1", "x2"])\
  .setOutputCol("features")
  
model=RandomForestClassifier(featuresCol="features", labelCol="y")

pipeline = Pipeline(stages=[
  vectorAssembler, model
])
  
data=generateDataFrame(spark)

fitmodel=pipeline.fit(data)

lime = TabularLIME()\
  .setModel(model)\
  .setPredictionCol("prediction")\
  .setOutputCol("weights")\
  .setInputCol("features")

result = lime.fit(fitmodel.transform(data))

#This is where the error occurs
result.transform(fitmodel.transform(data))

spark.stop()
```

**Comment by mhamilton723** [comment]
Thanks for reaching out! Try using the fitModel as the model for LIME as opposed to the model. The error is basically pointing out that the model you are trying to interpret hasn’t been fit yet. If you paste the full stack trace i can turn it into a more user friendly error message for future use :)

Get Outlook for iOS<https://aka.ms/o0ukef>

________________________________

**Comment by phillyfan1138** [comment]
Yes, I found that error :).  It still gives me a different error now that I've fixed that.  See my edited code above.

**Comment by mhamilton723** [comment]
@phillyfan1138 can you paste the full stacktrace? THanks for your help

**Comment by phillyfan1138** [comment]
@mhamilton723 

IllegalArgumentException: 'Output column features already exists.'
Py4JJavaError                             Traceback (most recent call last)
/opt/cloudera/parcels/SPARK2/lib/spark2/python/pyspark/sql/utils.py in deco(*a, **kw)
     62         try:
---> 63             return f(*a, **kw)
     64         except py4j.protocol.Py4JJavaError as e:

/usr/local/lib/python3.6/site-packages/py4j/protocol.py in get_return_value(answer, gateway_client, target_id, name)
    327                     "An error occurred while calling {0}{1}{2}.\n".
--> 328                     format(target_id, ".", name), value)
    329             else:

Py4JJavaError: An error occurred while calling o313.transform.
: java.lang.IllegalArgumentException: Output column features already exists.
	at org.apache.spark.ml.feature.VectorAssembler.transformSchema(VectorAssembler.scala:127)
	at org.apache.spark.ml.PipelineModel$$anonfun$transformSchema$5.apply(Pipeline.scala:311)
	at org.apache.spark.ml.PipelineModel$$anonfun$transformSchema$5.apply(Pipeline.scala:311)
	at scala.collection.IndexedSeqOptimized$class.foldl(IndexedSeqOptimized.scala:57)
	at scala.collection.IndexedSeqOptimized$class.foldLeft(IndexedSeqOptimized.scala:66)
	at scala.collection.mutable.ArrayOps$ofRef.foldLeft(ArrayOps.scala:186)
	at org.apache.spark.ml.PipelineModel.transformSchema(Pipeline.scala:311)
	at org.apache.spark.ml.PipelineStage.transformSchema(Pipeline.scala:74)
	at org.apache.spark.ml.PipelineModel.transform(Pipeline.scala:305)
	at com.microsoft.ml.spark.DataFrameSugars.mlTransform(FluentAPI.scala:15)
	at com.microsoft.ml.spark.TabularLIMEModel.transform(LIME.scala:232)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at py4j.reflection.MethodInvoker.invoke(MethodInvoker.java:244)
	at py4j.reflection.ReflectionEngine.invoke(ReflectionEngine.java:357)
	at py4j.Gateway.invoke(Gateway.java:282)
	at py4j.commands.AbstractCommand.invokeMethod(AbstractCommand.java:132)
	at py4j.commands.CallCommand.execute(CallCommand.java:79)
	at py4j.GatewayConnection.run(GatewayConnection.java:238)
	at java.lang.Thread.run(Thread.java:748)


During handling of the above exception, another exception occurred:

IllegalArgumentException                  Traceback (most recent call last)
in engine
----> 1 result.transform(fitmodel.transform(data))

/opt/cloudera/parcels/SPARK2/lib/spark2/python/pyspark/ml/base.py in transform(self, dataset, params)
    171                 return self.copy(params)._transform(dataset)
    172             else:
--> 173                 return self._transform(dataset)
    174         else:
    175             raise ValueError("Params must be a param map but got %s." % type(params))

/opt/cloudera/parcels/SPARK2/lib/spark2/python/pyspark/ml/wrapper.py in _transform(self, dataset)
    303     def _transform(self, dataset):
    304         self._transfer_params_to_java()
--> 305         return DataFrame(self._java_obj.transform(dataset._jdf), dataset.sql_ctx)
    306 
    307 

/usr/local/lib/python3.6/site-packages/py4j/java_gateway.py in __call__(self, *args)
   1255         answer = self.gateway_client.send_command(command)
   1256         return_value = get_return_value(
-> 1257             answer, self.gateway_client, self.target_id, self.name)
   1258 
   1259         for temp_arg in temp_args:

/opt/cloudera/parcels/SPARK2/lib/spark2/python/pyspark/sql/utils.py in deco(*a, **kw)
     77                 raise QueryExecutionException(s.split(': ', 1)[1], stackTrace)
     78             if s.startswith('java.lang.IllegalArgumentException: '):
---> 79                 raise IllegalArgumentException(s.split(': ', 1)[1], stackTrace)
     80             raise
     81     return deco

IllegalArgumentException: 'Output column features already exists.'

**Comment by ralf0615** [comment]
@phillyfan1138 This is Yuchen Li, I reached out to me today via LinkedIn, it seems to me that I have found the solution. Please execute the following code and see if it helps :D

df_train = spark.sparkContext.parallelize(
        [Row(x1=3, x2=4, x3=1),
         Row(x1=2, x2=1, x3=0),
         Row(x1=2, x2=2, x3=0),
         Row(x1=3, x2=5, x3=1)
         ]).toDF()

df_scoring = spark.sparkContext.parallelize(
        [Row(x1=3, x2=4, x3=1),
         Row(x1=2, x2=1, x3=0),
         Row(x1=1, x2=2, x3=0),
         Row(x1=1, x2=5, x3=1)
         ]).toDF()

vectorAssembler = VectorAssembler() \
    .setInputCols(["x1", "x2"]) \
    .setOutputCol("features")

prepared_df_train = vectorAssembler.transform(df_train)
prepared_df_scoring = vectorAssembler.transform(df_scoring)

model = RandomForestClassifier(featuresCol="features", labelCol="x3")

fitted_model = model.fit(prepared_df_train)

lime = mmlspark.TabularLIME() \
    .setModel(fitted_model) \
    .setPredictionCol("prediction") \
    .setOutputCol("weights") \
    .setInputCol("features")

lime_model = lime.fit(prepared_df_scoring)

result = lime_model.transform(prepared_df_scoring)

**Comment by phillyfan1138** [comment]
Interesting.  It seems like the fact that my "fitted model" is a PipelineModel may be the issue here.

**Comment by phillyfan1138** [comment]
For comparison:

```python
from pyspark.sql import SparkSession
from pyspark.ml.feature import VectorAssembler
from pyspark.ml import Pipeline
from pyspark.ml.classification import RandomForestClassifier

spark = SparkSession\
    .builder\
    .appName("pyspark")\
    .getOrCreate()

from mmlspark import *
from mmlspark import FluentAPI   

def generateDataFrame(spark):
  data=[
    {'x1':3, 'x2':4, 'y':1}, 
    {'x1':2, 'x2':1, 'y':0}, 
    {'x1':2, 'x2':2, 'y':0}, 
    {'x1':3, 'x2':5, 'y':1}
  ]
  return spark.createDataFrame(data)


vectorAssembler = VectorAssembler()\
  .setInputCols(["x1", "x2"])\
  .setOutputCol("features")
  
model=RandomForestClassifier(featuresCol="features", labelCol="y")

## TEST 1: Pipeline.  This doesn't work
pipeline = Pipeline(stages=[
  vectorAssembler, model
])
  
data=generateDataFrame(spark)

fitmodel=pipeline.fit(data)

lime = TabularLIME()\
  .setModel(fitmodel)\
  .setPredictionCol("prediction")\
  .setOutputCol("weights")\
  .setInputCol("features")

fdta=fitmodel.transform(data).drop('prediction', 'probability', 'rawPrediction')
result = lime.fit(fdta)

#This is where the error occurs
r=result.transform(fdta)

## TEST 2: Model.  This works
data1=vectorAssembler.transform(data)
fitmodel2=model.fit(data1)
lime = TabularLIME()\
  .setModel(fitmodel2)\
  .setPredictionCol("prediction")\
  .setOutputCol("weights")\
  .setInputCol("features")
result = lime.fit(data1)
r=result.transform(data1)

spark.stop()
```

**Comment by mhamilton723** [comment]
@phillyfan1138 thanks for the detailed repro, will try to make the pipelineModel work in the future!

**Comment by sacmax** [comment]
> @phillyfan1138 This is Yuchen Li, I reached out to me today via LinkedIn, it seems to me that I have found the solution. Please execute the following code and see if it helps :D
> 
> df_train = spark.sparkContext.parallelize(
> [Row(x1=3, x2=4, x3=1),
> Row(x1=2, x2=1, x3=0),
> Row(x1=2, x2=2, x3=0),
> Row(x1=3, x2=5, x3=1)
> ]).toDF()
> 
> df_scoring = spark.sparkContext.parallelize(
> [Row(x1=3, x2=4, x3=1),
> Row(x1=2, x2=1, x3=0),
> Row(x1=1, x2=2, x3=0),
> Row(x1=1, x2=5, x3=1)
> ]).toDF()
> 
> vectorAssembler = VectorAssembler()
> .setInputCols(["x1", "x2"])
> .setOutputCol("features")
> 
> prepared_df_train = vectorAssembler.transform(df_train)
> prepared_df_scoring = vectorAssembler.transform(df_scoring)
> 
> model = RandomForestClassifier(featuresCol="features", labelCol="x3")
> 
> fitted_model = model.fit(prepared_df_train)
> 
> lime = mmlspark.TabularLIME()
> .setModel(fitted_model)
> .setPredictionCol("prediction")
> .setOutputCol("weights")
> .setInputCol("features")
> 
> lime_model = lime.fit(prepared_df_scoring)
> 
> result = lime_model.transform(prepared_df_scoring)

I there a way to use explainer after the above code?

**Comment by r12king** [comment]
I am getting a similar error with my pipeline model. I separated the pipeline and did the vector assembling separately from the lgbm model. Any idea what could be causing this issue?

SparkException: Job aborted due to stage failure: Task 0 in stage 49.0 failed 4 times, most recent failure: Lost task 0.3 in stage 49.0 (TID 1321, 10.139.64.62, executor 26): org.apache.spark.SparkException: Failed to execute user defined function($anonfun$12: (struct<type:tinyint,size:int,indices:array<int>,values:array<double>>) => array<struct<type:tinyint,size:int,indices:array<int>,values:array<double>>>)
	at org.apache.spark.sql.catalyst.expressions.GeneratedClass$GeneratedIteratorForCodegenStage1.generate_doConsume_0$(Unknown Source)
	at org.apache.spark.sql.catalyst.expressions.GeneratedClass$GeneratedIteratorForCodegenStage1.processNext(Unknown Source)
	at org.apache.spark.sql.execution.BufferedRowIterator.hasNext(BufferedRowIterator.java:43)
	at org.apache.spark.sql.execution.WholeStageCodegenExec$$anonfun$13$$anon$1.hasNext(WholeStageCodegenExec.scala:640)
	at scala.collection.Iterator$$anon$11.hasNext(Iterator.scala:409)
	at scala.collection.Iterator$$anon$11.hasNext(Iterator.scala:409)
	at scala.collection.Iterator$class.isEmpty(Iterator.scala:331)
	at scala.collection.AbstractIterator.isEmpty(Iterator.scala:1334)
	at com.microsoft.ml.spark.lime.LIMEUtils$$anonfun$localAggregateBy$1.apply(LIME.scala:51)
	at com.microsoft.ml.spark.lime.LIMEUtils$$anonfun$localAggregateBy$1.apply(LIME.scala:50)
	at org.apache.spark.sql.execution.MapPartitionsExec$$anonfun$5.apply(objects.scala:200)
	at org.apache.spark.sql.execution.MapPartitionsExec$$anonfun$5.apply(objects.scala:197)
	at org.apache.spark.rdd.RDD$$anonfun$mapPartitionsInternal$1$$anonfun$apply$24.apply(RDD.scala:865)
	at org.apache.spark.rdd.RDD$$anonfun$mapPartitionsInternal$1$$anonfun$apply$24.apply(RDD.scala:865)
	at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:60)
	at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:353)
	at org.apache.spark.rdd.RDD.iterator(RDD.scala:317)
	at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:60)
	at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:353)
	at org.apache.spark.rdd.RDD.iterator(RDD.scala:317)
	at org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:90)
	at org.apache.spark.scheduler.Task.doRunTask(Task.scala:140)
	at org.apache.spark.scheduler.Task.run(Task.scala:113)
	at org.apache.spark.executor.Executor$TaskRunner$$anonfun$13.apply(Executor.scala:533)
	at org.apache.spark.util.Utils$.tryWithSafeFinally(Utils.scala:1541)
	at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:539)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.ClassCastException: org.apache.spark.ml.linalg.SparseVector cannot be cast to org.apache.spark.ml.linalg.DenseVector
	at com.microsoft.ml.spark.lime.TabularLIMEModel$$anonfun$12.apply(LIME.scala:222)
	... 29 more

Driver stacktrace:

**Comment by allarddewinter** [comment]
@r12king: I am having the same error message.

This part works like a charm:
> lime_model = lime.fit(prepared_df_scoring)
>
> result = lime_model.transform(prepared_df_scoring)

But when I am trying to view the results, by doing display(result) or result.show(5), it gives me the exact same error message.

I tried manually creating a DenseVector from the SparseVector (the 'weights' column) using an udf, as that seems to be causing the error, but that also gives me the same error message. 

Any suggestion what I can try next?

**Comment by jennyivy** [comment]
> @r12king: I am having the same error message.
> 
> This part works like a charm:
> 
> > lime_model = lime.fit(prepared_df_scoring)
> > result = lime_model.transform(prepared_df_scoring)
> 
> But when I am trying to view the results, by doing display(result) or result.show(5), it gives me the exact same error message.
> 
> I tried manually creating a DenseVector from the SparseVector (the 'weights' column) using an udf, as that seems to be causing the error, but that also gives me the same error message.
> 
> Any suggestion what I can try next?

i had the same problem. can you display or show your result now?

**Comment by allarddewinter** [comment]
> > @r12king: I am having the same error message.
> > This part works like a charm:
> > > lime_model = lime.fit(prepared_df_scoring)
> > > result = lime_model.transform(prepared_df_scoring)
> > 
> > 
> > But when I am trying to view the results, by doing display(result) or result.show(5), it gives me the exact same error message.
> > I tried manually creating a DenseVector from the SparseVector (the 'weights' column) using an udf, as that seems to be causing the error, but that also gives me the same error message.
> > Any suggestion what I can try next?
> 
> i had the same problem. can you display or show your result now?

No it is not possible, I keep receiving the same error message. In the end I switched to the regular LIME package in combination with sklearn, which is slow, but it works.

I don't know if it makes a difference, but I use databricks (Databricks Runtime Version 6.5, Apache Spark 2.4.5, Scala 2.11 and mmlspark 2.11:1.0.0-rc1).
