### ISSUE TITLE
`GLIBCXX_3.4.20' not found

### ISSUE THREAD

**Issue by yinshurman** [Azure/mmlspark#592]
java.lang.UnsatisfiedLinkError: /data/yarn/nm/usercache/root/appcache/application_1558406713531_0488/container_1558406713531_0488_01_000018/tmp/mml-natives8624054304531690193/lib_lightgbm.so: /lib64/libstdc++.so.6: version `GLIBCXX_3.4.20' not found (required by /data/yarn/nm/usercache/root/appcache/application_1558406713531_0488/container_1558406713531_0488_01_000018/tmp/mml-natives8624054304531690193/lib_lightgbm.so)
  at java.lang.ClassLoader$NativeLibrary.load(Native Method)
  at java.lang.ClassLoader.loadLibrary0(ClassLoader.java:1941)
  at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1824)
  at java.lang.Runtime.load0(Runtime.java:809)
  at java.lang.System.load(System.java:1086)
  at com.microsoft.ml.spark.NativeLoader.loadLibraryByName(NativeLoader.java:59)
  at com.microsoft.ml.spark.LightGBMUtils$.initializeNativeLibrary(LightGBMUtils.scala:38)
  at com.microsoft.ml.spark.TrainUtils$$anonfun$7.apply(TrainUtils.scala:301)
  at com.microsoft.ml.spark.TrainUtils$$anonfun$7.apply(TrainUtils.scala:298)
  at com.microsoft.ml.spark.StreamUtilities$.using(StreamUtilities.scala:29)
  at com.microsoft.ml.spark.TrainUtils$.trainLightGBM(TrainUtils.scala:297)
  at com.microsoft.ml.spark.LightGBMBase$$anonfun$4.apply(LightGBMBase.scala:49)
  at com.microsoft.ml.spark.LightGBMBase$$anonfun$4.apply(LightGBMBase.scala:49)
  at org.apache.spark.sql.execution.MapPartitionsExec$$anonfun$5.apply(objects.scala:188)
  at org.apache.spark.sql.execution.MapPartitionsExec$$anonfun$5.apply(objects.scala:185)
  at org.apache.spark.rdd.RDD$$anonfun$mapPartitionsInternal$1$$anonfun$apply$24.apply(RDD.scala:836)
  at org.apache.spark.rdd.RDD$$anonfun$mapPartitionsInternal$1$$anonfun$apply$24.apply(RDD.scala:836)
  at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:52)
  at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:324)
  at org.apache.spark.rdd.RDD.iterator(RDD.scala:288)
  at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:52)
  at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:324)
  at org.apache.spark.rdd.RDD.iterator(RDD.scala:288)
  at org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:90)
  at org.apache.spark.scheduler.Task.run(Task.scala:121)
  at org.apache.spark.executor.Executor$TaskRunner$$anonfun$11.apply(Executor.scala:407)
  at org.apache.spark.util.Utils$.tryWithSafeFinally(Utils.scala:1360)
  at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:413)
  at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
  at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
  at java.lang.Thread.run(Thread.java:748)

**Comment by yinshurman** [comment]
I use CDH  spark cluster with  centos 7.2;when fit the model ,I got this error? any suggest?

**Comment by yinshurman** [comment]
the mmlspark version is 0.17

**Comment by yinshurman** [comment]
also I found a  same closed issue here https://github.com/Azure/mmlspark/issues/533.
but it said this problem was solved in version 0.17, it seems not.

**Comment by imatiach-msft** [comment]
hi @yinshurman , sorry about any confusion, actually the fix is not in 0.17 but on latest master and should be available in the next release (0.18).  For now you could use a private build as recommended on that issue.
