### ISSUE TITLE
java.net.ConnectException: Connection refused (Connection refused) when using LightGBMClassifier with lambdarank objective

### ISSUE THREAD

**Issue by Simon-Bru** [Azure/mmlspark#600]
Hi,

I am trying to train a lambdarank model using LightGBMClassifier but I get a ConnectException while executing lgbm.fit(train). 
I really don't understand why I encounter that issue and the stack trace is not very explicit. 
I followed this guide: https://github.com/microsoft/recommenders/blob/master/notebooks/02_model/mmlspark_lightgbm_criteo.ipynb

And everything worked fine, but I am trying to adapt and use a lambdarank algorithm to get ranked recommendations.

If anyone can help me on this bug, I would be very grateful

Here's the Stack Trace: 

```
---------------------------------------------------------------------------
Py4JJavaError                             Traceback (most recent call last)
<command-780990571047582> in <module>()
----> 1 model = lgbm.fit(train)
      2 predictions = model.transform(test)

/databricks/spark/python/pyspark/ml/base.py in fit(self, dataset, params)
    130                 return self.copy(params)._fit(dataset)
    131             else:
--> 132                 return self._fit(dataset)
    133         else:
    134             raise ValueError("Params must be either a param map or a list/tuple of param maps, "

/databricks/spark/python/pyspark/ml/wrapper.py in _fit(self, dataset)
    293 
    294     def _fit(self, dataset):
--> 295         java_model = self._fit_java(dataset)
    296         model = self._create_model(java_model)
    297         return self._copyValues(model)

/databricks/spark/python/pyspark/ml/wrapper.py in _fit_java(self, dataset)
    290         """
    291         self._transfer_params_to_java()
--> 292         return self._java_obj.fit(dataset._jdf)
    293 
    294     def _fit(self, dataset):

/databricks/spark/python/lib/py4j-0.10.7-src.zip/py4j/java_gateway.py in __call__(self, *args)
   1255         answer = self.gateway_client.send_command(command)
   1256         return_value = get_return_value(
-> 1257             answer, self.gateway_client, self.target_id, self.name)
   1258 
   1259         for temp_arg in temp_args:

/databricks/spark/python/pyspark/sql/utils.py in deco(*a, **kw)
     61     def deco(*a, **kw):
     62         try:
---> 63             return f(*a, **kw)
     64         except py4j.protocol.Py4JJavaError as e:
     65             s = e.java_exception.toString()

/databricks/spark/python/lib/py4j-0.10.7-src.zip/py4j/protocol.py in get_return_value(answer, gateway_client, target_id, name)
    326                 raise Py4JJavaError(
    327                     "An error occurred while calling {0}{1}{2}.\n".
--> 328                     format(target_id, ".", name), value)
    329             else:
    330                 raise Py4JError(

Py4JJavaError: An error occurred while calling o1670.fit.
: org.apache.spark.SparkException: Job aborted due to stage failure: Task 5 in stage 248.0 failed 4 times, most recent failure: Lost task 5.3 in stage 248.0 (TID 8019, 10.139.64.5, executor 1): java.net.ConnectException: Connection refused (Connection refused)
	at java.net.PlainSocketImpl.socketConnect(Native Method)
	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350)
	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
	at java.net.Socket.connect(Socket.java:589)
	at java.net.Socket.connect(Socket.java:538)
	at java.net.Socket.<init>(Socket.java:434)
	at java.net.Socket.<init>(Socket.java:211)
	at com.microsoft.ml.spark.TrainUtils$.getNetworkInitNodes(TrainUtils.scala:240)
	at com.microsoft.ml.spark.TrainUtils$$anonfun$7.apply(TrainUtils.scala:303)
	at com.microsoft.ml.spark.TrainUtils$$anonfun$7.apply(TrainUtils.scala:298)
	at com.microsoft.ml.spark.StreamUtilities$.using(StreamUtilities.scala:29)
	at com.microsoft.ml.spark.TrainUtils$.trainLightGBM(TrainUtils.scala:297)
	at com.microsoft.ml.spark.LightGBMBase$$anonfun$4.apply(LightGBMBase.scala:49)
	at com.microsoft.ml.spark.LightGBMBase$$anonfun$4.apply(LightGBMBase.scala:49)
	at org.apache.spark.sql.execution.MapPartitionsExec$$anonfun$6.apply(objects.scala:200)
	at org.apache.spark.sql.execution.MapPartitionsExec$$anonfun$6.apply(objects.scala:197)
	at org.apache.spark.rdd.RDD$$anonfun$mapPartitionsInternal$1$$anonfun$apply$24.apply(RDD.scala:849)
	at org.apache.spark.rdd.RDD$$anonfun$mapPartitionsInternal$1$$anonfun$apply$24.apply(RDD.scala:849)
	at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:56)
	at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:337)
	at org.apache.spark.rdd.RDD.iterator(RDD.scala:301)
	at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:56)
	at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:337)
	at org.apache.spark.rdd.RDD.iterator(RDD.scala:301)
	at org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:90)
	at org.apache.spark.scheduler.Task.run(Task.scala:124)
	at org.apache.spark.executor.Executor$TaskRunner$$anonfun$11.apply(Executor.scala:459)
	at org.apache.spark.util.Utils$.tryWithSafeFinally(Utils.scala:1401)
	at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:465)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

Driver stacktrace:
	at org.apache.spark.scheduler.DAGScheduler.org$apache$spark$scheduler$DAGScheduler$$failJobAndIndependentStages(DAGScheduler.scala:2025)
	at org.apache.spark.scheduler.DAGScheduler$$anonfun$abortStage$1.apply(DAGScheduler.scala:2013)
	at org.apache.spark.scheduler.DAGScheduler$$anonfun$abortStage$1.apply(DAGScheduler.scala:2012)
	at scala.collection.mutable.ResizableArray$class.foreach(ResizableArray.scala:59)
	at scala.collection.mutable.ArrayBuffer.foreach(ArrayBuffer.scala:48)
	at org.apache.spark.scheduler.DAGScheduler.abortStage(DAGScheduler.scala:2012)
	at org.apache.spark.scheduler.DAGScheduler$$anonfun$handleTaskSetFailed$1.apply(DAGScheduler.scala:1057)
	at org.apache.spark.scheduler.DAGScheduler$$anonfun$handleTaskSetFailed$1.apply(DAGScheduler.scala:1057)
	at scala.Option.foreach(Option.scala:257)
	at org.apache.spark.scheduler.DAGScheduler.handleTaskSetFailed(DAGScheduler.scala:1057)
	at org.apache.spark.scheduler.DAGSchedulerEventProcessLoop.doOnReceive(DAGScheduler.scala:2248)
	at org.apache.spark.scheduler.DAGSchedulerEventProcessLoop.onReceive(DAGScheduler.scala:2196)
	at org.apache.spark.scheduler.DAGSchedulerEventProcessLoop.onReceive(DAGScheduler.scala:2184)
	at org.apache.spark.util.EventLoop$$anon$1.run(EventLoop.scala:49)
	at org.apache.spark.scheduler.DAGScheduler.runJob(DAGScheduler.scala:854)
	at org.apache.spark.SparkContext.runJob(SparkContext.scala:2186)
	at org.apache.spark.SparkContext.runJob(SparkContext.scala:2283)
	at org.apache.spark.rdd.RDD$$anonfun$reduce$1.apply(RDD.scala:1048)
	at org.apache.spark.rdd.RDDOperationScope$.withScope(RDDOperationScope.scala:151)
	at org.apache.spark.rdd.RDDOperationScope$.withScope(RDDOperationScope.scala:112)
	at org.apache.spark.rdd.RDD.withScope(RDD.scala:376)
	at org.apache.spark.rdd.RDD.reduce(RDD.scala:1030)
	at org.apache.spark.sql.Dataset$$anonfun$reduce$1.apply(Dataset.scala:1644)
	at org.apache.spark.sql.Dataset$$anonfun$withNewRDDExecutionId$1.apply(Dataset.scala:3415)
	at org.apache.spark.sql.execution.SQLExecution$$anonfun$withCustomExecutionEnv$1.apply(SQLExecution.scala:89)
	at org.apache.spark.sql.execution.SQLExecution$.withSQLConfPropagated(SQLExecution.scala:196)
	at org.apache.spark.sql.execution.SQLExecution$.withCustomExecutionEnv(SQLExecution.scala:84)
	at org.apache.spark.sql.execution.SQLExecution$.withNewExecutionId(SQLExecution.scala:126)
	at org.apache.spark.sql.Dataset.withNewRDDExecutionId(Dataset.scala:3411)
	at org.apache.spark.sql.Dataset.reduce(Dataset.scala:1643)
	at com.microsoft.ml.spark.LightGBMBase$class.train(LightGBMBase.scala:51)
	at com.microsoft.ml.spark.LightGBMClassifier.train(LightGBMClassifier.scala:23)
	at com.microsoft.ml.spark.LightGBMClassifier.train(LightGBMClassifier.scala:23)
	at org.apache.spark.ml.Predictor.fit(Predictor.scala:118)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at py4j.reflection.MethodInvoker.invoke(MethodInvoker.java:244)
	at py4j.reflection.ReflectionEngine.invoke(ReflectionEngine.java:380)
	at py4j.Gateway.invoke(Gateway.java:295)
	at py4j.commands.AbstractCommand.invokeMethod(AbstractCommand.java:132)
	at py4j.commands.CallCommand.execute(CallCommand.java:79)
	at py4j.GatewayConnection.run(GatewayConnection.java:251)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.net.ConnectException: Connection refused (Connection refused)
	at java.net.PlainSocketImpl.socketConnect(Native Method)
	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350)
	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
	at java.net.Socket.connect(Socket.java:589)
	at java.net.Socket.connect(Socket.java:538)
	at java.net.Socket.<init>(Socket.java:434)
	at java.net.Socket.<init>(Socket.java:211)
	at com.microsoft.ml.spark.TrainUtils$.getNetworkInitNodes(TrainUtils.scala:240)
	at com.microsoft.ml.spark.TrainUtils$$anonfun$7.apply(TrainUtils.scala:303)
	at com.microsoft.ml.spark.TrainUtils$$anonfun$7.apply(TrainUtils.scala:298)
	at com.microsoft.ml.spark.StreamUtilities$.using(StreamUtilities.scala:29)
	at com.microsoft.ml.spark.TrainUtils$.trainLightGBM(TrainUtils.scala:297)
	at com.microsoft.ml.spark.LightGBMBase$$anonfun$4.apply(LightGBMBase.scala:49)
	at com.microsoft.ml.spark.LightGBMBase$$anonfun$4.apply(LightGBMBase.scala:49)
	at org.apache.spark.sql.execution.MapPartitionsExec$$anonfun$6.apply(objects.scala:200)
	at org.apache.spark.sql.execution.MapPartitionsExec$$anonfun$6.apply(objects.scala:197)
	at org.apache.spark.rdd.RDD$$anonfun$mapPartitionsInternal$1$$anonfun$apply$24.apply(RDD.scala:849)
	at org.apache.spark.rdd.RDD$$anonfun$mapPartitionsInternal$1$$anonfun$apply$24.apply(RDD.scala:849)
	at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:56)
	at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:337)
	at org.apache.spark.rdd.RDD.iterator(RDD.scala:301)
	at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:56)
	at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:337)
	at org.apache.spark.rdd.RDD.iterator(RDD.scala:301)
	at org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:90)
	at org.apache.spark.scheduler.Task.run(Task.scala:124)
	at org.apache.spark.executor.Executor$TaskRunner$$anonfun$11.apply(Executor.scala:459)
	at org.apache.spark.util.Utils$.tryWithSafeFinally(Utils.scala:1401)
	at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:465)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	... 1 more
```

**Comment by imatiach-msft** [comment]
@Simon-Bru really sorry about this issue, it usually happens when lightgbm hasn't calculated the right number of workers, or one of the workers has failed and the others have this error (so this error is hiding the actual error message on another worker).  Would you be able to send the full logs for the other workers?  There may be a lot, in which case it might be easier if we debug over a meeting e.g. skype.  With the next release v0.18 we have a new barrier execution mode which should fix lightgbm calculating the number of workers incorrectly on some clusters (I'm not sure if that is the issue in your case though).  Would you be interested in trying it out?  

--packages
com.microsoft.ml.spark:mmlspark_2.11:0.17.dev27
and --repositories
https://mmlspark.azureedge.net/maven

you can set .setUseBarrierExecutionMode(true) in scala or useBarrierExecutionMode=True in python.

**Comment by Simon-Bru** [comment]
Hi @imatiach-msft 
Thank you for your help ! 
I will try to get the other workers logs but I'm on Azure Databricks so not sure if I can access those I think it was the only available stack trace. 
I am available if you can help me debugging through skype but I just tried with the 0.18 release and useBarrierExecutionMode option but it also ended in an exception, here's the stack trace: 


````
---------------------------------------------------------------------------
Py4JJavaError                             Traceback (most recent call last)
<command-780990571047582> in <module>()
----> 1 model = lgbm.fit(train)
      2 predictions = model.transform(test)

/databricks/spark/python/pyspark/ml/base.py in fit(self, dataset, params)
    130                 return self.copy(params)._fit(dataset)
    131             else:
--> 132                 return self._fit(dataset)
    133         else:
    134             raise ValueError("Params must be either a param map or a list/tuple of param maps, "

/databricks/spark/python/pyspark/ml/wrapper.py in _fit(self, dataset)
    293 
    294     def _fit(self, dataset):
--> 295         java_model = self._fit_java(dataset)
    296         model = self._create_model(java_model)
    297         return self._copyValues(model)

/databricks/spark/python/pyspark/ml/wrapper.py in _fit_java(self, dataset)
    290         """
    291         self._transfer_params_to_java()
--> 292         return self._java_obj.fit(dataset._jdf)
    293 
    294     def _fit(self, dataset):

/databricks/spark/python/lib/py4j-0.10.7-src.zip/py4j/java_gateway.py in __call__(self, *args)
   1255         answer = self.gateway_client.send_command(command)
   1256         return_value = get_return_value(
-> 1257             answer, self.gateway_client, self.target_id, self.name)
   1258 
   1259         for temp_arg in temp_args:

/databricks/spark/python/pyspark/sql/utils.py in deco(*a, **kw)
     61     def deco(*a, **kw):
     62         try:
---> 63             return f(*a, **kw)
     64         except py4j.protocol.Py4JJavaError as e:
     65             s = e.java_exception.toString()

/databricks/spark/python/lib/py4j-0.10.7-src.zip/py4j/protocol.py in get_return_value(answer, gateway_client, target_id, name)
    326                 raise Py4JJavaError(
    327                     "An error occurred while calling {0}{1}{2}.\n".
--> 328                     format(target_id, ".", name), value)
    329             else:
    330                 raise Py4JError(

Py4JJavaError: An error occurred while calling o654.fit.
: org.apache.spark.scheduler.BarrierJobUnsupportedRDDChainException: [SPARK-24820][SPARK-24821]: Barrier execution mode does not allow the following pattern of RDD chain within a barrier stage:
1. Ancestor RDDs that have different number of partitions from the resulting RDD (eg. union()/coalesce()/first()/take()/PartitionPruningRDD). A workaround for first()/take() can be barrierRdd.collect().head (scala) or barrierRdd.collect()[0] (python).
2. An RDD that depends on multiple barrier RDDs (eg. barrierRdd1.zip(barrierRdd2)).
	at org.apache.spark.scheduler.DAGScheduler.checkBarrierStageWithRDDChainPattern(DAGScheduler.scala:471)
	at org.apache.spark.scheduler.DAGScheduler.createResultStage(DAGScheduler.scala:546)
	at org.apache.spark.scheduler.DAGScheduler.handleJobSubmitted(DAGScheduler.scala:1093)
	at org.apache.spark.scheduler.DAGSchedulerEventProcessLoop.doOnReceive(DAGScheduler.scala:2205)
	at org.apache.spark.scheduler.DAGSchedulerEventProcessLoop.onReceive(DAGScheduler.scala:2196)
	at org.apache.spark.scheduler.DAGSchedulerEventProcessLoop.onReceive(DAGScheduler.scala:2184)
	at org.apache.spark.util.EventLoop$$anon$1.run(EventLoop.scala:49)
	at org.apache.spark.scheduler.DAGScheduler.runJob(DAGScheduler.scala:854)
	at org.apache.spark.SparkContext.runJob(SparkContext.scala:2186)
	at org.apache.spark.SparkContext.runJob(SparkContext.scala:2283)
	at org.apache.spark.rdd.RDD$$anonfun$reduce$1.apply(RDD.scala:1048)
	at org.apache.spark.rdd.RDDOperationScope$.withScope(RDDOperationScope.scala:151)
	at org.apache.spark.rdd.RDDOperationScope$.withScope(RDDOperationScope.scala:112)
	at org.apache.spark.rdd.RDD.withScope(RDD.scala:376)
	at org.apache.spark.rdd.RDD.reduce(RDD.scala:1030)
	at com.microsoft.ml.spark.LightGBMBase$class.innerTrain(LightGBMBase.scala:87)
	at com.microsoft.ml.spark.LightGBMClassifier.innerTrain(LightGBMClassifier.scala:24)
	at com.microsoft.ml.spark.LightGBMBase$class.train(LightGBMBase.scala:37)
	at com.microsoft.ml.spark.LightGBMClassifier.train(LightGBMClassifier.scala:24)
	at com.microsoft.ml.spark.LightGBMClassifier.train(LightGBMClassifier.scala:24)
	at org.apache.spark.ml.Predictor.fit(Predictor.scala:118)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at py4j.reflection.MethodInvoker.invoke(MethodInvoker.java:244)
	at py4j.reflection.ReflectionEngine.invoke(ReflectionEngine.java:380)
	at py4j.Gateway.invoke(Gateway.java:295)
	at py4j.commands.AbstractCommand.invokeMethod(AbstractCommand.java:132)
	at py4j.commands.CallCommand.execute(CallCommand.java:79)
	at py4j.GatewayConnection.run(GatewayConnection.java:251)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by imatiach-msft** [comment]
There should be logs for each of the workers, but it may be overwhelming if you have a lot of workers on the cluster.  For each worker and driver there are two logs:
standard error (stderr)
standard output (stdout)
In addition, there are also log4j logs for the cluster.
I think it might be easier to just debug over skype or teams.

Here is a teams meeting I created:

https://teams.microsoft.com/l/meetup-join/19%3ameeting_NmE4YjU5NjUtZDFjNy00NGI5LWIyOWEtZmQxMDRhMDU1YjM4%40thread.v2/0?context=%7b%22Tid%22%3a%2272f988bf-86f1-41af-91ab-2d7cd011db47%22%2c%22Oid%22%3a%227ac33778-88d2-407b-bfe1-d64366fff0e4%22%7d

________________________________________________________________________________ 
Join Microsoft Teams Meeting 
+1 347-991-7781   United States, New York City (Toll) 
(866) 641-7188   (Toll-free) 
Conference ID: 983 864 00# 
Local numbers | Reset PIN | Learn more about Teams | Meeting options 
________________________________________________________________________________

**Comment by imatiach-msft** [comment]
@Simon-Bru interesting I definitely haven't seen this error before, what is the spark version you are running locally:
: org.apache.spark.scheduler.BarrierJobUnsupportedRDDChainException: [SPARK-24820][SPARK-24821]: Barrier execution mode does not allow the following pattern of RDD chain within a barrier stage:
1. Ancestor RDDs that have different number of partitions from the resulting RDD (eg. union()/coalesce()/first()/take()/PartitionPruningRDD). A workaround for first()/take() can be barrierRdd.collect().head (scala) or barrierRdd.collect()[0] (python).
2. An RDD that depends on multiple barrier RDDs (eg. barrierRdd1.zip(barrierRdd2)).
I will try to repro the error.  Have you also tried running without barrier execution mode with the latest code on master?

**Comment by imatiach-msft** [comment]
@Simon-Bru closing this issue as you were passing ranking objective to lightgbm classifier, and using lightgbm ranker seems to have fixed this issue.  Please reopen if you are still seeing this error or please open a new ticket for any new errors.  Thank you!
