### ISSUE TITLE
 java.lang.NoClassDefFoundError:Lcom/microsoft/ml/lightgbm/SWIGTYPE_p_void

### ISSUE THREAD

**Issue by charmby** [Azure/mmlspark#611]
When I'm  running lightgbm by the spark.I get such exceptions.
```
Exception in thread "main" java.lang.NoClassDefFoundError: Lcom/microsoft/ml/lightgbm/SWIGTYPE_p_void;

	at java.lang.Class.getDeclaredFields0(Native Method)
	at java.lang.Class.privateGetDeclaredFields(Class.java:2583)
	at java.lang.Class.getDeclaredField(Class.java:2068)
	at java.io.ObjectStreamClass.getDeclaredSUID(ObjectStreamClass.java:1703)
	at java.io.ObjectStreamClass.access$700(ObjectStreamClass.java:72)

	at java.io.ObjectStreamClass$2.run(ObjectStreamClass.java:484)
	at java.io.ObjectStreamClass$2.run(ObjectStreamClass.java:472)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.io.ObjectStreamClass.<init>(ObjectStreamClass.java:472)
	at java.io.ObjectStreamClass.lookup(ObjectStreamClass.java:369)
	at java.io.ObjectOutputStream.writeClass(ObjectOutputStream.java:1213)
	at java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1120)
	at java.io.ObjectOutputStream.defaultWriteFields(ObjectOutputStream.java:1548)
	at java.io.ObjectOutputStream.writeSerialData(ObjectOutputStream.java:1509)
	at java.io.ObjectOutputStream.writeOrdinaryObject(ObjectOutputStream.java:1432)
	at java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1178)
	at java.io.ObjectOutputStream.defaultWriteFields(ObjectOutputStream.java:1548)
	at java.io.ObjectOutputStream.writeSerialData(ObjectOutputStream.java:1509)
	at java.io.ObjectOutputStream.writeOrdinaryObject(ObjectOutputStream.java:1432)
	at java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1178)
	at java.io.ObjectOutputStream.writeObject(ObjectOutputStream.java:348)
	at org.apache.spark.serializer.JavaSerializationStream.writeObject(JavaSerializer.scala:43)
	at org.apache.spark.serializer.JavaSerializerInstance.serialize(JavaSerializer.scala:100)
	at org.apache.spark.util.ClosureCleaner$.ensureSerializable(ClosureCleaner.scala:342)
	at org.apache.spark.util.ClosureCleaner$.org$apache$spark$util$ClosureCleaner$$clean(ClosureCleaner.scala:335)
	at org.apache.spark.util.ClosureCleaner$.clean(ClosureCleaner.scala:159)
```
My pom reference as shown below
```
  <dependency>
            <groupId>Azure</groupId>
            <artifactId>mmlspark</artifactId>
            <version>0.16</version>
        </dependency>
```
Who can help me to solve this problem?Thank you very much ！

**Comment by imatiach-msft** [comment]
@charmby sorry about the issue you are encountering.  Usually this happens when the native lightgbm dependency is not loaded from maven, please see this maven artifact:

https://mvnrepository.com/artifact/com.microsoft.ml.lightgbm/lightgbmlib

also, please use the latest 0.17 version from mmlspark

**Comment by imatiach-msft** [comment]
@charmby did you have any luck with this issue?  were you able to find a workaround?

**Comment by prarshah** [comment]
Using version 2.3.150 of LightGBM gives this error, because the file SWIGTYPE_p_void is missing also some other versions give errors like SWIGTYPE_p_int_64_t not found, and the rest give error "libomp" not loaded.. I have tried all combinations and still no luck

**Comment by 13pranav5** [comment]
I get the same error with the latest release. has anyone figured out a fix for this?

<dependency>
            <groupId>com.microsoft.ml.spark</groupId>
            <artifactId>mmlspark_2.11</artifactId>
            <version>1.0.0-rc1</version>
</dependency>

**Comment by prarshah** [comment]
I don't know if this is the correct way for you but according to the H2O.ai documentation, 
H2O provides a method for emulating the LightGBM software using a certain set of options within XGBoost. This is done by setting the following options:
```
tree_method="hist"
grow_policy="lossguide"
```
[Doccumenation link](http://docs.h2o.ai/h2o/latest-stable/h2o-docs/data-science/xgboost.html?highlight=lightgbm)
Hope this helps.

**Comment by caozhanxu** [comment]
> Using the latest version of LightGBM gives this error because the file SWIGTYPE_p_void is missing which is present in other versions, but some other versions like 2.3.350 give errors like SWIGTYPE_p_int_64_t not found, and the rest give error "libomp" not loaded ... I have tried all combinations and still no luck

 I get the same error with the follow pom

 <dependency>
            <groupId>com.microsoft.ml.spark</groupId>
            <artifactId>mmlspark_2.11</artifactId>
            <version>0.18.1</version>
        </dependency>

        <dependency>
            <groupId>com.microsoft.ml.lightgbm</groupId>
            <artifactId>lightgbmlib</artifactId>
            <version>2.2.400</version>
        </dependency>


please help

**Comment by ranadeepsingh** [comment]
This issue is a duplicate of canonical issue #295 regarding NoClassDefFoundError for LightGBM SWIG native library classes. All discussion and tracking for this issue will be consolidated under #295, so this duplicate is now closed.
