### ISSUE TITLE
EMR Livy cannot start session with newest version of mmlspark lib

### ISSUE THREAD

**Issue by rogor777** [Azure/mmlspark#674]
**Describe the bug**
When using AWS EMR JupyterHub pyspark notebook to use newest mmlspark, session timeouts.
EMR jupyterhub is using Apache Livy to perform operations  against spark.

Everything works perfectly fine with mmlspark version 0.17. 

**To Reproduce**
1st cell in notebook:
%%configure
{ "conf": {
    "spark.jars.packages": "com.microsoft.ml.spark:mmlspark_2.11:0.18.1"
}}

2nd cell, anything to just start the spark session:
import os

**Expected behavior**
Session is established. 

**Info (please complete the following information):**
 - MMLSpark Version: [0.18.1, 0.18.0]
 - Spark Version [2.4.3]
 - Spark Platform [AWS EMR 5.26, 5.25]
 - Livy [0.6.0]

** Stacktrace**
Stack trace in livy server logs, just after message "Created Spark session (with Hive support).";
```
 19/08/27 18:09:48 INFO LineBufferedStream: Exception in thread "main" java.lang.NullPointerException
19/08/27 18:09:48 INFO LineBufferedStream:      at org.apache.livy.rsc.driver.JobWrapper.cancel(JobWrapper.java:90)
19/08/27 18:09:48 INFO LineBufferedStream:      at org.apache.livy.rsc.driver.RSCDriver.shutdown(RSCDriver.java:127)
19/08/27 18:09:48 INFO LineBufferedStream:      at org.apache.livy.rsc.driver.RSCDriver.run(RSCDriver.java:356)
19/08/27 18:09:48 INFO LineBufferedStream:      at org.apache.livy.rsc.driver.RSCDriverBootstrapper.main(RSCDriverBootstrapper.java:93)
19/08/27 18:09:48 INFO LineBufferedStream:      at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
19/08/27 18:09:48 INFO LineBufferedStream:      at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
19/08/27 18:09:48 INFO LineBufferedStream:      at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
19/08/27 18:09:48 INFO LineBufferedStream:      at java.lang.reflect.Method.invoke(Method.java:498)
19/08/27 18:09:48 INFO LineBufferedStream:      at org.apache.spark.deploy.JavaMainApplication.start(SparkApplication.scala:52)
19/08/27 18:09:48 INFO LineBufferedStream:      at org.apache.spark.deploy.SparkSubmit.org$apache$spark$deploy$SparkSubmit$$runMain(SparkSubmit.scala:849)
19/08/27 18:09:48 INFO LineBufferedStream:      at org.apache.spark.deploy.SparkSubmit.doRunMain$1(SparkSubmit.scala:167)
19/08/27 18:09:48 INFO LineBufferedStream:      at org.apache.spark.deploy.SparkSubmit.submit(SparkSubmit.scala:195)
19/08/27 18:09:48 INFO LineBufferedStream:      at org.apache.spark.deploy.SparkSubmit.doSubmit(SparkSubmit.scala:86)
19/08/27 18:09:48 INFO LineBufferedStream:      at org.apache.spark.deploy.SparkSubmit$$anon$2.doSubmit(SparkSubmit.scala:924)
19/08/27 18:09:48 INFO LineBufferedStream:      at org.apache.spark.deploy.SparkSubmit$.main(SparkSubmit.scala:933)
19/08/27 18:09:48 INFO LineBufferedStream:      at org.apache.spark.deploy.SparkSubmit.main(SparkSubmit.scala)
```
Execution logs:
```
19/08/27 22:27:37 INFO Client: Requesting a new application from cluster with 2 NodeManagers
19/08/27 22:27:37 INFO Client: Verifying our application has not requested more than the maximum memory capability of the cluster (12288 MB per container)
19/08/27 22:27:37 INFO Client: Will allocate AM container, with 896 MB memory including 384 MB overhead
19/08/27 22:27:37 INFO Client: Setting up container launch context for our AM
19/08/27 22:27:37 INFO Client: Setting up the launch environment for our AM container
19/08/27 22:27:37 INFO Client: Preparing resources for our AM container
19/08/27 22:27:37 INFO Client: Uploading resource file:/usr/lib/livy/rsc-jars/livy-api-0.6.0-incubating.jar -> hdfs://<<host name>>:8020/user/livy/.sparkStaging/application_1566941596797_0003/livy-api-0.6.0-incubating.jar
19/08/27 22:27:37 INFO Client: Uploading resource file:/usr/lib/livy/rsc-jars/netty-all-4.1.17.Final.jar -> hdfs://<<host name>>:8020/user/livy/.sparkStaging/application_1566941596797_0003/netty-all-4.1.17.Final.jar
19/08/27 22:27:37 INFO Client: Uploading resource file:/usr/lib/livy/rsc-jars/livy-rsc-0.6.0-incubating.jar -> hdfs://<<host name>>:8020/user/livy/.sparkStaging/application_1566941596797_0003/livy-rsc-0.6.0-incubating.jar
19/08/27 22:27:37 INFO Client: Uploading resource file:/usr/lib/livy/repl_2.11-jars/commons-codec-1.9.jar -> hdfs://<<host name>>:8020/user/livy/.sparkStaging/application_1566941596797_0003/commons-codec-1.9.jar
19/08/27 22:27:37 INFO Client: Uploading resource file:/usr/lib/livy/repl_2.11-jars/livy-core_2.11-0.6.0-incubating.jar -> hdfs://<<host name>>:8020/user/livy/.sparkStaging/application_1566941596797_0003/livy-core_2.11-0.6.0-incubating.jar
19/08/27 22:27:37 INFO Client: Uploading resource file:/usr/lib/livy/repl_2.11-jars/livy-repl_2.11-0.6.0-incubating.jar -> hdfs://<<host name>>:8020/user/livy/.sparkStaging/application_1566941596797_0003/livy-repl_2.11-0.6.0-incubating.jar
19/08/27 22:27:37 INFO Client: Uploading resource file:/var/lib/livy/.ivy2/jars/Azure_mmlspark-0.17.jar -> hdfs://<<host name>>:8020/user/livy/.sparkStaging/application_1566941596797_0003/Azure_mmlspark-0.17.jar
19/08/27 22:27:37 INFO Client: Uploading resource file:/var/lib/livy/.ivy2/jars/io.spray_spray-json_2.11-1.3.2.jar -> hdfs://<<host name>>:8020/user/livy/.sparkStaging/application_1566941596797_0003/io.spray_spray-json_2.11-1.3.2.jar
19/08/27 22:27:37 INFO Client: Uploading resource file:/var/lib/livy/.ivy2/jars/com.microsoft.cntk_cntk-2.4.jar -> hdfs://<<host name>>:8020/user/livy/.sparkStaging/application_1566941596797_0003/com.microsoft.cntk_cntk-2.4.jar
19/08/27 22:27:38 INFO Client: Uploading resource file:/var/lib/livy/.ivy2/jars/org.openpnp_opencv-3.2.0-1.jar -> hdfs://<<host name>>:8020/user/livy/.sparkStaging/application_1566941596797_0003/org.openpnp_opencv-3.2.0-1.jar
19/08/27 22:27:38 INFO Client: Uploading resource file:/var/lib/livy/.ivy2/jars/com.jcraft_jsch-0.1.54.jar -> hdfs://<<host name>>:8020/user/livy/.sparkStaging/application_1566941596797_0003/com.jcraft_jsch-0.1.54.jar
19/08/27 22:27:38 INFO Client: Uploading resource file:/var/lib/livy/.ivy2/jars/org.apache.httpcomponents_httpclient-4.5.6.jar -> hdfs://<<host name>>:8020/user/livy/.sparkStaging/application_1566941596797_0003/org.apache.httpcomponents_httpclient-4.5.6.jar
19/08/27 22:27:39 INFO Client: Uploading resource file:/var/lib/livy/.ivy2/jars/com.microsoft.ml.lightgbm_lightgbmlib-2.2.300.jar -> hdfs://<<host name>>:8020/user/livy/.sparkStaging/application_1566941596797_0003/com.microsoft.ml.lightgbm_lightgbmlib-2.2.300.jar
19/08/27 22:27:39 INFO Client: Uploading resource file:/var/lib/livy/.ivy2/jars/org.apache.httpcomponents_httpcore-4.4.10.jar -> hdfs://<<host name>>:8020/user/livy/.sparkStaging/application_1566941596797_0003/org.apache.httpcomponents_httpcore-4.4.10.jar
19/08/27 22:27:39 INFO Client: Uploading resource file:/var/lib/livy/.ivy2/jars/commons-logging_commons-logging-1.2.jar -> hdfs://<<host name>>:8020/user/livy/.sparkStaging/application_1566941596797_0003/commons-logging_commons-logging-1.2.jar
19/08/27 22:27:39 INFO Client: Uploading resource file:/var/lib/livy/.ivy2/jars/commons-codec_commons-codec-1.10.jar -> hdfs://<<host name>>:8020/user/livy/.sparkStaging/application_1566941596797_0003/commons-codec_commons-codec-1.10.jar
19/08/27 22:27:39 INFO Client: Uploading resource file:/etc/spark/conf/hive-site.xml -> hdfs://<<host name>>:8020/user/livy/.sparkStaging/application_1566941596797_0003/hive-site.xml
19/08/27 22:27:39 INFO Client: Uploading resource file:/usr/lib/spark/R/lib/sparkr.zip#sparkr -> hdfs://<<host name>>:8020/user/livy/.sparkStaging/application_1566941596797_0003/sparkr.zip
19/08/27 22:27:40 INFO Client: Uploading resource file:/usr/lib/spark/python/lib/pyspark.zip -> hdfs://<<host name>>:8020/user/livy/.sparkStaging/application_1566941596797_0003/pyspark.zip
19/08/27 22:27:40 INFO Client: Uploading resource file:/usr/lib/spark/python/lib/py4j-0.10.7-src.zip -> hdfs://<<host name>>:8020/user/livy/.sparkStaging/application_1566941596797_0003/py4j-0.10.7-src.zip
19/08/27 22:27:41 WARN Client: Same name resource file:///usr/lib/spark/python/lib/pyspark.zip added multiple times to distributed cache
19/08/27 22:27:41 WARN Client: Same name resource file:///usr/lib/spark/python/lib/py4j-0.10.7-src.zip added multiple times to distributed cache
19/08/27 22:27:41 WARN Client: Same path resource file:///var/lib/livy/.ivy2/jars/Azure_mmlspark-0.17.jar added multiple times to distributed cache.
19/08/27 22:27:41 WARN Client: Same path resource file:///var/lib/livy/.ivy2/jars/io.spray_spray-json_2.11-1.3.2.jar added multiple times to distributed cache.
19/08/27 22:27:41 WARN Client: Same path resource file:///var/lib/livy/.ivy2/jars/com.microsoft.cntk_cntk-2.4.jar added multiple times to distributed cache.
19/08/27 22:27:41 WARN Client: Same path resource file:///var/lib/livy/.ivy2/jars/org.openpnp_opencv-3.2.0-1.jar added multiple times to distributed cache.
19/08/27 22:27:41 WARN Client: Same path resource file:///var/lib/livy/.ivy2/jars/com.jcraft_jsch-0.1.54.jar added multiple times to distributed cache.
19/08/27 22:27:41 WARN Client: Same path resource file:///var/lib/livy/.ivy2/jars/org.apache.httpcomponents_httpclient-4.5.6.jar added multiple times to distributed cache.
19/08/27 22:27:41 WARN Client: Same path resource file:///var/lib/livy/.ivy2/jars/com.microsoft.ml.lightgbm_lightgbmlib-2.2.300.jar added multiple times to distributed cache.
19/08/27 22:27:41 WARN Client: Same path resource file:///var/lib/livy/.ivy2/jars/org.apache.httpcomponents_httpcore-4.4.10.jar added multiple times to distributed cache.
19/08/27 22:27:41 WARN Client: Same path resource file:///var/lib/livy/.ivy2/jars/commons-logging_commons-logging-1.2.jar added multiple times to distributed cache.
19/08/27 22:27:41 WARN Client: Same path resource file:///var/lib/livy/.ivy2/jars/commons-codec_commons-codec-1.10.jar added multiple times to distributed cache.
19/08/27 22:27:41 INFO Client: Uploading resource file:/mnt/tmp/spark-df5cd850-d17a-4461-8c66-f80c28ea4ece/__spark_conf__7178753338038677377.zip -> hdfs://<<host name>>:8020/user/livy/.sparkStaging/application_1566941596797_0003/__spark_conf__.zip
19/08/27 22:27:41 INFO Client: Submitting application application_1566941596797_0003 to ResourceManager
19/08/27 22:27:41 INFO YarnClientImpl: Submitted application application_1566941596797_0003
19/08/27 22:27:41 INFO SchedulerExtensionServices: Starting Yarn extension services with app application_1566941596797_0003 and attemptId None
19/08/27 22:27:43 INFO Client: Application report for application_1566941596797_0003 (state: ACCEPTED)
19/08/27 22:27:43 INFO Client: 
	 client token: N/A
	 diagnostics: AM container is launched, waiting for AM container to Register with RM
	 ApplicationMaster host: N/A
	 ApplicationMaster RPC port: -1
	 queue: default
	 start time: 1566944861950
	 final status: UNDEFINED
	 tracking URL: http://<<host name>>:20888/proxy/application_1566941596797_0003/
	 user: livy
19/08/27 22:27:44 INFO Client: Application report for application_1566941596797_0003 (state: FAILED)
19/08/27 22:27:44 INFO Client: 
	 client token: N/A
	 diagnostics: Application application_1566941596797_0003 failed 1 times (global limit =2; local limit is =1) due to AM Container for appattempt_1566941596797_0003_000001 exited with  exitCode: 1
Failing this attempt.Diagnostics: Exception from container-launch..

Some things to try:
a) Make sure Spark has enough available resources for Jupyter to create a Spark context.
b) Contact your Jupyter administrator to make sure the Spark a...
```

**Comment by rogor777** [comment]
Issue was caused by dependency on scala-reflect and scala-xml packages, which caused livy to crash. 
In case someone interested I'm adding spark configuration to make it work properly 

%%configure
{ "conf": {
    "spark.jars.packages": "com.microsoft.ml.spark:mmlspark_2.11:0.18.1",
    "spark.jars.excludes": "org.scala-lang:scala-reflect,org.scala-lang.modules:scala-xml_2.11"
}}
