### ISSUE TITLE
LightGBMRegressor throws exception at getNetworkInitNodes()

### ISSUE THREAD

**Issue by abattaje** [Azure/mmlspark#683]
I am having trouble training a LightGBMRegressor because of the way my network is setup. I am running spark in client mode. The cluster is in a different network as that of the driver. Due to the firewall setup that blocks any socket connections from executors to the driver, we use `spark.blockmanager.port` in spark config as a workaround to this. This port too should be within a range that firewall allows.

This works fine for most of the spark ML libraries. However, in mmlspark, I see driver listening on a random port and that port is used by executors to communicate with driver. Is there a way to override random port selection with the blockmanager port or some port within a given range that is allowed by firewall?

Driver log:

```
> 19/09/06 18:39:13 INFO lightgbm.LightGBMRegressor: driver expecting 50 connections...
> 19/09/06 18:39:13 INFO lightgbm.LightGBMRegressor: driver accepting a new connection...
> 19/09/06 18:39:13 INFO lightgbm.LightGBMRegressor: driver waiting for connections on host: <driver_ip_addr> and port: 40276
```

Executor log:

```
19/09/06 18:40:11 INFO storage.ShuffleBlockFetcherIterator: Getting 1 non-empty blocks out of 49 blocks
19/09/06 18:40:11 INFO storage.ShuffleBlockFetcherIterator: Started 0 remote fetches in 1 ms
19/09/06 18:40:11 INFO lightgbm.LightGBMRegressor: Successfully bound to port 15784
19/09/06 18:40:11 INFO lightgbm.LightGBMRegressor: LightGBM worker connecting to host: <driver_ip_addr> and port: 40276
19/09/06 18:40:11 ERROR executor.Executor: Exception in task 2.3 in stage 2.0 (TID 108)
java.net.ConnectException: Connection refused (Connection refused)
	at java.net.PlainSocketImpl.socketConnect(Native Method)
	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350)
	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
	at java.net.Socket.connect(Socket.java:589)
	at java.net.Socket.connect(Socket.java:538)
	at java.net.Socket.<init>(Socket.java:434)
	at java.net.Socket.<init>(Socket.java:211)
	at com.microsoft.ml.spark.lightgbm.TrainUtils$.getNetworkInitNodes(TrainUtils.scala:324)
	at com.microsoft.ml.spark.lightgbm.TrainUtils$$anonfun$15.apply(TrainUtils.scala:398)
	at com.microsoft.ml.spark.lightgbm.TrainUtils$$anonfun$15.apply(TrainUtils.scala:393)
	at com.microsoft.ml.spark.core.env.StreamUtilities$.using(StreamUtilities.scala:28)
	at com.microsoft.ml.spark.lightgbm.TrainUtils$.trainLightGBM(TrainUtils.scala:392)
	at com.microsoft.ml.spark.lightgbm.LightGBMBase$$anonfun$6.apply(LightGBMBase.scala:85)
	at com.microsoft.ml.spark.lightgbm.LightGBMBase$$anonfun$6.apply(LightGBMBase.scala:85)
	at org.apache.spark.sql.execution.MapPartitionsExec$$anonfun$5.apply(objects.scala:188)
	at org.apache.spark.sql.execution.MapPartitionsExec$$anonfun$5.apply(objects.scala:185)
	at org.apache.spark.rdd.RDD$$anonfun$mapPartitionsInternal$1$$anonfun$apply$25.apply(RDD.scala:836)
	at org.apache.spark.rdd.RDD$$anonfun$mapPartitionsInternal$1$$anonfun$apply$25.apply(RDD.scala:836)
	at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:49)
	at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:324)
	at org.apache.spark.rdd.RDD.iterator(RDD.scala:288)
	at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:49)
	at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:324)
	at org.apache.spark.rdd.RDD.iterator(RDD.scala:288)
	at org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:87)
	at org.apache.spark.scheduler.Task.run(Task.scala:109)
	at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:381)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by imatiach-msft** [comment]
@abattaje sorry about the trouble you are having.  Luckily, I have a parameter just for this:
https://github.com/Azure/mmlspark/blob/master/src/main/scala/com/microsoft/ml/spark/lightgbm/LightGBMParams.scala#L24
you can set the lower-bound value, and then all executors get values above that, unless some ports are taken or fail, in which case some port #s may be skipped, but the lower-bound is guaranteed.
The default is set to 12400:
https://github.com/Azure/mmlspark/blob/master/src/main/scala/com/microsoft/ml/spark/lightgbm/LightGBMConstants.scala#L9
I really hope this parameter works for you!

**Comment by imatiach-msft** [comment]
please feel free to reopen if you are still having issues
