### ISSUE TITLE
ClusterUtil.getNumCoresPerExecutor returns the wrong number

### ISSUE THREAD

**Issue by catenamatteo** [Azure/mmlspark#707]
I'm trying to train a LightGBMRanker with 10 executors and 1 cores each (I compiled the code from the master branch. I receive this error:
```
java.lang.IllegalArgumentException: requirement failed: Number of partitions (0) must be positive.
  at scala.Predef$.require(Predef.scala:224)
  at org.apache.spark.sql.catalyst.plans.logical.Repartition.<init>(basicLogicalOperators.scala:831)
  at org.apache.spark.sql.Dataset.coalesce(Dataset.scala:2880)
  at com.microsoft.ml.spark.lightgbm.LightGBMBase$class.prepareDataframe(LightGBMBase.scala:97)
  at com.microsoft.ml.spark.lightgbm.LightGBMRanker.prepareDataframe(LightGBMRanker.scala:25)
  at com.microsoft.ml.spark.lightgbm.LightGBMBase$class.innerTrain(LightGBMBase.scala:119)
  at com.microsoft.ml.spark.lightgbm.LightGBMRanker.innerTrain(LightGBMRanker.scala:25)
  at com.microsoft.ml.spark.lightgbm.LightGBMBase$class.train(LightGBMBase.scala:40)
  at com.microsoft.ml.spark.lightgbm.LightGBMRanker.train(LightGBMRanker.scala:25)
  at com.microsoft.ml.spark.lightgbm.LightGBMRanker.train(LightGBMRanker.scala:25)
  at org.apache.spark.ml.Predictor.fit(Predictor.scala:118)
  at trainRankerModel(<console>:40)
  ... 49 elided
```

I think the problem is due to the fact that ClusterUtil.getNumCoresPerExecutor returns 0 (it thinks that there are no cores on the executors).

**Comment by imatiach-msft** [comment]
@catenamatteo you're right, for some reason it is returning the wrong number of partitions... would you be able to share some of the log output?

**Comment by imatiach-msft** [comment]
@catenamatteo that is very strange, I'm guessing this method is returning zero for you:

```
  def getJVMCPUs(spark: SparkSession): Int = {
    import spark.implicits._
    spark.range(0, 1)
      .map(_ => java.lang.Runtime.getRuntime.availableProcessors).collect.head
  }
```
could you try running that code locally?

**Comment by catenamatteo** [comment]
Nope, it returns 40.

**Comment by imatiach-msft** [comment]
@catenamatteo 
interesting, I'm guessing you had this property set:
```
spark.executor.cores
```
see code:
https://github.com/Azure/mmlspark/blob/master/src/main/scala/com/microsoft/ml/spark/core/utils/ClusterUtil.scala#L36
probably it is set to a value less than 40, and then when using integer division "confCores / confTaskCpus" we get zero.  The new code seems to fix this as task CPUs is 1 by default, which seems to line up with spark.  That was a recent change that I made which I rolled back after @eisber noticed issues with distributed VowpalWabbit which is using the same utils.

**Comment by catenamatteo** [comment]
Yes, I confirm we use the spark.executor.cores property

**Comment by ranadeepsingh** [comment]
We are closing this issue as the integer division error in `ClusterUtil` that returned 0 executor cores when `spark.executor.cores` was set was fixed in master and included in published releases starting with mmlspark 0.19 and carried forward into SynapseML v1.1.3. If you encounter any core calculation issues on current releases, please open a new issue.
