### ISSUE TITLE
HttpOnSpark databricks example is not working (service responsed with 405/GET Method not allowed)

### ISSUE THREAD

**Issue by kduvekot-wehkamp-nl** [Azure/mmlspark#727]
**Describe the bug**
When I download and run the databricks notebook for HttpOnSpark the service that the request is towards respond with "Method Not Allowed (Allow: GET, HEAD)/ 405"

**To Reproduce**
Import and run the databricks notebook: HttpOnSpark - Working with Arbitrary Web APIs.ipynb

**Expected behavior**
A dataframe with the reponse as descibed in the notebook

**Info (please complete the following information):**
 - MMLSpark Version: 0.18.1 (1.0.0-rc1 is not available yet via maven central)
 - Spark Version: 2.4.3
 - Spark Platform: Databricks

** Stacktrace**
```
No stack trace ... 
```

**Comment by kduvekot-wehkamp-nl** [comment]
Looks like the HttpOnSpark does not support the GET method:
https://mmlspark.blob.core.windows.net/docs/0.18.1/pyspark/mmlspark.io.http.html#mmlspark.io.http.JSONInputParser.JSONInputParser

method (str) – method to use for request, (PUT, POST, PATCH) (default: POST)

**Comment by alapinsk** [comment]
I have similar issue.
I tried to running example [HttpOnSpark - Working with Arbitrary Web APIs.ipynb](https://github.com/Azure/mmlspark/blob/master/notebooks/samples/HttpOnSpark%20-%20Working%20with%20Arbitrary%20Web%20APIs.ipynb)
using library version ***mmlspark:0.17***
environment ***Databricks Runtime Version 5.5 LTS ML (Apache Spark 2.4.3, Scala 2.11)***
using scala API

```scala
import com.microsoft.ml.spark.{SimpleHTTPTransformer,JSONOutputParser,JSONInputParser}
import org.apache.spark.sql.types._
import org.apache.spark.sql.functions.struct

val df = sc.parallelize(0 to 100).toDF("data")
            .withColumn("inputs", struct("data"))
val response_schema = StructType(List(StructField("status",StringType,true),StructField("message",StringType,true)))

val client = new SimpleHTTPTransformer()
  .setInputCol("inputs")
  .setInputParser(new JSONInputParser().setMethod("GET").setUrl("https://dog.ceo/api/breeds/image/random"))
  .setOutputParser(new JSONOutputParser().setDataType(response_schema))
  .setOutputCol("results")

val responses = client.transform(df)
display(responses.select("results"))
```

Here is stack trace
```
java.lang.IllegalArgumentException: Entity is defined but method is GET
	at com.microsoft.ml.spark.HTTPRequestData.toHTTPCore(HTTPSchema.scala:189)
	at com.microsoft.ml.spark.HandlingUtils$.advanced(HTTPClients.scala:109)
	at com.microsoft.ml.spark.HandlingUtils$$anonfun$advancedUDF$1.apply(HTTPClients.scala:124)
	at com.microsoft.ml.spark.HandlingUtils$$anonfun$advancedUDF$1.apply(HTTPClients.scala:124)
	at com.microsoft.ml.spark.SingleThreadedHTTPClient.handle(HTTPClients.scala:149)
	at com.microsoft.ml.spark.HTTPClient$class.sendRequestWithContext(HTTPClients.scala:48)
	at com.microsoft.ml.spark.SingleThreadedHTTPClient.sendRequestWithContext(HTTPClients.scala:146)
	at com.microsoft.ml.spark.SingleThreadedClient$$anonfun$sendRequestsWithContext$1.apply(Clients.scala:97)
	at com.microsoft.ml.spark.SingleThreadedClient$$anonfun$sendRequestsWithContext$1.apply(Clients.scala:97)
	at scala.collection.Iterator$$anon$11.next(Iterator.scala:410)
	at scala.collection.Iterator$$anon$11.next(Iterator.scala:410)
	at scala.collection.Iterator$$anon$11.next(Iterator.scala:410)
	at org.apache.spark.sql.catalyst.expressions.GeneratedClass$GeneratedIteratorForCodegenStage2.processNext(Unknown Source)
	at org.apache.spark.sql.execution.BufferedRowIterator.hasNext(BufferedRowIterator.java:43)
	at 
....
```

**Comment by mhamilton723** [comment]
Hey @kduvekot-wehkamp-nl on master I just added an integration with python Requests. This helps with creating HTTP request objects for Spark to orchestrate. Hope this helps!

**Comment by kduvekot-wehkamp-nl** [comment]
@mhamilton723 any documentation on how to use that?

**Comment by ericholiveira** [comment]
Just learned how to do http get (fixing @alapinsk code)

`scala

import com.microsoft.ml.spark.io.http._
import org.apache.spark.sql.types._
import org.apache.spark.sql.functions.struct

val df = sc.parallelize(0 to 100).toDF("inputs")

val response_schema = StructType(List(StructField("status",StringType,true),StructField("message",StringType,true)))

val inputParser = new CustomInputParser().setUDF({ x: Int => new HttpGet(s"https://dog.ceo/api/breeds/image/random?$x") })

val client = new SimpleHTTPTransformer()
  .setInputCol("inputs")
  .setInputParser(inputParser)
  .setOutputParser(new JSONOutputParser().setDataType(response_schema))
  .setOutputCol("results")

val responses = client.transform(df)
display(responses.select("results"))
`

**Comment by marktab** [comment]
@ericholiveira  thanks for your solution, but I needed to add an additional import line to make it work:

%scala
import com.microsoft.ml.spark.io.http._
import org.apache.spark.sql.types._
import org.apache.spark.sql.functions.struct
**import org.apache.http.client.methods.HttpGet**

val df = sc.parallelize(0 to 100).toDF("inputs")

val response_schema = StructType(List(StructField("status",StringType,true),StructField("message",StringType,true)))

val inputParser = new CustomInputParser().setUDF({ x: Int => new HttpGet(s"https://dog.ceo/api/breeds/image/random?$x") })

val client = new SimpleHTTPTransformer()
.setInputCol("inputs")
.setInputParser(inputParser)
.setOutputParser(new JSONOutputParser().setDataType(response_schema))
.setOutputCol("results")

val responses = client.transform(df)
display(responses.select("results"))

**Comment by ranadeepsingh** [comment]
We are closing this issue as complete code examples for performing HTTP GET requests with `CustomInputParser` and `HttpGet` were provided and verified in the thread. If you encounter issues with HttpOnSpark in current releases, please consult the updated documentation or open a new issue.
