### ISSUE TITLE
Param earlyStoppingRound does not exist

### ISSUE THREAD

**Issue by uzair4520** [Azure/mmlspark#729]
I am using mmlspark version 0.15 for python on  my windows system. I am getting following exception while fitting my model. Any help will be highly appreciated.

py4j.protocol.Py4JJavaError: An error occurred while calling o1109.getParam.
: java.util.NoSuchElementException: Param earlyStoppingRound does not exist.
	at org.apache.spark.ml.param.Params$$anonfun$getParam$2.apply(params.scala:729)
	at org.apache.spark.ml.param.Params$$anonfun$getParam$2.apply(params.scala:729)
	at scala.Option.getOrElse(Option.scala:121)
	at org.apache.spark.ml.param.Params$class.getParam(params.scala:728)
	at org.apache.spark.ml.PipelineStage.getParam(Pipeline.scala:42)
	at sun.reflect.GeneratedMethodAccessor55.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at py4j.reflection.MethodInvoker.invoke(MethodInvoker.java:244)
	at py4j.reflection.ReflectionEngine.invoke(ReflectionEngine.java:357)
	at py4j.Gateway.invoke(Gateway.java:282)
	at py4j.commands.AbstractCommand.invokeMethod(AbstractCommand.java:132)
	at py4j.commands.CallCommand.execute(CallCommand.java:79)
	at py4j.GatewayConnection.run(GatewayConnection.java:238)
	at java.lang.Thread.run(Thread.java:745)

**Comment by ocworld** [comment]
It is written in v0.17's release comments that is "Add early stopping capabilities". I assume a early stopping parameter from v0.17.

**Comment by imatiach-msft** [comment]
@uzair4520 early stopping does exist, but you also need to specify the validation data as an index.  I would recommend using the latest 1.0 version as there were a lot of bugfixes for this functionality since 0.17.

**Comment by imatiach-msft** [comment]
closing issue as this feature was added in a newer release
