### ISSUE TITLE
Installation from Maven failing on Databricks

### ISSUE THREAD

**Issue by conorbmurphy** [Azure/mmlspark#745]
Installation using the coordinates "com.microsoft.ml.spark:mmlspark_2.11:1.0.0-rc1" is failing on Databricks clusters.  I'm using DBR 6.1 with Spark 2.4.4 and Scala 2.11.  I'm also using the clusters UI to install the library.

The full stack trace:

`Library resolution failed. Cause: java.lang.RuntimeException: unresolved dependency: com.microsoft.ml.spark:mmlspark_2.11:1.0.0-rc1: not found
	at com.databricks.libraries.server.MavenInstaller.doDownloadMavenPackages(MavenLibraryResolver.scala:438)
	at com.databricks.libraries.server.MavenInstaller.$anonfun$downloadMavenPackages$2(MavenLibraryResolver.scala:381)
	at com.databricks.backend.common.util.FileUtils$.withTemporaryDirectory(FileUtils.scala:431)
	at com.databricks.libraries.server.MavenInstaller.$anonfun$downloadMavenPackages$1(MavenLibraryResolver.scala:380)
	at com.databricks.logging.UsageLogging.$anonfun$recordOperation$4(UsageLogging.scala:417)
	at com.databricks.logging.UsageLogging.$anonfun$withAttributionContext$1(UsageLogging.scala:239)
	at scala.util.DynamicVariable.withValue(DynamicVariable.scala:62)
	at com.databricks.logging.UsageLogging.withAttributionContext(UsageLogging.scala:234)
	at com.databricks.logging.UsageLogging.withAttributionContext$(UsageLogging.scala:231)
	at com.databricks.libraries.server.MavenInstaller.withAttributionContext(MavenLibraryResolver.scala:57)
	at com.databricks.logging.UsageLogging.withAttributionTags(UsageLogging.scala:276)
	at com.databricks.logging.UsageLogging.withAttributionTags$(UsageLogging.scala:269)
	at com.databricks.libraries.server.MavenInstaller.withAttributionTags(MavenLibraryResolver.scala:57)
	at com.databricks.logging.UsageLogging.recordOperation(UsageLogging.scala:398)
	at com.databricks.logging.UsageLogging.recordOperation$(UsageLogging.scala:337)
	at com.databricks.libraries.server.MavenInstaller.recordOperation(MavenLibraryResolver.scala:57)
	at com.databricks.libraries.server.MavenInstaller.downloadMavenPackages(MavenLibraryResolver.scala:379)
	at com.databricks.libraries.server.MavenInstaller.downloadMavenPackagesWithRetry(MavenLibraryResolver.scala:137)
	at com.databricks.libraries.server.MavenInstaller.resolveMavenPackages(MavenLibraryResolver.scala:113)
	at com.databricks.libraries.server.MavenLibraryResolver.resolve(MavenLibraryResolver.scala:44)
	at com.databricks.libraries.server.ManagedLibraryManager$GenericManagedLibraryResolver.resolve(ManagedLibraryManager.scala:263)
	at com.databricks.libraries.server.ManagedLibraryManagerImpl.$anonfun$resolvePrimitives$1(ManagedLibraryManagerImpl.scala:193)
	at com.databricks.libraries.server.ManagedLibraryManagerImpl.$anonfun$resolvePrimitives$1$adapted(ManagedLibraryManagerImpl.scala:188)
	at scala.collection.Iterator.foreach(Iterator.scala:941)
	at scala.collection.Iterator.foreach$(Iterator.scala:941)
	at scala.collection.AbstractIterator.foreach(Iterator.scala:1429)
	at scala.collection.IterableLike.foreach(IterableLike.scala:74)
	at scala.collection.IterableLike.foreach$(IterableLike.scala:73)
	at scala.collection.AbstractIterable.foreach(Iterable.scala:56)
	at com.databricks.libraries.server.ManagedLibraryManagerImpl.resolvePrimitives(ManagedLibraryManagerImpl.scala:188)
	at com.databricks.libraries.server.ManagedLibraryManagerImpl$ClusterStatus.installLibs(ManagedLibraryManagerImpl.scala:772)
	at com.databricks.libraries.server.ManagedLibraryManagerImpl$InstallLibTask$1.run(ManagedLibraryManagerImpl.scala:473)
	at com.databricks.threading.NamedExecutor$$anon$1.$anonfun$run$1(NamedExecutor.scala:317)
	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:23)
	at com.databricks.logging.UsageLogging.$anonfun$withAttributionContext$1(UsageLogging.scala:239)
	at scala.util.DynamicVariable.withValue(DynamicVariable.scala:62)
	at com.databricks.logging.UsageLogging.withAttributionContext(UsageLogging.scala:234)
	at com.databricks.logging.UsageLogging.withAttributionContext$(UsageLogging.scala:231)
	at com.databricks.threading.NamedExecutor.withAttributionContext(NamedExecutor.scala:256)
	at com.databricks.threading.NamedExecutor$$anon$1.run(NamedExecutor.scala:317)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)`

**Comment by imatiach-msft** [comment]
@conorbmurphy I believe there is already an issue for this here:
https://github.com/Azure/mmlspark/issues/715
also adding @mhamilton723

**Comment by conorbmurphy** [comment]
Yes, looks like the same issue.  Thanks!

**Comment by Hugheym** [comment]
Adding "https://mmlspark.azureedge.net/maven" to the repository field fixed the issue for me.

**Comment by candalfigomoro** [comment]
@imatiach-msft @mhamilton723 
For the next release, would it be possible to use the same repository used for version 0.18.x? In some very restrictive environments adding an additional repo is a problem (I still could not test v1.0.0-rc1)

**Comment by akshaya-a** [comment]
@mhamilton723 / @imatiach-msft  can we close this?

**Comment by nfplay** [comment]
Is there a fix for this? I'm having the same problem and @Hugheym 's fix didn't work for me.

Thanks

**Comment by ranadeepsingh** [comment]
Thank you for reaching out! The legacy `com.microsoft.ml.spark:mmlspark_2.11` artifact coordinates and Spark 2.4 (Scala 2.11) runtime environments have been retired. The library is now published as SynapseML under `com.microsoft.azure.synapse:synapseml_2.12` on Maven Central for Spark 3.x. Since the legacy coordinates and environment are obsolete, we are closing this issue.
