### ISSUE TITLE
Crash when fitting a model twice

### ISSUE THREAD

**Issue by jelmerk** [Azure/mmlspark#770]
**Describe the bug**

I am using lightgbm 1.0-rc1 with jdk1.8.0_181 and scala on Ubuntu 14.04.6 the following snippet will give the error

> ** Error in `/path/to/jdk1.8.0_181/bin/java': double free or corruption (!prev): 0x00007f47043db4d0 ***

```
import com.microsoft.ml.spark.lightgbm.LightGBMClassifier

val clf = new LightGBMClassifier()
      .setFeaturesCol("features")
      .setLabelCol("label")
      .setPredictionCol("prediction")
      .setObjective("binary")
      .setNumLeaves(6)
      .setNumIterations(10)

clf.fit(trainingData)
clf.fit(trainingData) //  invoking fit a second time will trigger the error
```

The schema of the training data is

root
 |-- features: vector (nullable = true)
 |-- label: double (nullable = true)

**Comment by jelmerk** [comment]
I tried downgrading to 0.18.1 this gives me 

> java.lang.IncompatibleClassChangeError: vtable stub
>         at scala.collection.SetLike$$anonfun$$plus$plus$1.apply(SetLike.scala:141)
>         at scala.collection.SetLike$$anonfun$$plus$plus$1.apply(SetLike.scala:141)
>         at scala.collection.LinearSeqOptimized$class.foldLeft(LinearSeqOptimized.scala:124)
>         at scala.collection.immutable.List.foldLeft(List.scala:84)
>         at scala.collection.TraversableOnce$class.$div$colon(TraversableOnce.scala:151)
>         at scala.collection.AbstractTraversable.$div$colon(Traversable.scala:104)
>         at scala.collection.SetLike$class.$plus$plus(SetLike.scala:141)
>         at scala.collection.AbstractSet.$plus$plus(Set.scala:47)
>         at scala.tools.nsc.interpreter.Imports$class.select$1(Imports.scala:130)
>         at scala.tools.nsc.interpreter.Imports$class.reqsToUse$1(Imports.scala:140)
>         at scala.tools.nsc.interpreter.Imports$$anonfun$importsCode$1.apply$mcV$sp(Imports.scala:166)
>         at scala.tools.nsc.interpreter.Imports$$anonfun$importsCode$1.apply(Imports.scala:163)
>         at scala.tools.nsc.interpreter.Imports$$anonfun$importsCode$1.apply(Imports.scala:163)
>         at scala.tools.nsc.interpreter.Imports$class.wrapBeforeAndAfter$1(Imports.scala:156)
>         at scala.tools.nsc.interpreter.Imports$class.importsCode(Imports.scala:163)
>         at scala.tools.nsc.interpreter.IMain.importsCode(IMain.scala:64)
>         at scala.tools.nsc.interpreter.IMain$Request$$anonfun$16.apply(IMain.scala:903)
>         at scala.tools.nsc.interpreter.IMain$Request$$anonfun$16.apply(IMain.scala:903)
>         at scala.reflect.internal.SymbolTable.enteringPhase(SymbolTable.scala:235)
>         at scala.reflect.internal.SymbolTable.exitingPhase(SymbolTable.scala:256)

**Comment by imatiach-msft** [comment]
interesting, this is an untested scenario, not sure about how it should behave yet, but it is definitely a bug for it to crash like this.

**Comment by ranadeepsingh** [comment]
Thank you for reporting this issue! The native C++ library double-free crash when invoking `.fit()` multiple times on the same estimator instance was resolved by refactoring native SWIG handle lifecycles within task scopes. This fix is included in published releases (v1.0.0 and later). We are closing this issue as fixed in published releases.
