### ISSUE TITLE
Lightgbm example code with Categorical feature

### ISSUE THREAD

**Issue by nirupamkar** [Azure/mmlspark#774]
Hello,
I have been trying to use lgb for a dataset having categorical feature. However I am facing issues like num_cat being zero in tree produced .
Would it be possible for you to kindly add an example code which clearly shows how to use categorical features in lightgbm? And if I may request, the following info/code would really help
1.How to use categorical features directly without label encoding like the python lgb does?
2.How to use weight for training etc
Thanks in advance

**Comment by nirupamkar** [comment]
Attaching a dummy code.
'
from mmlspark.lightgbm import LightGBMClassifier
import math

from matplotlib.colors import ListedColormap, Normalize
from matplotlib.cm import get_cmap
import matplotlib.pyplot as plt
from mmlspark.lightgbm import LightGBMRegressor
import numpy as np
import pandas as pd
from pyspark.ml.feature import VectorAssembler,StringIndexer
from pyspark.ml.regression import LinearRegression
import pyspark.sql.types as T

df=spark.createDataFrame(
    [
        (1, 'a1',"b2","c3",10), # create your data here, be consistent in the types.
        (2, 'a2',"b2","c3",2),
        (3, 'a2',"b3","c1",2),
        (4, 'a1',"b2","c1",2),
        (5, 'a2',"b3","c1",2),
        (6, 'a3',"b2","c3",2),
        (7, 'a2',"b2","c2",2),
        (4, 'a3',"b4","c2",2),
        (5, 'a2',"b2","c2",2),
        (2, 'a1',"b2","c2",2),
        (10, 'a2',"b3","c2",2),
        
    ],
    ['target', "cat_f1","cat_f2","cat_f3","weight"] # add your columns label here
)

for i in range(5):
    print(i)
    df=df.union(df)
    print(df.cache().count())

train, test = df.randomSplit([0.85, 0.15], seed=1)

feature_cols=["cat_f1","cat_f2","cat_f3"]
feature_cols_index=[]
for col in feature_cols:
    indexer = StringIndexer(inputCol=col, outputCol=col+"_index",handleInvalid="keep")
    model=indexer.fit(train)
    train = model.transform(train)
    test = model.transform(test)
    feature_cols_index.append(col+"_index")

featurizer = VectorAssembler(
    inputCols=feature_cols_index,
    outputCol='features'
)
lr_train_data = featurizer.transform(train)['target', 'features']
lr_test_data = featurizer.transform(test)['target', 'features']

lgr = LightGBMRegressor(
    objective='regression',
    learningRate=0.3,
    numLeaves=10,
    labelCol='target',
    numIterations=5,categoricalSlotNames=feature_cols_index,
)

lg_model = lgr.fit(lr_train_data.coalesce(1))


The model has no tree with num_cat>0.
tree
version=v2
num_class=1
num_tree_per_iteration=1
label_index=0
max_feature_idx=2
objective=regression
feature_names=cat_f1_index cat_f2_index cat_f3_index
feature_infos=[0:2] [0:2] [0:2]
tree_sizes=762 788 788 792 792

Tree=0
num_leaves=9
num_cat=0
split_feature=2 0 1 0 2 0 0 0
split_gain=365.008 631.038 271.61 194.19 207.638 54 14.2456 1.42109e-14
threshold=1.0000000180025095e-35 1.0000000180025095e-35 1.0000000180025095e-35 1.5000000000000002 1.5000000000000002 1.5000000000000002 1.0000000180025095e-35 1.0000000180025095e-35
decision_type=2 2 2 2 2 2 2 2
left_child=1 2 -1 4 6 -3 -2 -6
right_child=3 5 -4 -5 7 -7 -8 -9
leaf_value=4.9495530457408208 3.7113712197562125 3.7113712197562125 6.1113712197562124 4.9113712197562123 4.3113712286969088 4.3113712376376059 3.4113712197562123 4.3113712376376059
leaf_count=55 29 27 27 25 56 27 28 25
internal_value=0 1.2096 2.95762 -1.00923 -1.4738 -1.44482 -2.93604 -0.444816
internal_count=299 136 82 163 138 54 57 81
shrinkage=1


Tree=1
num_leaves=9
num_cat=0
split_feature=2 0 1 0 2 0 0 0
split_gain=178.854 309.209 133.089 95.1529 101.743 26.46 6.98035 1.5099e-14
threshold=1.0000000180025095e-35 1.0000000180025095e-35 1.0000000180025095e-35 1.5000000000000002 1.5000000000000002 1.5000000000000002 1.0000000180025095e-35 1.0000000180025095e-35
decision_type=2 2 2 2 2 2 2 2
left_child=1 2 -1 4 6 -3 -2 -6
right_child=3 5 -4 -5 7 -7 -8 -9
leaf_value=0.35331590993837875 -0.51341135501861568 -0.51341135501861568 1.1665886163711547 0.32658863067626953 -0.093411362171173087 -0.093411371111869812 -0.7234113693237304 -0.093411371111869812
leaf_count=55 29 27 27 25 56 27 28 25
internal_value=0 0.846717 2.07034 -0.706463 -1.03166 -1.01137 -2.05523 -0.311371
internal_count=299 136 82 163 138 54 57 81
shrinkage=0.3

'

**Comment by nirupamkar** [comment]
@imatiach-msft any help on this?

**Comment by imatiach-msft** [comment]
@nirupamkar sorry which version of mmlspark are you currently using?  there have been a lot of categorical-handling bugfixes recently.

**Comment by imatiach-msft** [comment]
any way to ensure you have this bugfix from back in September:
https://github.com/Azure/mmlspark/pull/685

**Comment by imatiach-msft** [comment]
this seems very similar to this issue:
https://github.com/Azure/mmlspark/issues/665
"In the MMLSpark model we see num_cat always equals to 0 on each tree as seen below"
you are also seeing num_cat as zero.

The code you have above should work.  You don't even have to pass this:
```categoricalSlotNames=feature_cols_index,```
it should already be taken care of because you are using StringIndexer.
My guess is that you are using an older version which doesn't have this recent bugfix.

**Comment by nirupamkar** [comment]
@imatiach-msft We have tried "spark-shell --packages com.microsoft.ml.spark:mmlspark_2.11:1.0.0-rc1 ". It says
`Exception in thread "main" java.lang.RuntimeException: [unresolved dependency: com.microsoft.ml.spark#mmlspark_2.11;1.0.0-rc1: not found]`
It did not find anything on maven repository.

We tried "--packages com.microsoft.ml.spark:mmlspark_2.11:0.18.1 ", and install mmlspark, does it include the fix you are talking about?

**Comment by nirupamkar** [comment]
@imatiach-msft , version was the issue to get started. It is working with num_cat coming to be >0. Could you please let me know if there is anyway to use categorical feature without doing label encoding via StringIndexer. 
In lightgbm python, we could just use astype("category") on pandas dataframe and use that feature. So when using the model afterwards, this feature to index mapping does not need to be passed

**Comment by nirupamkar** [comment]
@imatiach-msft any help on this?

**Comment by kogandaniil** [comment]
@nirupamkar In order to get latest version you should add a repository in spark-defaults or a resolver in build.sbt as described here: https://github.com/Azure/mmlspark/issues/715

**Comment by nirupamkar** [comment]
@kogandaniil like I said in my last post, I updated the version and I am seeing num_cat>0. However I want to know
 if there is anyway to use categorical feature without doing label encoding via StringIndexer.
In lightgbm python, we could just use astype("category") on pandas dataframe and use that feature. So when using the model afterwards, this feature to index mapping does not need to be passed

**Comment by nirupamkar** [comment]
@kogandaniil @imatiach-msft any help on above?

**Comment by imatiach-msft** [comment]
hi @nirupamkar ,
"to use categorical feature without doing label encoding via StringIndexer"
yes, you can pass either slot indexes or names (if they are on metadata) and those slots on the vector column will be treated as categorcial features:

https://github.com/Azure/mmlspark/blob/master/src/main/scala/com/microsoft/ml/spark/lightgbm/LightGBMParams.scala#L109

https://github.com/Azure/mmlspark/blob/master/src/main/scala/com/microsoft/ml/spark/lightgbm/LightGBMParams.scala#L117

you can also modify the spark dataframe metadata directly to mark the columns as categorical if you don't want to use string indexer (because that is the metadata we are using), but I'm not sure if you want to dabble in spark metadata (unfortunately it's not as easy as saying astype("category") like in pandas).

**Comment by yinyan5988** [comment]
Hi @imatiach-msft , I found the code you showed is scala version. Does that mean pyspark currently doesn't support categoricalSlotNames? I tried to specify which column is categorical feature. But it got error.  
lgb = LightGBMRegressor(alpha=0.3,
                learningRate=0.3,
                numIterations=100,
                numLeaves=31,
                labelCol='sales',
                categoricalSlotNames = 'fea1',
                featuresCol='features')
assembler = VectorAssembler(
    inputCols=['fea1','fea2','fea3','fea4','fea5'],
    outputCol="features")
train_sub_tran = assembler.transform(train_sub)
model = lgb.fit(train_sub_tran)
And I got the error
Py4JJavaError: An error occurred while calling o31815.fit.
: java.lang.ClassCastException: java.lang.Integer cannot be cast to [I
	at com.microsoft.ml.spark.LightGBMBase$class.train(LightGBMBase.scala:37)
	at com.microsoft.ml.spark.LightGBMRegressor.train(LightGBMRegressor.scala:35)
	at com.microsoft.ml.spark.LightGBMRegressor.train(LightGBMRegressor.scala:35)
	at org.apache.spark.ml.Predictor.fit(Predictor.scala:120)
	at sun.reflect.GeneratedMethodAccessor861.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at py4j.reflection.MethodInvoker.invoke(MethodInvoker.java:244)
	at py4j.reflection.ReflectionEngine.invoke(ReflectionEngine.java:380)
	at py4j.Gateway.invoke(Gateway.java:295)
	at py4j.commands.AbstractCommand.invokeMethod(AbstractCommand.java:132)
	at py4j.commands.CallCommand.execute(CallCommand.java:79)
	at py4j.GatewayConnection.run(GatewayConnection.java:251)
	at java.lang.Thread.run(Thread.java:748)

**Comment by imatiach-msft** [comment]
@yinyan5988 pyspark should support categoricalSlotNames.  Could you create a new issue, it might be easier to keep track of it since I believe this issue should be resolved (or at least, we just need to have better documentation), while you seem to be getting an error?  Also, categoricalSlotNames should be an array.  What version are you on?  Can you try the latest from master:

Maven Coordinates
com.microsoft.ml.spark:mmlspark_2.11:1.0.0-rc1-96-fce3c952-SNAPSHOT
Maven Resolver
https://mmlspark.azureedge.net/maven

**Comment by yinyan5988** [comment]
Hi Maven,

Sure. Let me create a new issue. Btw, I tried both. An array version [‘feat1’] and that one. Neither of them work. Should I use string type for that feature? Since it is integer type. And other columns of my features are in different type. Idk if this is the problem.\

Best,
Yan

**Comment by eromoe** [comment]
@imatiach-msft 
> yes, you can pass either slot indexes or names (if the names exist on metadata, they might not in which case slot indexes is the only way) and those slots on the vector column will be treated as categorcial features:

What do you mean `names exist on metadata` ?
I am using pyspark, if I have a dataframe with `['category_1',  'count', 'features', 'label']` , which `features` is constructed by `['category_1',  'count']` .
In this way , do you mean  `categoricalSlotNames=['category_1']`  doesn't take effect ?

**Comment by jylinstat** [comment]
> @yinyan5988 pyspark should support categoricalSlotNames. Could you create a new issue, it might be easier to keep track of it since I believe this issue should be resolved (or at least, we just need to have better documentation), while you seem to be getting an error? Also, categoricalSlotNames should be an array. What version are you on? Can you try the latest from master:
> 
> Maven Coordinates com.microsoft.ml.spark:mmlspark_2.11:1.0.0-rc1-96-fce3c952-SNAPSHOT Maven Resolver https://mmlspark.azureedge.net/maven

did not work for me

**Comment by jylinstat** [comment]
> 
sorry
chang to 'com.microsoft.ml.spark:mmlspark_2.11:1.0.0-rc3'
it works
