### ISSUE TITLE
[LIGHTGBM]LightGBMRanker failing for negative GroupColumn values with message: DatasetSetField call failed in LightGBM with error: Sum of query counts is not same with #data

### ISSUE THREAD

**Issue by JoanFM** [Azure/mmlspark#801]
**Describe the bug**
When calling LightGBMRanker fit with data where the grouping column has negative values 

**To Reproduce**
Example of spark-shell
`import com.microsoft.ml.spark.lightgbm.LightGBMRanker
import org.apache.spark.ml.linalg.Vector
import org.apache.spark.ml.linalg.Vectors
import spark.implicits._

case class Sample[T](GroupID: T, ItemID: Int, Label: Int, Features: Vector)

val intSamples = (1 to 1000).map(i => Sample(i % 10000, i % 50, i % 5, Vectors.dense(Array(i.toDouble%5, i.toDouble%3, i.toDouble%4))))

val trainDSInt = sc.parallelize(intSamples).toDS.withColumn("Validation", lit(false))

val valIntSamples = (1 to 200).map(i => Sample(i % 20, i % 50, i % 5, Vectors.dense(Array(i.toDouble%5, i.toDouble%3, i.toDouble%4))))

val valDSInt = sc.parallelize(valIntSamples).toDS.withColumn("Validation", lit(true))

val gradientBooster = new LightGBMRanker().setFeaturesCol("Features").setLabelCol("Label").setGroupCol("GroupID").setValidationIndicatorCol("validation").setNumIterations(1).setNumLeaves(2).setMaxDepth(2).setMaxPosition(200)

val dataSet = trainDSInt.withColumn("Validation", lit(false)).union(valDSInt.withColumn("Validation", lit(true)))

val model = gradientBooster.fit(dataSet).getModel
model.model

val NegativeintSamples = (1 to 1000).map(i => Sample(-i % 10, i % 50, i % 5, Vectors.dense(Array(i.toDouble%5, i.toDouble%3, i.toDouble%4))))

val NegativetrainDSInt = sc.parallelize(NegativeintSamples).toDS

val NegativevalIntSamples = (1 to 200).map(i => Sample(-i % 20, i % 50, i % 5, Vectors.dense(Array(i.toDouble%5, i.toDouble%3, i.toDouble%4))))

val NegativevalDSInt = sc.parallelize(NegativevalIntSamples).toDS

val NegativegradientBooster = new LightGBMRanker().setFeaturesCol("Features").setLabelCol("Label").setGroupCol("GroupID").setValidationIndicatorCol("validation").setNumIterations(1).setNumLeaves(2).setMaxDepth(2).setMaxPosition(200)

val NegativedataSet = NegativetrainDSInt.withColumn("Validation", lit(false)).union(NegativevalDSInt.withColumn("Validation", lit(true)))

val Negativemodel = NegativegradientBooster.fit(NegativedataSet).getModel
Negativemodel.model`

See that it works where the GroupID are positive but not when they are negative

**Expected behavior**
Should not fail

**Info (please complete the following information):**
 - MMLSpark Version: 0.18.1
 - Spark Version 2.4.4

** Stacktrace**
`Caused by: java.lang.Exception: DatasetSetField call failed in LightGBM with error: Sum of query counts is not same with #data
  at com.microsoft.ml.spark.lightgbm.LightGBMUtils$.validate(LightGBMUtils.scala:31)
  at com.microsoft.ml.spark.lightgbm.LightGBMDataset.addIntField(LightGBMDataset.scala:81)
  at com.microsoft.ml.spark.lightgbm.TrainUtils$$anonfun$addGroupColumn$1.apply(TrainUtils.scala:126)
  at com.microsoft.ml.spark.lightgbm.TrainUtils$$anonfun$addGroupColumn$1.apply(TrainUtils.scala:99)
  at scala.Option.foreach(Option.scala:257)
  at com.microsoft.ml.spark.lightgbm.TrainUtils$.addGroupColumn(TrainUtils.scala:99)
  at com.microsoft.ml.spark.lightgbm.TrainUtils$.generateDataset(TrainUtils.scala:89)
  at com.microsoft.ml.spark.lightgbm.TrainUtils$.translate(TrainUtils.scala:258)
  at com.microsoft.ml.spark.lightgbm.TrainUtils$.trainLightGBM(TrainUtils.scala:411)
  at com.microsoft.ml.spark.lightgbm.LightGBMBase$$anonfun$6.apply(LightGBMBase.scala:85)
  at com.microsoft.ml.spark.lightgbm.LightGBMBase$$anonfun$6.apply(LightGBMBase.scala:85)
  at org.apache.spark.sql.execution.MapPartitionsExec$$anonfun$5.apply(objects.scala:188)
  at org.apache.spark.sql.execution.MapPartitionsExec$$anonfun$5.apply(objects.scala:185)
  at org.apache.spark.rdd.RDD$$anonfun$mapPartitionsInternal$1$$anonfun$apply$24.apply(RDD.scala:836)
  at org.apache.spark.rdd.RDD$$anonfun$mapPartitionsInternal$1$$anonfun$apply$24.apply(RDD.scala:836)`
```

**Comment by ranadeepsingh** [comment]
We are confirming closure of this issue as the LightGBMRanker negative group ID partitioning issue was fixed in PR #778 (commit e745784c7e). LightGBMRanker now automatically repartitions data by the grouping column, ensuring proper distribution across partitions. This fix is included in published releases including v1.1.3.
