### ISSUE TITLE
java.lang.UnsatisfiedLinkError: Reason: image not found

### ISSUE THREAD

**Issue by BhushG** [Azure/mmlspark#815]
**Describe the bug**
I've installed libopm already using : brew install libomp
Same LightGBMClassifier with same dependency runs on Ubuntu but doesn't run on Mac OS.
        
        <dependency>
            <groupId>com.microsoft.ml.spark</groupId>
            <artifactId>mmlspark_2.11</artifactId>
            <version>0.18.1</version>
        </dependency>

**To Reproduce**
Run any LightGBMClassifier on Mac OS

**Info (please complete the following information):**
 - MMLSpark Version: 0.18.1
 - Spark Version 2.4.0
 - Spark Platform : local, Mac OS

** Stacktrace**
```
Caused by: java.lang.UnsatisfiedLinkError: /private/var/folders/bk/x34npyr17414f2y69fcjpspnfbmckp/T/mml-natives3463521485175743851/lib_lightgbm.dylib: dlopen(/private/var/folders/bk/x34npyr17414f2y69fcjpspnfbmckp/T/mml-natives3463521485175743851/lib_lightgbm.dylib, 1): Library not loaded: /usr/local/opt/libomp/lib/libomp.dylib
  Referenced from: /private/var/folders/bk/x34npyr17414f2y69fcjpspnfbmckp/T/mml-natives3463521485175743851/lib_lightgbm.dylib
  Reason: image not found
	at java.lang.ClassLoader$NativeLibrary.load(Native Method)
	at java.lang.ClassLoader.loadLibrary0(ClassLoader.java:1941)
	at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1824)
	at java.lang.Runtime.load0(Runtime.java:809)
	at java.lang.System.load(System.java:1086)
```

If the bug pertains to a specific feature please tag the appropriate [CODEOWNER](https://github.com/Azure/mmlspark/blob/master/CODEOWNERS) for better visibility

**Additional context**

**Comment by ranadeepsingh** [comment]
We are closing this issue as a duplicate of canonical Issue #668. Both issues report the identical UnsatisfiedLinkError on macOS when loading lib_lightgbm.dylib due to the native OpenMP runtime library (libomp.dylib) path resolution. Please follow Issue #668 for updates regarding macOS LightGBM native library linking.
