### ISSUE TITLE
Error When Trying To Use CNTKModel()

### ISSUE THREAD

**Issue by Kinchenn** [Azure/mmlspark#819]
**Describe the bug**
I am trying to follow the DeepLearning - BiLSTM Medical Entity Extraction.ipynb example which I have done previously. But, this time I am getting an error when running this block of code: 

``` 
model = CNTKModel() \
    .setModelLocation(modelSchema.uri) \
    .setInputCol("features") \
    .setOutputCol("probs") \
    .setOutputNodeIndex(0) \
    .setMiniBatchSize(1)
 ```

**To Reproduce**
Run this notebook: https://github.com/Azure/mmlspark/blob/master/notebooks/samples/DeepLearning%20-%20BiLSTM%20Medical%20Entity%20Extraction.ipynb

**Info (please complete the following information):**
 - MMLSpark Version:  mmlspark_2.11:1.0.0-rc1
 - Spark Version: 2.4.3
 - Spark Platform: Databricks

** Stacktrace**
```
Py4JJavaError: An error occurred while calling None.com.microsoft.ml.spark.cntk.CNTKModel.
: java.lang.NoSuchMethodError: com.microsoft.CNTK.CNTKUtils$.ArgumentPrefix()Ljava/lang/String;
	at com.microsoft.ml.spark.cntk.CNTKModel.<init>(CNTKModel.scala:207)
	at com.microsoft.ml.spark.cntk.CNTKModel.<init>(CNTKModel.scala:148)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at py4j.reflection.MethodInvoker.invoke(MethodInvoker.java:247)
	at py4j.reflection.ReflectionEngine.invoke(ReflectionEngine.java:380)
	at py4j.Gateway.invoke(Gateway.java:250)
	at py4j.commands.ConstructorCommand.invokeConstructor(ConstructorCommand.java:80)
	at py4j.commands.ConstructorCommand.execute(ConstructorCommand.java:69)
	at py4j.GatewayConnection.run(GatewayConnection.java:251)
	at java.lang.Thread.run(Thread.java:748)
```

If the bug pertains to a specific feature please tag the appropriate [CODEOWNER](https://github.com/Azure/mmlspark/blob/master/CODEOWNERS) for better visibility

**Additional context**

**Comment by ranadeepsingh** [comment]
We are confirming closure of this issue because CNTK (Microsoft Cognitive Toolkit) was officially retired by Microsoft, and CNTKModel support in SynapseML has been removed. Deep learning model inference in SynapseML is now supported via ONNXModel using ONNX Runtime. Please migrate your models to ONNX format and use ONNXModel in the deep-learning module.
