### ISSUE TITLE
com.microsoft.ml.spark.stages.Lambda

### ISSUE THREAD

**Issue by softwareland** [Azure/mmlspark#844]
I rewrite Automated Snow Leopard Detection with Microsoft ML for Apache Spark example to Scala. Just for test need. 
There is my code:
https://github.com/softwareland/imagerecognize/tree/master/src/main/scala/pl/softwareland/photosearch
I deploy spark application with Azure Spark plugin for IntelliJ IDEA 2019.1.4 and during deploying I receive the following stack trace:20/03/24 12:03:05 INFO ApplicationMaster: Unregistering ApplicationMaster with FAILED (diag message: User class threw exception: java.lang.NoClassDefFoundError: com/microsoft/ml/spark/stages/Lambda
	at pl.softwareland.SparkAppStarter$.delayedEndpoint$pl$softwareland$SparkAppStarter$1(SparkAppStarter.scala:15)
	at pl.softwareland.SparkAppStarter$delayedInit$body.apply(SparkAppStarter.scala:7)
	at scala.Function0$class.apply$mcV$sp(Function0.scala:34)
	at scala.runtime.AbstractFunction0.apply$mcV$sp(AbstractFunction0.scala:12)
	at scala.App$$anonfun$main$1.apply(App.scala:76)
	at scala.App$$anonfun$main$1.apply(App.scala:76)
	at scala.collection.immutable.List.foreach(List.scala:392)
	at scala.collection.generic.TraversableForwarder$class.foreach(TraversableForwarder.scala:35)
	at scala.App$class.main(App.scala:76)
	at pl.softwareland.SparkAppStarter$.main(SparkAppStarter.scala:7)
	at pl.softwareland.SparkAppStarter.main(SparkAppStarter.scala)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.spark.deploy.yarn.ApplicationMaster$$anon$2.run(ApplicationMaster.scala:678)
Caused by: java.lang.ClassNotFoundException: com.microsoft.ml.spark.stages.Lambda
	at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:419)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:352)
	... 16 more
)
v: MMLSPARK 1.0.0-rc1 
HDInsight cluster with spark 2.4

**Comment by ranadeepsingh** [comment]
We are closing this issue as it stems from a deployment classpath configuration where the library JAR was not included on the Spark executor classpath during application submission on HDInsight. In addition, the package namespace has since been updated from com.microsoft.ml.spark to com.microsoft.azure.synapse.ml. Please ensure that the current com.microsoft.azure:synapseml_2.12 package is included via --packages or attached to your cluster runtime.
