### ISSUE TITLE
Provide more detailed documentation for pyspark install & implementation

### ISSUE THREAD

**Issue by njgerner** [Azure/mmlspark#854]
**Is your feature request related to a problem? Please describe.**
Trying to get mmlspark running in pyspark has been more challenging than it should be.  I'm able to run the latest version when launching a pyspark shell or spark-submit job but had some trouble getting the most up to date version of the package to my local machine to use in local development and importing into our testing environment. 

Here are some of the issues I ran into:
1. Installing directly pypi using pip installed an outdated version of the python library. https://pypi.org/project/mmlspark/ currently points to `mmlspark 0.0.11111111`. Ideally, this library would be up to date.
Not great
```bash
pip install mmlspark
```
2. It is still possible to install a somewhat recent version via the wheel file but I don't see this documented anywhere and had to hunt for it.
Better
```bash
pip install https://mmlspark.azureedge.net/pip/mmlspark-0.17-py2.py3-none-any.whl
```
3. I'm unable to build directly from the git source as it looks like I'm missing some environment variables. Might be able to get this to work but don't have the time to dive in.
Errors out
```bash
pip install -e "git+https://github.com/Azure/mmlspark.git#egg=mmlspark&subdirectory=src/main/python"

Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/path/to/module/src/mmlspark/src/main/python/setup.py", line 9, in <module>
        version=os.environ["MML_PY_VERSION"],
      File "/usr/local/Cellar/python@2/2.7.15_2/Frameworks/Python.framework/Versions/2.7/lib/python2.7/UserDict.py", line 40, in __getitem__
        raise KeyError(key)
    KeyError: 'MML_PY_VERSION'
```

**Describe the solution you'd like**
Easier to use pyspark install documentation. If it exists would love a link to it.

**Comment by nchaly** [comment]
@njgerner mmlspark is a scala library, packed into jar archive. It contains python/R code, which is mostly wrappers/facades to native code, and never intended to use standalone.

For maintainers: This actually causes issues while developing in IDE - python syntax/dependency analysis fails (understandably) to resolve references to mmlspark. I'd propose to generate and distribute [stub files](https://www.python.org/dev/peps/pep-0484/#stub-files) library for mmlspark - this [has been in practice for pyspark ](https://github.com/zero323/pyspark-stubs) for some time.

**Comment by ranadeepsingh** [comment]
Thanks for the detailed feedback, and apologies that this stayed open after the documentation improved. The current installation guide now covers pip/PySpark setup, local development, Microsoft Fabric, Synapse, Spark packages, Databricks, Livy, Docker, source builds, and R.

References:
- Installation guide: https://microsoft.github.io/SynapseML/docs/Get%20Started/Install%20SynapseML/
- Current release: https://github.com/microsoft/SynapseML/releases/tag/v1.1.3

I am closing this documentation request as completed. Please file a focused follow-up if any current command or platform section is inaccurate.
