### ISSUE TITLE
Lightgbm categoricalSlotNames error

### ISSUE THREAD

**Issue by yinyan5988** [Azure/mmlspark#877]
**Describe the bug**
Error occurred when using categoricalSlotNames

**To Reproduce**
lgb = LightGBMRegressor(alpha=0.3,
learningRate=0.3,
numIterations=100,
numLeaves=31,
labelCol='sales',
categoricalSlotNames = ['fea1'],
featuresCol='features')
assembler = VectorAssembler(
inputCols=['fea1','fea2','fea3','fea4','fea5'],
outputCol="features")
train_sub_tran = assembler.transform(train_sub)
model = lgb.fit(train_sub_tran)

And I got the error
Py4JJavaError: An error occurred while calling o31815.fit.
: java.lang.ClassCastException: java.lang.Integer cannot be cast to [I
at com.microsoft.ml.spark.LightGBMBase$class.train(LightGBMBase.scala:37)
at com.microsoft.ml.spark.LightGBMRegressor.train(LightGBMRegressor.scala:35)
at com.microsoft.ml.spark.LightGBMRegressor.train(LightGBMRegressor.scala:35)
at org.apache.spark.ml.Predictor.fit(Predictor.scala:120)
at sun.reflect.GeneratedMethodAccessor861.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at py4j.reflection.MethodInvoker.invoke(MethodInvoker.java:244)
at py4j.reflection.ReflectionEngine.invoke(ReflectionEngine.java:380)
at py4j.Gateway.invoke(Gateway.java:295)
at py4j.commands.AbstractCommand.invokeMethod(AbstractCommand.java:132)
at py4j.commands.CallCommand.execute(CallCommand.java:79)
at py4j.GatewayConnection.run(GatewayConnection.java:251)
at java.lang.Thread.run(Thread.java:748)

**Comment by imatiach-msft** [comment]
@yinyan5988 what version of mmlspark are you using?  Would you be able to try out the latest version to see if the issue is still there?  What dataset did you use to reproduce the issue, is it a public dataset?

This is the latest build:
```
Maven Coordinates
com.microsoft.ml.spark:mmlspark_2.11:1.0.0-rc1-96-fce3c952-SNAPSHOT
Maven Resolver
https://mmlspark.azureedge.net/maven
```
Thank you, Ilya

**Comment by imatiach-msft** [comment]
@yinyan5988 
```
Sure. Let me create a new issue. Btw, I tried both. An array version [‘feat1’] and that one. Neither of them work. Should I use string type for that feature? Since it is integer type. And other columns of my features are in different type. Idk if this is the problem.
```
I don't think this is an issue with the categorical features, but I'm not sure yet.  I think, knowing what version of mmlspark you are using would help a lot, since I'm not able to find the code corresponding to the lines in the stack trace in the latest master.

**Comment by gnayoaixgnaw** [comment]
> help
assembler doesn't support the string type, so how can I generate the input vector via assembler before fitting?

**Comment by ranadeepsingh** [comment]
This issue was resolved in published releases of SynapseML (v1.0.0+ and v1.1.3). The categoricalSlotNames parameter was refactored as a StringArrayParam returning Array[String], resolving the ClassCastException present in the legacy package. As this fix is available in published releases including v1.1.3, we are closing this issue.
