### ISSUE TITLE
LightGBMRanker only takes groupCol as Long or Int

### ISSUE THREAD

**Issue by victorconan** [Azure/mmlspark#880]
**Describe the bug**
I had job failed and the error in the log said:
```
java.lang.IllegalArgumentException: group column must be of type Long or Int but is string
```

**To Reproduce**
I am not sure if this is reproducible. In my case, I've always put a string field to groupCol. Previously it worked. However, recently it frequently failed and the log showed such error.  

**Expected behavior**
In this document: https://lightgbm.readthedocs.io/en/latest/Parameters.html#core-parameters. It seems group column can be either int or string.

**Info (please complete the following information):**
 - MMLSpark Version: 2.11:1.0.0-rc1
 - Spark Version: 2.4.5
 - Spark Platform: Databricks

** Stacktrace**
```
Driver stacktrace:
	at org.apache.spark.scheduler.DAGScheduler.org$apache$spark$scheduler$DAGScheduler$$failJobAndIndependentStages(DAGScheduler.scala:2362)
	at org.apache.spark.scheduler.DAGScheduler$$anonfun$abortStage$1.apply(DAGScheduler.scala:2350)
	at org.apache.spark.scheduler.DAGScheduler$$anonfun$abortStage$1.apply(DAGScheduler.scala:2349)
	at scala.collection.mutable.ResizableArray$class.foreach(ResizableArray.scala:59)
	at scala.collection.mutable.ArrayBuffer.foreach(ArrayBuffer.scala:48)
	at org.apache.spark.scheduler.DAGScheduler.abortStage(DAGScheduler.scala:2349)
	at org.apache.spark.scheduler.DAGScheduler$$anonfun$handleTaskSetFailed$1.apply(DAGScheduler.scala:1102)
	at org.apache.spark.scheduler.DAGScheduler$$anonfun$handleTaskSetFailed$1.apply(DAGScheduler.scala:1102)
	at scala.Option.foreach(Option.scala:257)
	at org.apache.spark.scheduler.DAGScheduler.handleTaskSetFailed(DAGScheduler.scala:1102)
	at org.apache.spark.scheduler.DAGSchedulerEventProcessLoop.doOnReceive(DAGScheduler.scala:2582)
	at org.apache.spark.scheduler.DAGSchedulerEventProcessLoop.onReceive(DAGScheduler.scala:2529)
	at org.apache.spark.scheduler.DAGSchedulerEventProcessLoop.onReceive(DAGScheduler.scala:2517)
	at org.apache.spark.util.EventLoop$$anon$1.run(EventLoop.scala:49)
	at org.apache.spark.scheduler.DAGScheduler.runJob(DAGScheduler.scala:897)
	at org.apache.spark.SparkContext.runJob(SparkContext.scala:2280)
	at org.apache.spark.SparkContext.runJob(SparkContext.scala:2378)
	at org.apache.spark.rdd.RDD$$anonfun$reduce$1.apply(RDD.scala:1087)
	at org.apache.spark.rdd.RDDOperationScope$.withScope(RDDOperationScope.scala:151)
	at org.apache.spark.rdd.RDDOperationScope$.withScope(RDDOperationScope.scala:112)
	at org.apache.spark.rdd.RDD.withScope(RDD.scala:392)
	at org.apache.spark.rdd.RDD.reduce(RDD.scala:1069)
	at org.apache.spark.sql.Dataset$$anonfun$reduce$1.apply(Dataset.scala:1680)
	at org.apache.spark.sql.Dataset$$anonfun$withNewRDDExecutionId$1.apply(Dataset.scala:3486)
	at org.apache.spark.sql.execution.SQLExecution$$anonfun$withCustomExecutionEnv$1$$anonfun$apply$1.apply(SQLExecution.scala:112)
	at org.apache.spark.sql.execution.SQLExecution$.withSQLConfPropagated(SQLExecution.scala:217)
	at org.apache.spark.sql.execution.SQLExecution$$anonfun$withCustomExecutionEnv$1.apply(SQLExecution.scala:98)
	at org.apache.spark.sql.SparkSession.withActive(SparkSession.scala:835)
	at org.apache.spark.sql.execution.SQLExecution$.withCustomExecutionEnv(SQLExecution.scala:74)
	at org.apache.spark.sql.execution.SQLExecution$.withNewExecutionId(SQLExecution.scala:169)
	at org.apache.spark.sql.Dataset.withNewRDDExecutionId(Dataset.scala:3482)
	at org.apache.spark.sql.Dataset.reduce(Dataset.scala:1679)
	at com.microsoft.ml.spark.lightgbm.LightGBMBase$class.innerTrain(LightGBMBase.scala:150)
	at com.microsoft.ml.spark.lightgbm.LightGBMRanker.innerTrain(LightGBMRanker.scala:25)
	at com.microsoft.ml.spark.lightgbm.LightGBMBase$class.train(LightGBMBase.scala:40)
	at com.microsoft.ml.spark.lightgbm.LightGBMRanker.train(LightGBMRanker.scala:25)
	at com.microsoft.ml.spark.lightgbm.LightGBMRanker.train(LightGBMRanker.scala:25)
	at org.apache.spark.ml.Predictor.fit(Predictor.scala:120)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at py4j.reflection.MethodInvoker.invoke(MethodInvoker.java:244)
	at py4j.reflection.ReflectionEngine.invoke(ReflectionEngine.java:380)
	at py4j.Gateway.invoke(Gateway.java:295)
	at py4j.commands.AbstractCommand.invokeMethod(AbstractCommand.java:132)
	at py4j.commands.CallCommand.execute(CallCommand.java:79)
	at py4j.GatewayConnection.run(GatewayConnection.java:251)
	at java.lang.Thread.run(Thread.java:748)
```

If the bug pertains to a specific feature please tag the appropriate [CODEOWNER](https://github.com/Azure/mmlspark/blob/master/CODEOWNERS) for better visibility

**Additional context**

**Comment by imatiach-msft** [comment]
@victorconan Sorry about the trouble you are having.
Looking at history, it looks like this was fixed with this PR:
https://github.com/Azure/mmlspark/pull/714
Indeed, it seems that in the latest master string is also supported:
https://github.com/Azure/mmlspark/blob/master/src/main/scala/com/microsoft/ml/spark/lightgbm/LightGBMBase.scala#L137
We even have a test with string data:
https://github.com/Azure/mmlspark/blob/master/src/test/scala/com/microsoft/ml/spark/lightgbm/split2/VerifyLightGBMRanker.scala#L104

Here is the latest build, in case it helps:
```
Maven Coordinates
com.microsoft.ml.spark:mmlspark_2.11:1.0.0-rc1-96-fce3c952-SNAPSHOT
Maven Resolver
https://mmlspark.azureedge.net/maven
```

**Comment by imatiach-msft** [comment]
Also, to clear up any confusion, the document points to the lightgbm repo, which is different from mmlspark.  mmlspark is relatively newer than lightgbm, especially lightgbm in mmlspark, and we are still trying to catch up with their API - note we only use the distributed version, whereas I think most users are more familiar with the single-node local python version.

**Comment by victorconan** [comment]
Thanks! It is resolved with `com.microsoft.ml.spark:mmlspark_2.11:1.0.0-rc1-86-05c25aad-SNAPSHOT`!

I will close this. Thanks!

**Comment by victorconan** [comment]
> Also, to clear up any confusion, the document (https://lightgbm.readthedocs.io/en/latest/Parameters.html#core-parameters) points to the lightgbm repo, which is different from mmlspark. mmlspark is relatively newer than lightgbm, especially lightgbm in mmlspark, and we are still trying to catch up with their API - note we only use the distributed version and wrap it in a scala/pyspark/sparklyr API, whereas I think most users are more familiar with the single-node local python version. You probably didn't have any issues with using string query column in the python version.

Yea, I understand the difference between lightgbm and mmlspark's lightgbm. It's just that the documentation of mmlspark-lightgbm doesnt provide much information (e.g. what are the available values for certain inputs). So I've always used lightgbm's documentation as reference. I guess probably majority of information is similar?

**Comment by imatiach-msft** [comment]
@victorconan that's true, mmlspark has much worse documentation, it can definitely be improved much more.
