### ISSUE TITLE
Py4JJavaError: An error occurred while calling None.com.microsoft.ml.spark.lightgbm.LightGBMClassifier. : java.lang.NoClassDefFoundError: org/apache/spark/ml/util/MLWritable$class

### ISSUE THREAD

**Issue by MrWangg1992** [Azure/mmlspark#891]
on amazon linux ami

>>> from mmlspark.lightgbm.LightGBMClassifier import LightGBMClassifier
>>> LightGBMClassifier()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/hadoop/.local/lib/python3.6/site-packages/pyspark/__init__.py", line 110, in wrapper
    return func(self, **kwargs)
  File "/mnt/tmp/spark-cf61bf0e-de1a-45f1-bb6b-de0b5c525c62/userFiles-1decae17-087a-460d-9e48-e4ee111eb2a9/com.microsoft.ml.spark_mmlspark_2.11-1.0.0-rc1.jar/mmlspark/lightgbm/_LightGBMClassifier.py", line 66, in __init__
  File "/home/hadoop/.local/lib/python3.6/site-packages/pyspark/ml/wrapper.py", line 69, in _new_java_obj
    return java_obj(*java_args)
  File "/home/hadoop/.local/lib/python3.6/site-packages/py4j/java_gateway.py", line 1569, in __call__
    answer, self._gateway_client, None, self._fqn)
  File "/home/hadoop/.local/lib/python3.6/site-packages/pyspark/sql/utils.py", line 131, in deco
    return f(*a, **kw)
  File "/home/hadoop/.local/lib/python3.6/site-packages/py4j/protocol.py", line 328, in get_return_value
    format(target_id, ".", name), value)
py4j.protocol.Py4JJavaError: An error occurred while calling None.com.microsoft.ml.spark.lightgbm.LightGBMClassifier.
: java.lang.NoClassDefFoundError: org/apache/spark/ml/util/MLWritable$class
        at com.microsoft.ml.spark.lightgbm.LightGBMClassifier.<init>(LightGBMClassifier.scala:27)
        at com.microsoft.ml.spark.lightgbm.LightGBMClassifier.<init>(LightGBMClassifier.scala:29)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
        at py4j.reflection.MethodInvoker.invoke(MethodInvoker.java:247)
        at py4j.reflection.ReflectionEngine.invoke(ReflectionEngine.java:357)
        at py4j.Gateway.invoke(Gateway.java:238)
        at py4j.commands.ConstructorCommand.invokeConstructor(ConstructorCommand.java:80)
        at py4j.commands.ConstructorCommand.execute(ConstructorCommand.java:69)
        at py4j.GatewayConnection.run(GatewayConnection.java:238)
        at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.ClassNotFoundException: org.apache.spark.ml.util.MLWritable$class
        at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:419)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:352)
        ... 13 more

**Comment by imatiach-msft** [comment]
@MrWangg1992 sorry about the trouble you are having, I'm not sure what might be causing this error.  Maybe it is due to an older or newer version of spark?  What version of spark are you running?  Or perhaps it is some cluster configuration issue.  Are you able to import other spark classes that use MLWritable?

Just noticed this:
https://github.com/databricks/spark-deep-learning/issues/194
The post suggests it might be a scala version issue.  I think we only support 2.11, can you try switching to scala 2.11?

**Comment by victor-sobreira** [comment]
I've lost too much time trying to get MMLSpark to work and I was close to giving up (even considering I really need to get it working). 

I've tried in different OS (Ubuntu 16.04 and 20.04), java versions (8 and 11), Scala Versions (2.13, 2.11, ...), environment variables settings, and the already posted issues did not helped.

I got it working using Pyspark 3.0.0 on Jupyter Notebook installed via Miniconda, Spark 2.4.0 (with Scala 2.11.12), Java 1.8.0, Python 3.7.9. It seems no matter what Scala version you try to install, Spark uses the version from the specific release (and I lost to much time until I figure out it).

Some more tips... Set variables on .bashrc:

`export JAVA_HOME=<PATH TO JAVA INSTALL>`
`export SPARK_HOME=<PATH TO SPARK INSTALL>`
`export PATH=$JAVA_HOME/bin:$SPARK_HOME/bin:$PATH`
`export PYSPARK_DRIVER_PYTHON=jupyter`
`export PYSPARK_DRIVER_PYTHON_OPTS='notebook'`

Jupyter/Pyspark starting command:
`pyspark --packages com.microsoft.ml.spark:mmlspark_2.11:1.0.0-rc1 --repositories=https://mmlspark.azureedge.net/maven`

I suppose you should work better on the compatibility of this library for the latest Spark versions. It is very frustating to try and error until we get a working configuration.

**Comment by hanan-vian** [comment]
+1

**Comment by saikiranvadhi** [comment]
Not able to use mmlspark lightgbm on Spark 3 cluster due to this error. @imatiach-msft any timeline for supporting Spark 3.

**Comment by invkrh** [comment]
Same issue here. Any updates on this? Downgrading spark is not an option in my case. 
@imatiach-msft

**Comment by orestiskaitezidis** [comment]
Hi @imatiach-msft any update on this? Thank you for your time!

**Comment by imatiach-msft** [comment]
hi @orestiskaitezidis we now support scala 2.12 and spark 3.0 on latest master, you can use any of the latest PR builds

**Comment by imatiach-msft** [comment]
I think this might be a good commit:
https://github.com/Azure/mmlspark/commit/cd79ecda47bacec8acfa6babf6e585240e617ad0
the build is:
MMLSpark Build and Release Information
Maven Coordinates
com.microsoft.ml.spark:mmlspark_2.12:1.0.0-rc3-49-659b7743-SNAPSHOT
Maven Resolver
https://mmlspark.azureedge.net/maven

you can also try an even newer commit:
https://github.com/Azure/mmlspark/commit/bc9e81ef2cf3fe5b0a1a1a586ace925fa1270d1f
MMLSpark Build and Release Information
Maven Coordinates
com.microsoft.ml.spark:mmlspark_2.12:1.0.0-rc3-54-bc9e81ef-SNAPSHOT
Maven Resolver
https://mmlspark.azureedge.net/maven

There's some issue I am looking into right now though, not related to lightgbm but TrainClassifier returning best model, so I'm not sure if you want to get the very latest commit yet on master.

**Comment by orestiskaitezidis** [comment]
@imatiach-msft Thank you for the information. I am using spark 3.1.1 should I downgrade? I am using the build 

spark = pyspark.sql.SparkSession.builder.appName("MyApp") \
            .config("spark.jars.packages", "com.microsoft.ml.spark:mmlspark_2.11:1.0.0-rc3") \
            .config("spark.jars.repositories", "https://mmlspark.azureedge.net/maven") \
            .getOrCreate()

Ok thank you, I will try the above suggestion.

**Comment by imatiach-msft** [comment]
yes the rc3 release still doesn't support spark 3.0 or scala 2.12 yet
the new releases actually support both 2.12 and 2.11, they have both artifacts generated as far as I understand, @mhamilton723, owner of mmlspark, might have more info.
Are you able to find the build artifacts from PRs?  I'm not sure if the devops is public.  We used to actually publish the build artifact URLs on every PR build, not sure why that broke at some point (or if there is something new I missed).

**Comment by orestiskaitezidis** [comment]
@imatiach-msft It seems to be working now with the latest PR build that you shared. Thank you so much for the quick turnaround.

**Comment by alenma04** [comment]
hi All,
please find below colab link to install mmlspark in google colab.
https://colab.research.google.com/drive/1Fh91i442XsiFmxgFj0wZGyyFb9JxF-a9?usp=sharing

**Comment by AndresUr** [comment]
> Creo que este podría ser un buen compromiso: [cd79ecd](https://github.com/microsoft/SynapseML/commit/cd79ecda47bacec8acfa6babf6e585240e617ad0) la compilación es: MMLSpark Compilación e información de lanzamiento Maven Coordinates com.microsoft.ml.spark:mmlspark_2.12:1.0.0-rc3-49-659b7743-SNAPSHOT Maven Resolver [https:// mmlspark.azureedge.net/maven](https://mmlspark.azureedge.net/maven)
> 
> también puede probar una confirmación aún más nueva: [bc9e81e](https://github.com/microsoft/SynapseML/commit/bc9e81ef2cf3fe5b0a1a1a586ace925fa1270d1f) MMLSpark Información de compilación y publicación Maven Coordinates com.microsoft.ml.spark:mmlspark_2.12:1.0.0-rc3-54-bc9e81ef-SNAPSHOT Maven Resolver [https://mmlspark.azureedge. red/experto](https://mmlspark.azureedge.net/maven)
> 
> Sin embargo, hay un problema que estoy investigando en este momento, no relacionado con lightgbm pero TrainClassifier devuelve el mejor modelo, por lo que no estoy seguro de si desea obtener el último compromiso aún en el maestro.



> Creo que este podría ser un buen compromiso: [cd79ecd](https://github.com/microsoft/SynapseML/commit/cd79ecda47bacec8acfa6babf6e585240e617ad0) la compilación es: MMLSpark Compilación e información de lanzamiento Maven Coordinates com.microsoft.ml.spark:mmlspark_2.12:1.0.0-rc3-49-659b7743-SNAPSHOT Maven Resolver [https:// mmlspark.azureedge.net/maven](https://mmlspark.azureedge.net/maven)
> 
> también puede probar una confirmación aún más nueva: [bc9e81e](https://github.com/microsoft/SynapseML/commit/bc9e81ef2cf3fe5b0a1a1a586ace925fa1270d1f) MMLSpark Información de compilación y publicación Maven Coordinates com.microsoft.ml.spark:mmlspark_2.12:1.0.0-rc3-54-bc9e81ef-SNAPSHOT Maven Resolver [https://mmlspark.azureedge. red/experto](https://mmlspark.azureedge.net/maven)
> 
> Sin embargo, hay un problema que estoy investigando en este momento, no relacionado con lightgbm pero TrainClassifier devuelve el mejor modelo, por lo que no estoy seguro de si desea obtener el último compromiso aún en el maestro.

-----------------------------------------------------------------------------------------------------------------------------------------
-----------------------------------------------------------------------------------------------------------------------------------------

thanks master with the version de spark 3.0.1 and scala 2.12 (DBR 7.3 LTS)  and  with MMLSpark Compilación e información de lanzamiento
Maven Coordinates
com.microsoft.ml.spark:mmlspark_2.12:1.0.0-rc3-49-659b7743-SNAPSHOT
Maven Resolver
[https:// mmlspark.azureedge.net/maven](https://mmlspark.azureedge.net/maven)

I can resolve my problems, excelent thanks bro !!

**Comment by ranadeepsingh** [comment]
This issue was resolved when SynapseML added native support for Spark 3.x and Scala 2.12 (starting with the v1.0.0 release). The NoClassDefFoundError: org/apache/spark/ml/util/MLWritable was caused by using legacy Scala 2.11 artifacts on a Spark 3.x cluster. All current published releases (including v1.1.3) target Scala 2.12 and Spark 3.x natively.
