### ISSUE TITLE
LightGBM: Launch container failed when predicting with spark 2.3 scala 2.11

### ISSUE THREAD

**Issue by ZixinChen0520** [Azure/mmlspark#893]
**Describe the bug**
We trained a model with LightGBM and tried to make prediction on about 500 Million data. The prediction process always has "Launch Container failed" Error and finally it will fail:
```
[WARN ] dispatcher-event-loop-31 [org.apache.spark.scheduler.cluster.YarnSchedulerBackend$YarnSchedulerEndpoint:69]  Requesting driver to remove executor 23 for reason Container from a bad node: container_e446_1593685215274_1605926_05_210384 on host: n196-083-020.byted.org. Exit status: 134. Diagnostics: Exit Code: 134
Exception from container-launch.
Container id: container_e446_1593685215274_1605926_05_210384
Exit code: 134
Stack trace: org.apache.hadoop.yarn.server.nodemanager.containermanager.runtime.ContainerExecutionException: Launch container failed: 
	at org.apache.hadoop.yarn.server.nodemanager.containermanager.linux.runtime.DockerLinuxContainerRuntime.launchContainer(DockerLinuxContainerRuntime.java:635)
	at org.apache.hadoop.yarn.server.nodemanager.containermanager.linux.runtime.DelegatingLinuxContainerRuntime.launchContainer(DelegatingLinuxContainerRuntime.java:91)
	at org.apache.hadoop.yarn.server.nodemanager.LinuxContainerExecutor.launchContainer(LinuxContainerExecutor.java:474)
	at org.apache.hadoop.yarn.server.nodemanager.containermanager.launcher.ContainerLaunch.call(ContainerLaunch.java:459)
	at org.apache.hadoop.yarn.server.nodemanager.containermanager.launcher.ContainerLaunch.call(ContainerLaunch.java:96)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:748)
```
When we looked into the executors, we got core dump messages like:
![image](https://user-images.githubusercontent.com/50555711/87500944-717f9b80-c690-11ea-9253-ecd01841f2a7.png)

**To Reproduce**
spark settings:
spark.driver.cores=12
driver-memory=24G
executor-cores=4
executor-memory=32G
spark.dynamicAllocation.maxExecutors=1000
 - Spark Version 2.3 & 3.0
 - Scala Version 2.11 & 2.12

We have tried on spark 2.3, scala 2.11 and  spark 3.0, scala 2.12. Make prediction and then write the result to parquet can always reproduce this problem. 
We also found that if we just print the result instead of writing it to parquet, the job could success. It seems that an executor can't do more tasks after it finished one. (not sure about that, just suspect)

please take a look at that 
Thanks!

**Comment by imatiach-msft** [comment]
@ZixinChen0520 any way to reproduce this failure?  I'm not sure I can reproduce it from the given description, sorry.  I haven't seen this error before, but it looks like it is failing in the native code somewhere.

**Comment by ranadeepsingh** [comment]
This issue was filed against the legacy Spark 2.3 and Scala 2.11 runtime environment. Support for Spark 2.x and Scala 2.11 was intentionally removed from SynapseML in the v1.0.0 rewrite, and all published releases including v1.1.3 target Spark 3.x and Scala 2.12. As the reported platform runtime is no longer supported or part of SynapseML, we are closing this issue.
