### ISSUE TITLE
java.lang.OutOfMemoryError: GC overhead limit exceeded

### ISSUE THREAD

**Issue by whiteneverdie** [Azure/mmlspark#894]
Hi, everybody!

I have a hadoop cluster on yarn.  
There are about 
Memory Total: 8.98 TB
VCores Total: 1216

my app has followinng config (python api):

spark = (
    pyspark.sql.SparkSession
    .builder
    .master("yarn") ## local[8]
    .appName("test_mmlspark_lgbm2")
    .config("spark.driver.memory","70G")
    .config("spark.executor.memory","70G")
    .config("spark.executor.cores","20")
    .config("spark.executor.instances","5")
    .config("spark.driver.maxResultSize", '128g')
    .config("spark.memory.offHeap.enabled", 'true')
    .config("spark.memory.offHeap.size", '30g')
    .enableHiveSupport()
    .getOrCreate()
)

1 Node has about 32 cores and ~96Gb Ram

Data has about 1.5M rows and ~3000 Cols (double type)

I am doing simple pipe

data_train = spark.sql(query)

assembler = VectorAssembler(inputCols=main_cols, outputCol='features')
estimator = LightGBMClassifier(
    learningRate=0.1, 
     numIterations=500, 
     ## maxDepth = 10,
     metric = "binary_logloss",
     earlyStoppingRound=10, 
     isUnbalance=True, 
     validationIndicatorCol="valInd", 
     verbosity=1,
     parallelism="voting_parallel",
)
pipeline = Pipeline(stages=[assembler, estimator])
model = pipeline.fit(data_train)

with limit on data (100000 rows) all works fine

but on whole dataset i have a problem.

Traceback (most recent call last):
  File "test_pyspark_mmlspark_lgbm_1.py", line 109, in <module>
    model = pipeline.fit(data_train)
  File "/hadoop11/yarn/local/usercache/airflow/appcache/application_1588099960229_28117/container_e10_1588099960229_28117_03_000001/pyspark.zip/pyspark/ml/base.py", line 132, in fit
  File "/hadoop11/yarn/local/usercache/airflow/appcache/application_1588099960229_28117/container_e10_1588099960229_28117_03_000001/pyspark.zip/pyspark/ml/pipeline.py", line 109, in _fit
  File "/hadoop11/yarn/local/usercache/airflow/appcache/application_1588099960229_28117/container_e10_1588099960229_28117_03_000001/pyspark.zip/pyspark/ml/base.py", line 132, in fit
  File "/hadoop11/yarn/local/usercache/airflow/appcache/application_1588099960229_28117/container_e10_1588099960229_28117_03_000001/pyspark.zip/pyspark/ml/wrapper.py", line 295, in _fit
  File "/hadoop11/yarn/local/usercache/airflow/appcache/application_1588099960229_28117/container_e10_1588099960229_28117_03_000001/pyspark.zip/pyspark/ml/wrapper.py", line 292, in _fit_java
  File "/hadoop11/yarn/local/usercache/airflow/appcache/application_1588099960229_28117/container_e10_1588099960229_28117_03_000001/py4j-0.10.7-src.zip/py4j/java_gateway.py", line 1257, in __call__
  File "/hadoop11/yarn/local/usercache/airflow/appcache/application_1588099960229_28117/container_e10_1588099960229_28117_03_000001/pyspark.zip/pyspark/sql/utils.py", line 63, in deco
  File "/hadoop11/yarn/local/usercache/airflow/appcache/application_1588099960229_28117/container_e10_1588099960229_28117_03_000001/py4j-0.10.7-src.zip/py4j/protocol.py", line 328, in get_return_value
py4j.protocol.Py4JJavaError: An error occurred while calling o12112.fit.
: java.lang.OutOfMemoryError: GC overhead limit exceeded
	at org.apache.spark.ml.linalg.SparseVector$$anonfun$1.apply$mcVI$sp(Vectors.scala:580)
	at org.apache.spark.ml.linalg.SparseVector$$anonfun$1.apply(Vectors.scala:579)
	at org.apache.spark.ml.linalg.SparseVector$$anonfun$1.apply(Vectors.scala:579)
	at scala.collection.IndexedSeqOptimized$class.foreach(IndexedSeqOptimized.scala:33)
	at scala.collection.mutable.ArrayOps$ofInt.foreach(ArrayOps.scala:234)
	at org.apache.spark.ml.linalg.SparseVector.<init>(Vectors.scala:579)
	at org.apache.spark.ml.linalg.VectorUDT.deserialize(VectorUDT.scala:62)
	at org.apache.spark.sql.catalyst.expressions.GeneratedClass$SpecificSafeProjection.createExternalRow_0_0$(Unknown Source)
	at org.apache.spark.sql.catalyst.expressions.GeneratedClass$SpecificSafeProjection.apply(Unknown Source)
	at org.apache.spark.sql.Dataset$$anonfun$org$apache$spark$sql$Dataset$$collectFromPlan$1.apply(Dataset.scala:3392)
	at org.apache.spark.sql.Dataset$$anonfun$org$apache$spark$sql$Dataset$$collectFromPlan$1.apply(Dataset.scala:3389)
	at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:234)
	at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:234)
	at scala.collection.IndexedSeqOptimized$class.foreach(IndexedSeqOptimized.scala:33)
	at scala.collection.mutable.ArrayOps$ofRef.foreach(ArrayOps.scala:186)
	at scala.collection.TraversableLike$class.map(TraversableLike.scala:234)
	at scala.collection.mutable.ArrayOps$ofRef.map(ArrayOps.scala:186)
	at org.apache.spark.sql.Dataset.org$apache$spark$sql$Dataset$$collectFromPlan(Dataset.scala:3389)
	at org.apache.spark.sql.Dataset$$anonfun$collect$1.apply(Dataset.scala:2788)
	at org.apache.spark.sql.Dataset$$anonfun$collect$1.apply(Dataset.scala:2788)
	at org.apache.spark.sql.Dataset$$anonfun$52.apply(Dataset.scala:3370)
	at org.apache.spark.sql.execution.SQLExecution$$anonfun$withNewExecutionId$1.apply(SQLExecution.scala:80)
	at org.apache.spark.sql.execution.SQLExecution$.withSQLConfPropagated(SQLExecution.scala:127)
	at org.apache.spark.sql.execution.SQLExecution$.withNewExecutionId(SQLExecution.scala:75)
	at org.apache.spark.sql.Dataset.withAction(Dataset.scala:3369)
	at org.apache.spark.sql.Dataset.collect(Dataset.scala:2788)
	at com.microsoft.ml.spark.lightgbm.LightGBMBase$class.innerTrain(LightGBMBase.scala:140)
	at com.microsoft.ml.spark.lightgbm.LightGBMClassifier.innerTrain(LightGBMClassifier.scala:26)
	at com.microsoft.ml.spark.lightgbm.LightGBMBase$class.train(LightGBMBase.scala:40)
	at com.microsoft.ml.spark.lightgbm.LightGBMClassifier.train(LightGBMClassifier.scala:26)
	at com.microsoft.ml.spark.lightgbm.LightGBMClassifier.train(LightGBMClassifier.scala:26)
	at org.apache.spark.ml.Predictor.fit(Predictor.scala:118)

How can i tune or fix it?

What kind of problem is it?
- spark config
- old version of cluster
- python compatibility
- voodoo magic was here
- somethong  else

**Comment by whiteneverdie** [comment]
Pipeline using standart  GBTClassifier has copleted without any GC or OOM error

**Comment by imatiach-msft** [comment]
@whiteneverdie what version of mmlspark are you using?

**Comment by imatiach-msft** [comment]
Can you use the version from master, this is one of the latest builds:

Maven Coordinates
com.microsoft.ml.spark:mmlspark_2.11:1.0.0-rc1-96-fce3c952-SNAPSHOT
Maven Resolver
https://mmlspark.azureedge.net/maven

**Comment by imatiach-msft** [comment]
1.5M rows * 3k cols * 8 bytes per value ~= 36 GB.  LightGBM in mmlspark currently uses about 3x memory, but it should be possible to decrease that to 2x (one native representation and one pyspark dataframe).  I'm wondering if somehow only one task gets created and it runs out of memory?  In the reduce stage, do you see 5 tasks created?

**Comment by whiteneverdie** [comment]
> Can you use the version from master, this is one of the latest builds:
> 
> Maven Coordinates
> com.microsoft.ml.spark:mmlspark_2.11:1.0.0-rc1-96-fce3c952-SNAPSHOT
> Maven Resolver
> https://mmlspark.azureedge.net/maven

This is not so easy. We have Hadoop build under old Redhat version and for running lightgbm our dev-team re-compiled 2.11:1.0.0-rc1 version of lightgbm (not last snapshot)

**Comment by imatiach-msft** [comment]
@whiteneverdie interesting, I see SparseVector in the stack trace, is the data sparse?

: java.lang.OutOfMemoryError: GC overhead limit exceeded
at org.apache.spark.ml.linalg.SparseVector$$anonfun$1.apply$mcVI$sp(Vectors.scala:580)

Maybe one of the first rows is sparse causing the rest of the data to be represented in sparse format?  LightGBM can't handle mixed sparse/dense rows.

**Comment by whiteneverdie** [comment]
> Maybe one of the first rows is sparse causing the rest of the data to be represented in sparse format? LightGBM can't handle mixed sparse/dense rows.

I  havn't done any special forced transformation to Sparse

**Comment by imatiach-msft** [comment]
@whiteneverdie I think vector assembler automatically represents some of the rows as sparse if there are a lot of zeros.  My guess is only a few rows are sparse, and just by chance the first row in the pyspark dataframe is.  We don't have very intelligent logic to go through the dataset to determine what the optimal transformation should be, so maybe I should add a parameter to allow the user to specify whether data is sparse or dense.  I'm not sure if this is the issue though, since using sparse vector should only double memory usage.

**Comment by whiteneverdie** [comment]
just now after that stage i have a crash
![image](https://user-images.githubusercontent.com/42961726/87687283-3a8faf80-c78e-11ea-80bd-c8ea9c8470fb.png)

**Comment by whiteneverdie** [comment]
About vectors you maybe right
https://stackoverflow.com/questions/51317473/make-vectorassembler-always-choose-densevector

**Comment by imatiach-msft** [comment]
yes we just get the head row right now and convert the rest of the rows to sparse or dense:

https://github.com/Azure/mmlspark/blob/f07e5584459e909223a470e6d2e11135b292f3ea/src/main/scala/com/microsoft/ml/spark/lightgbm/TrainUtils.scala#L34

for mixed sparse/dense rows this can be a problem, I need to either add a parameter to allow user to specify sparse/dense or scan the first X rows instead of just the head row

**Comment by whiteneverdie** [comment]
I have a good news 
after changing vector type to sparse  

Traceback (most recent call last):
  File "test_pyspark_mmlspark_lgbm_1.py", line 132, in <module>
    model = estimator.fit(data_train1)
  File "/hadoop1/yarn/local/usercache/airflow/appcache/application_1588099960229_28143/container_e10_1588099960229_28143_01_000001/pyspark.zip/pyspark/ml/base.py", line 132, in fit
  File "/hadoop1/yarn/local/usercache/airflow/appcache/application_1588099960229_28143/container_e10_1588099960229_28143_01_000001/pyspark.zip/pyspark/ml/wrapper.py", line 295, in _fit
  File "/hadoop1/yarn/local/usercache/airflow/appcache/application_1588099960229_28143/container_e10_1588099960229_28143_01_000001/pyspark.zip/pyspark/ml/wrapper.py", line 292, in _fit_java
  File "/hadoop1/yarn/local/usercache/airflow/appcache/application_1588099960229_28143/container_e10_1588099960229_28143_01_000001/py4j-0.10.7-src.zip/py4j/java_gateway.py", line 1257, in __call__
  File "/hadoop1/yarn/local/usercache/airflow/appcache/application_1588099960229_28143/container_e10_1588099960229_28143_01_000001/pyspark.zip/pyspark/sql/utils.py", line 63, in deco
  File "/hadoop1/yarn/local/usercache/airflow/appcache/application_1588099960229_28143/container_e10_1588099960229_28143_01_000001/py4j-0.10.7-src.zip/py4j/protocol.py", line 328, in get_return_value
py4j.protocol.Py4JJavaError: An error occurred while calling o12188.fit.
: java.lang.OutOfMemoryError: Java heap space
	at org.apache.spark.sql.execution.SparkPlan$$anon$1.next(SparkPlan.scala:282)
	at org.apache.spark.sql.execution.SparkPlan$$anon$1.next(SparkPlan.scala:278)
	at scala.collection.Iterator$class.foreach(Iterator.scala:891)
	at org.apache.spark.sql.execution.SparkPlan$$anon$1.foreach(SparkPlan.scala:278)
	at org.apache.spark.sql.execution.SparkPlan$$anonfun$executeCollect$1.apply(SparkPlan.scala:300)
	at org.apache.spark.sql.execution.SparkPlan$$anonfun$executeCollect$1.apply(SparkPlan.scala:299)
	at scala.collection.IndexedSeqOptimized$class.foreach(IndexedSeqOptimized.scala:33)
	at scala.collection.mutable.ArrayOps$ofRef.foreach(ArrayOps.scala:186)
	at org.apache.spark.sql.execution.SparkPlan.executeCollect(SparkPlan.scala:299)
	at org.apache.spark.sql.Dataset.org$apache$spark$sql$Dataset$$collectFromPlan(Dataset.scala:3389)
	at org.apache.spark.sql.Dataset$$anonfun$collect$1.apply(Dataset.scala:2788)
	at org.apache.spark.sql.Dataset$$anonfun$collect$1.apply(Dataset.scala:2788)
	at org.apache.spark.sql.Dataset$$anonfun$52.apply(Dataset.scala:3370)
	at org.apache.spark.sql.execution.SQLExecution$$anonfun$withNewExecutionId$1.apply(SQLExecution.scala:80)
	at org.apache.spark.sql.execution.SQLExecution$.withSQLConfPropagated(SQLExecution.scala:127)
	at org.apache.spark.sql.execution.SQLExecution$.withNewExecutionId(SQLExecution.scala:75)
	at org.apache.spark.sql.Dataset.withAction(Dataset.scala:3369)
	at org.apache.spark.sql.Dataset.collect(Dataset.scala:2788)
	at com.microsoft.ml.spark.lightgbm.LightGBMBase$class.innerTrain(LightGBMBase.scala:140)
	at com.microsoft.ml.spark.lightgbm.LightGBMClassifier.innerTrain(LightGBMClassifier.scala:26)
	at com.microsoft.ml.spark.lightgbm.LightGBMBase$class.train(LightGBMBase.scala:40)
	at com.microsoft.ml.spark.lightgbm.LightGBMClassifier.train(LightGBMClassifier.scala:26)
	at com.microsoft.ml.spark.lightgbm.LightGBMClassifier.train(LightGBMClassifier.scala:26)
	at org.apache.spark.ml.Predictor.fit(Predictor.scala:118)
	at org.apache.spark.ml.Predictor.fit(Predictor.scala:82)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at py4j.reflection.MethodInvoker.invoke(MethodInvoker.java:244)
	at py4j.reflection.ReflectionEngine.invoke(ReflectionEngine.java:357)
	at py4j.Gateway.invoke(Gateway.java:282)

**Comment by imatiach-msft** [comment]
@whiteneverdie you mean that you changed it to dense instead of sparse, is that correct?  But you are still seeing OOM errors?  My worry was that your data is actually mostly dense and not sparse, but sparse representation makes it 2x larger memory usage.

**Comment by whiteneverdie** [comment]
that is correct, i hope, yea, sparse to dense

but my data mostly sparse then dense 
sparsity is about ~70-80%

**Comment by imatiach-msft** [comment]
oh, sorry, I didn't realize your data is mostly sparse, I thought it was dense.  That will change the memory calculations then.  How many nonzeros are there per row for the sparse data (on average or based on just a quick look at a few rows)?

**Comment by imatiach-msft** [comment]
also, are you sure you are running multiple tasks in the reduce stage of LightGBM (when I am guessing it runs out of memory).  LightGBM coalesces the data, I'm wondering if it is not coalescing correctly.  Might you be able to post some of the logs from the driver?  Eg in particular I am interested in the number of workers in NetworkInit.

**Comment by whiteneverdie** [comment]
@imatiach-msft  one moment please

**Comment by whiteneverdie** [comment]
@imatiach-msft 
non-zeros less then 50% per row, in averange


20/07/16 20:10:24 INFO YarnAllocator: Will request 5 executor container(s), each with 20 core(s) and 78848 MB memory (including 7168 MB of overhead)
20/07/16 20:10:24 INFO YarnSchedulerBackend$YarnSchedulerEndpoint: ApplicationMaster registered as NettyRpcEndpointRef(spark://YarnAM@******:2562)
20/07/16 20:10:24 INFO YarnAllocator: Submitted 5 unlocalized container requests.
20/07/16 20:10:24 INFO ApplicationMaster: Started progress reporter thread with (heartbeat : 3000, initial allocation : 200) intervals

**Comment by whiteneverdie** [comment]
but
collect at LightGBMBase.scala:140 
runs only on one executor

**Comment by imatiach-msft** [comment]
@whiteneverdie if you are running only one task you might have a similar issue to this one:
https://github.com/Azure/mmlspark/issues/879
see this comment:
https://github.com/Azure/mmlspark/issues/879#issuecomment-648662334
What is spark.task.cpus configured to? Can you post any of the logs?  Specifically the "ClusterUtils calculated num cores..." would be really useful.

**Comment by imatiach-msft** [comment]
Also, what kind of cluster are you running?  It looks like you are using yarn?  So I assume this is not a Databricks cluster.

**Comment by whiteneverdie** [comment]
>> Also, what kind of cluster are you running? It looks like you are using yarn? So I assume this is not a Databricks cluster.
thats right

**Comment by whiteneverdie** [comment]
[Untitled.log](https://github.com/Azure/mmlspark/files/4933221/Untitled.log)

**Comment by imatiach-msft** [comment]
It does look like there is only one task created.
```
20/07/16 20:37:55 INFO LightGBMClassifier: driver expecting 1 connections...
20/07/16 20:37:55 INFO LightGBMClassifier: driver accepting a new connection...
20/07/16 20:37:55 INFO LightGBMClassifier: driver waiting for connections on host: 10.42.100.148 and port: 12828
```
Also I see this:
```
20/07/16 20:37:50 INFO LightGBMClassifier: ClusterUtils did not detect spark.task.cpus config set, using default 1 instead
20/07/16 20:37:50 INFO LightGBMClassifier: ClusterUtils calculated num cores per executor as 20 from 20 cores and 1 task CPUs
20/07/16 20:37:50 INFO LightGBMClassifier: Retrieving executors...
20/07/16 20:37:50 INFO LightGBMClassifier: Retrieved num executors 5 with num cores per executor 20
```
Will need to look through the code to figure out why there is only one task created, but that seems to be the problem.

**Comment by whiteneverdie** [comment]
@imatiach-msft 
there are last chance 
meet.google.com/icc-cxtc-kmk

**Comment by whiteneverdie** [comment]
![image](https://user-images.githubusercontent.com/42961726/87705890-463ba000-c7a7-11ea-9d2b-d8fa0f0ec694.png)

**Comment by imatiach-msft** [comment]
@whiteneverdie maybe we can meet at 3:30pm EST?  I have a meeting in 1 minute at 2pm

**Comment by whiteneverdie** [comment]
@imatiach-msft  it is deal

**Comment by whiteneverdie** [comment]
@imatiach-msft Thank you so much for consulting and helping hand!

**Comment by whiteneverdie** [comment]
@imatiach-msft 
all works fine but without validationCol like lightgbm params

--using repartition
--forcing change to Dense Vector after Assembler 

thx

**Comment by ranadeepsingh** [comment]
This issue regarding driver GC overhead OOM errors was resolved following assistance from maintainers. The memory issue was caused by single-task partition bottlenecks on large datasets; repartitioning the input DataFrame and converting vectors to DenseVectors resolved the issue as confirmed by the reporter. We are closing this answered support issue.
