### ISSUE TITLE
Dataset set feature names call failed in LightGBM with error: Do not support non-ascii characters in feature name.

### ISSUE THREAD

**Issue by MarsXDM** [Azure/mmlspark#908]
**Describe the bug**
fit a lightgbm model , the following bug occured: Dataset set feature names call failed in LightGBM with error: Do not support non-ascii characters in feature name.

In fact , column names are:
['parent_id',
 'app_version',
 'channel',
 'operator',
 'os',
 'os_version',
 'ip',
 'register_channel',
 'active_date',
 'class_id',
 'register_date',
 'login_common_weekday_60d',
 'login_common_hour_30d',
 'love_rank_last_date',
 'subscribe_last_date',
 'perfermance_last_date',
 'potential_last_date',
 'live_last_date',
 'light_last_date',
 'broadcast_last_date',
 'supply_last_date',
 'dow_str',
 'is_weekend_str',
 'family_role',
 'active_dates_num',
 'active_codes_num',
 'active_click',
 'love_rank_dates',
 'love_rank_click',
 'love_rank_window_end_dates',
 'subscribe_dates',
 'subscribe_click',
 'subscribe_window_end_dates',
 'perfermance_dates',
 'perfermance_click',
 'perfermance_window_end_dates',
 'potential_dates',
 'potential_click',
 'potential_window_end_dates',
 'live_dates',
 'live_click',
 'live_window_end_dates',
 'light_dates',
 'light_click',
 'light_window_end_dates',
 'broadcast_dates',
 'broadcast_click',
 'broadcast_window_end_dates',
 'supply_dates',
 'supply_click',
 'supply_window_end_dates',
 'label_1']

**Info (please complete the following information):**
 - MMLSpark Version: v0.0.11111111
 - pyspark Version: 2.4.5
 - Spark Version: 2.1.0
 - Spark Platform: Cloudera

** Stacktrace**
```
java.lang.Exception: Dataset set feature names call failed in LightGBM with error: Do not support non-ascii characters in feature name.
	at com.microsoft.ml.spark.lightgbm.LightGBMUtils$.validate(LightGBMUtils.scala:31)
	at com.microsoft.ml.spark.lightgbm.LightGBMDataset$$anonfun$setFeatureNames$1.apply(LightGBMDataset.scala:94)
	at com.microsoft.ml.spark.lightgbm.LightGBMDataset$$anonfun$setFeatureNames$1.apply(LightGBMDataset.scala:92)
	at scala.Option.foreach(Option.scala:257)
	at com.microsoft.ml.spark.lightgbm.LightGBMDataset.setFeatureNames(LightGBMDataset.scala:92)
	at com.microsoft.ml.spark.lightgbm.LightGBMUtils$.generateSparseDataset(LightGBMUtils.scala:250)
	at com.microsoft.ml.spark.lightgbm.TrainUtils$.generateDataset(TrainUtils.scala:51)
	at com.microsoft.ml.spark.lightgbm.TrainUtils$.translate(TrainUtils.scala:233)
	at com.microsoft.ml.spark.lightgbm.TrainUtils$.trainLightGBM(TrainUtils.scala:385)
	at com.microsoft.ml.spark.lightgbm.LightGBMBase$$anonfun$6.apply(LightGBMBase.scala:145)
	at com.microsoft.ml.spark.lightgbm.LightGBMBase$$anonfun$6.apply(LightGBMBase.scala:145)
	at org.apache.spark.sql.execution.MapPartitionsExec$$anonfun$5.apply(objects.scala:188)
	at org.apache.spark.sql.execution.MapPartitionsExec$$anonfun$5.apply(objects.scala:185)
	at org.apache.spark.rdd.RDD$$anonfun$mapPartitionsInternal$1$$anonfun$apply$24.apply(RDD.scala:858)
	at org.apache.spark.rdd.RDD$$anonfun$mapPartitionsInternal$1$$anonfun$apply$24.apply(RDD.scala:858)
	at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:52)
	at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:346)
	at org.apache.spark.rdd.RDD.iterator(RDD.scala:310)
	at org.apache.spark.sql.execution.SQLExecutionRDD.compute(SQLExecutionRDD.scala:55)
	at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:346)
	at org.apache.spark.rdd.RDD.iterator(RDD.scala:310)
	at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:52)
	at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:346)
	at org.apache.spark.rdd.RDD.iterator(RDD.scala:310)
	at org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:90)
	at org.apache.spark.scheduler.Task.run(Task.scala:123)
	at org.apache.spark.executor.Executor$TaskRunner$$anonfun$10.apply(Executor.scala:408)
	at org.apache.spark.util.Utils$.tryWithSafeFinally(Utils.scala:1360)
	at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:414)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

Driver stacktrace:
	at org.apache.spark.scheduler.DAGScheduler.org$apache$spark$scheduler$DAGScheduler$$failJobAndIndependentStages(DAGScheduler.scala:1891)
	at org.apache.spark.scheduler.DAGScheduler$$anonfun$abortStage$1.apply(DAGScheduler.scala:1879)
	at org.apache.spark.scheduler.DAGScheduler$$anonfun$abortStage$1.apply(DAGScheduler.scala:1878)
	at scala.collection.mutable.ResizableArray$class.foreach(ResizableArray.scala:59)
	at scala.collection.mutable.ArrayBuffer.foreach(ArrayBuffer.scala:48)
	at org.apache.spark.scheduler.DAGScheduler.abortStage(DAGScheduler.scala:1878)
	at org.apache.spark.scheduler.DAGScheduler$$anonfun$handleTaskSetFailed$1.apply(DAGScheduler.scala:927)
	at org.apache.spark.scheduler.DAGScheduler$$anonfun$handleTaskSetFailed$1.apply(DAGScheduler.scala:927)
	at scala.Option.foreach(Option.scala:257)
	at org.apache.spark.scheduler.DAGScheduler.handleTaskSetFailed(DAGScheduler.scala:927)
	at org.apache.spark.scheduler.DAGSchedulerEventProcessLoop.doOnReceive(DAGScheduler.scala:2112)
	at org.apache.spark.scheduler.DAGSchedulerEventProcessLoop.onReceive(DAGScheduler.scala:2061)
	at org.apache.spark.scheduler.DAGSchedulerEventProcessLoop.onReceive(DAGScheduler.scala:2050)
	at org.apache.spark.util.EventLoop$$anon$1.run(EventLoop.scala:49)
	at org.apache.spark.scheduler.DAGScheduler.runJob(DAGScheduler.scala:738)
	at org.apache.spark.SparkContext.runJob(SparkContext.scala:2061)
	at org.apache.spark.SparkContext.runJob(SparkContext.scala:2158)
	at org.apache.spark.rdd.RDD$$anonfun$reduce$1.apply(RDD.scala:1080)
	at org.apache.spark.rdd.RDDOperationScope$.withScope(RDDOperationScope.scala:151)
	at org.apache.spark.rdd.RDDOperationScope$.withScope(RDDOperationScope.scala:112)
	at org.apache.spark.rdd.RDD.withScope(RDD.scala:385)
	at org.apache.spark.rdd.RDD.reduce(RDD.scala:1062)
	at org.apache.spark.sql.Dataset$$anonfun$reduce$1.apply(Dataset.scala:1643)
	at org.apache.spark.sql.Dataset$$anonfun$withNewRDDExecutionId$1.apply(Dataset.scala:3355)
	at org.apache.spark.sql.execution.SQLExecution$$anonfun$withNewExecutionId$1.apply(SQLExecution.scala:80)
	at org.apache.spark.sql.execution.SQLExecution$.withSQLConfPropagated(SQLExecution.scala:127)
	at org.apache.spark.sql.execution.SQLExecution$.withNewExecutionId(SQLExecution.scala:75)
	at org.apache.spark.sql.Dataset.withNewRDDExecutionId(Dataset.scala:3351)
	at org.apache.spark.sql.Dataset.reduce(Dataset.scala:1642)
	at com.microsoft.ml.spark.lightgbm.LightGBMBase$class.innerTrain(LightGBMBase.scala:150)
	at com.microsoft.ml.spark.lightgbm.LightGBMClassifier.innerTrain(LightGBMClassifier.scala:26)
	at com.microsoft.ml.spark.lightgbm.LightGBMBase$class.train(LightGBMBase.scala:40)
	at com.microsoft.ml.spark.lightgbm.LightGBMClassifier.train(LightGBMClassifier.scala:26)
	at com.microsoft.ml.spark.lightgbm.LightGBMClassifier.train(LightGBMClassifier.scala:26)
	at org.apache.spark.ml.Predictor.fit(Predictor.scala:118)
	at org.apache.spark.ml.Predictor.fit(Predictor.scala:82)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at py4j.reflection.MethodInvoker.invoke(MethodInvoker.java:244)
	at py4j.reflection.ReflectionEngine.invoke(ReflectionEngine.java:357)
	at py4j.Gateway.invoke(Gateway.java:282)
	at py4j.commands.AbstractCommand.invokeMethod(AbstractCommand.java:132)
	at py4j.commands.CallCommand.execute(CallCommand.java:79)
	at py4j.GatewayConnection.run(GatewayConnection.java:238)
	at java.lang.Thread.run(Thread.java:748)```

Anyone can help ?

**Comment by imatiach-msft** [comment]
@MarsXDM I have a PR to improve the error message here:
https://github.com/Azure/mmlspark/pull/897
however, it looks like your columns don't have the invalid characters:
",:[]{}
Are those all of the column names?  Maybe there are other non-ascii characters in the feature names that I am missing?
You can always assign custom slot names via the setSlotNames() method in scala or slotNames parameter in pyspark.

**Comment by MarsXDM** [comment]
> @MarsXDM I have a PR to improve the error message here:
> #897
> however, it looks like your columns don't have the invalid characters:
> ",:[]{}
> Are those all of the column names? Maybe there are other non-ascii characters in the feature names that I am missing?
> You can always assign custom slot names via the setSlotNames() method in scala or slotNames parameter in pyspark.

I just print columns with df.columns to show it here

**Comment by imatiach-msft** [comment]
@MarsXDM 
```I just print columns with df.columns to show it here```
hmm, unfortunately I don't see those special characters there.  I would recommend trying to assign the custom slot names first (eg as integers in string form), and see if that fixes the issue.  If not, then more investigation might be required as to what is producing the error.  If assigning custom slot names fixes it, then we can try to narrow down which specific column name is causing the issue by changing them with a custom version.

**Comment by MarsXDM** [comment]
> @MarsXDM
> `I just print columns with df.columns to show it here`
> hmm, unfortunately I don't see those special characters there. I would recommend trying to assign the custom slot names first (eg as integers in string form), and see if that fixes the issue. If not, then more investigation might be required as to what is producing the error. If assigning custom slot names fixes it, then we can try to narrow down which specific column name is causing the issue by changing them with a custom version.

NUM_LEAVES = 32
NUM_ITERATIONS = 50
LEARNING_RATE = 0.1
FEATURE_FRACTION = 0.8
EARLY_STOPPING_ROUND = 10

lgb = LightGBMClassifier(
    labelCol="label_1",
    featuresCol="features",
    objective="binary",
    boostingType="gbdt",
    boostFromAverage=True,
    baggingSeed=42,
    numLeaves=NUM_LEAVES,
    numIterations=NUM_ITERATIONS,
    learningRate=LEARNING_RATE,
    featureFraction=FEATURE_FRACTION,
    earlyStoppingRound=EARLY_STOPPING_ROUND
)

feature_processor = VectorAssembler(inputCols=feature_cols, outputCol='features')
tmp = feature_processor.transform(train_set)
stages = [lgb]
pipelineModel = Pipeline(stages=stages)
model = pipelineModel.fit(tmp.select('features','label_1'))

cutdown columns but the bug still there

**Comment by imatiach-msft** [comment]
@MarsXDM the problem is with the metadata on the 'features' column after vector assembler.  I would recommend using slotNames or modifying the 'feature_cols' before this (and the corresponding column names on the dataset):
```feature_processor = VectorAssembler(inputCols=feature_cols, outputCol='features')```
Note I wouldn't expect this to do anything:
 model = pipelineModel.fit(tmp.select('features','label_1'))
since the slot names are already on the features column.

**Comment by MarsXDM** [comment]
> @MarsXDM the problem is with the metadata on the 'features' column after vector assembler. I would recommend using slotNames or modifying the 'feature_cols' before this (and the corresponding column names on the dataset):
> `feature_processor = VectorAssembler(inputCols=feature_cols, outputCol='features')`
> Note I wouldn't expect this to do anything:
> model = pipelineModel.fit(tmp.select('features','label_1'))
> since the slot names are already on the features column.

i'm so sorry i don't understand what 'slotNames' mean? and i try the feature engineering using vector assembler and FeatureHasher to create a new vector feature 'features',
# this using feature hasher
tmp = feature_processor.transform(train_set) 
tmp.select('features','label_1').show()

# this using vector assembler
tmp_va = feature_processor_va.transform(train_set_va)
tmp_va.select('features','label_1').show()

tmp and tmp_va is the same. but just tmp_va will throw the Error when execute 
stages = [lgb]
pipelineModel = Pipeline(stages=stages)
model = pipelineModel.fit(tmp_va.select('features','label_1'))

the feature name is the same tmp.select('features', 'label_1') and tmp_va.select('feature', 'label_1')

**Comment by imatiach-msft** [comment]
@MarsXDM 
When you create the 'features' column, you are using VectorAssembler.  VectorAssembler creates a vector column, and each individual value is what I call a slot.  There is metadata on each of those slots (not a column like 'feature' or 'label_1') and one of values on the metadata is the slot name.  The original feature names on the dataset prior to creating the vector column will be the slot names.  The best way to fix this is to change the column names that you passed to vector assembler or set the slot names as I wrote above.

**Comment by imatiach-msft** [comment]
Maybe the code here might help:
https://github.com/Azure/mmlspark/blob/master/src/main/scala/com/microsoft/ml/spark/lightgbm/TrainUtils.scala#L317
We get the schema for features column:
```
      val featuresSchema = schema.fields(schema.fieldIndex(featuresColumn))
```
Then the metadata:
```
      val metadata = AttributeGroup.fromStructField(featuresSchema)
```
Then we retrieve the slot names on the metadata:
```
      if (metadata.attributes.isEmpty) None
      else if (metadata.attributes.get.isEmpty) None
      else {
        val colnames = (0 until numCols).map(_.toString).toArray
        metadata.attributes.get.foreach {
          case attr =>
            attr.index.foreach(index => colnames(index) = attr.name.getOrElse(index.toString))
        }
        Some(colnames)
      }
```
There is some similar way to do it in pyspark but I don't recall the exact methods used.

If you are still having trouble maybe it would be better to have a call.

**Comment by MarsXDM** [comment]
> @MarsXDM
> When you create the 'features' column, you are using VectorAssembler. VectorAssembler creates a vector column, and each individual value is what I call a slot. There is metadata on each of those slots (not a column like 'feature' or 'label_1') and one of values on the metadata is the slot name. The original feature names on the dataset prior to creating the vector column will be the slot names. The best way to fix this is to change the column names that you passed to vector assembler or set the slot names as I wrote above.

Thanks so much your detail description, the metadata of vector assembler  come from output of onehot encoder (col+"_enc")
`train_set_rn = train_set.na.replace('','EMPTY')
indexers = [StringIndexer(inputCol=cate_col, outputCol=cate_col+"_indx").setHandleInvalid("keep") for cate_col in cate_features]
encoders = [OneHotEncoder(inputCol=idx.getOutputCol(), outputCol=idx.getOutputCol()+"_enc") for idx in indexers]
assembler = VectorAssembler(inputCols=[enc.getOutputCol() for enc in encoders] + cont_features, outputCol="features")

stages = indexers + encoders + [assembler, lgb]
pipelineModel = Pipeline(stages=stages)
model = pipelineModel.fit(train_set_rn)`

I think the problem maybe come from onehotencode. but i can't figure out why this happen.
because our spark is v2.1 so can't use featurehaser to process categorical features.

@imatiach-msft  Thank you so much. I think i should dive deeply to feature extract part of pyspark.

**Comment by imatiach-msft** [comment]
@MarsXDM sorry I think this should be really quick and easy to resolve, no need to dive deep into feature extraction.  Have you tried using the ```slotNames=['my','slot','names','for','the','dataset']``` parameter on the LightGBMClassifier?  The number of slot names just has to be as long as the length of the features vector.  Have you tried modifying the column names in the dataframe on ingest to remove any special characters?

**Comment by imatiach-msft** [comment]
I'll also try to get this PR in sooner in case the better error message can help diagnose which specific columns have the issue:
https://github.com/Azure/mmlspark/pull/897

**Comment by imatiach-msft** [comment]
@MarsXDM can you try out this build:

Maven Coordinates

com.microsoft.ml.spark:mmlspark_2.11:1.0.0-rc1-105-09a66057-SNAPSHOT
Maven Resolver

https://mmlspark.azureedge.net/maven

it's from this PR which I just updated and fixed and which was just merged to master:
https://github.com/Azure/mmlspark/pull/897

**Comment by MarsXDM** [comment]
@imatiach-msft  Thanks, I have tried the new resolver com.microsoft.ml.spark:mmlspark_2.11:1.0.0-rc1-105-09a66057-SNAPSHOT, and it print the feature name that has problem, the feature has value in Chinese character.
And then tried com.microsoft.ml.spark:mmlspark_2.11:1.0.0-rc2, the feature problem is gone.
Is that the rc2 solved character problem?

**Comment by imatiach-msft** [comment]
@MarsXDM actually that is very unexpected, as they are almost the same, and lightgbm actually didn't have any new changes merged since PR #897 .  I'm not sure why the error went away, maybe you were using an older lightgbm jar somehow before with the previous snapshot?  Not sure.

**Comment by MarsXDM** [comment]
@imatiach-msft  you are right, the error went away has no any relationship with mmlspark version but the Chinese character feature is processed to a single 'empty' value feature when I experiment on 1/1kw of dataset.  When I use full dataset to execute this, the error is still there. When I remove the 2 Chinese character feature columns, the execution is success.

So if i want to use the Chinese character feature column , I need transform it.

**Comment by ranadeepsingh** [comment]
This issue was addressed in PR #897, which added explicit validation and diagnostic reporting when non-ASCII feature names are passed to LightGBM. Native LightGBM requires ASCII feature names, and PR #897 pinpoints the specific non-ASCII columns so users can rename or set slot names. As this diagnostic fix is included in published releases including v1.1.3, we are closing this issue.
