### ISSUE TITLE
No module named 'mmlspark.train._TrainClassifier'

### ISSUE THREAD

**Issue by hanan-vian** [Azure/mmlspark#974]
**Describe the bug**
`from mmlspark.train import TrainClassifier` fails with: `ModuleNotFoundError: No module named 'mmlspark.train._TrainClassifier'`

**To Reproduce**
`from mmlspark.train import TrainClassifier`

**Expected behavior**
import exit without errors

**Info (please complete the following information):**
 - MMLSpark Version: 0.0.11111111 (this is from pip install mmlspark. In the cluster I use latest maven). 
 - Spark Version - 7.3 LTS (includes Apache Spark 3.0.1, Scala 2.12)
 - Spark Platform - Databricks, working remotely using databricks-connect. in Databricks notebook I get another error https://github.com/databricks/spark-deep-learning/issues/194

** Stacktrace**
```
---------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
<ipython-input-7-4fa4faaa5641> in <module>
----> 1 from mmlspark.train import TrainClassifier

~/opt/anaconda3/envs/ollivander/lib/python3.7/site-packages/mmlspark/train/TrainClassifier.py in <module>
      7     basestring = str
      8 
----> 9 from mmlspark.train._TrainClassifier import _TrainClassifier
     10 from mmlspark.train._TrainClassifier import _TrainedClassifierModel
     11 from pyspark.ml.common import inherit_doc

ModuleNotFoundError: No module named 'mmlspark.train._TrainClassifier'```

**Comment by OscarDPan** [comment]
Did you also include the mmlspark jar in the spark config?

**Comment by hanan-vian** [comment]
After adding jars in spark config (I thought adding the package in the databricks cluster is enough) I get to this error:

```
model = LogisticRegression()
train_classifier = TrainClassifier(model=model, 
                                   labelCol=label, 
                                   numFeatures=256)
```

```
Py4JJavaError: An error occurred while calling None.com.microsoft.ml.spark.train.TrainClassifier.
: java.lang.NoClassDefFoundError: org/apache/spark/ml/util/MLWritable$class
	at com.microsoft.ml.spark.train.TrainClassifier.<init>(TrainClassifier.scala:53)
	at com.microsoft.ml.spark.train.TrainClassifier.<init>(TrainClassifier.scala:55)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:500)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:481)
	at py4j.reflection.MethodInvoker.invoke(MethodInvoker.java:247)
	at py4j.reflection.ReflectionEngine.invoke(ReflectionEngine.java:380)
	at py4j.Gateway.invoke(Gateway.java:250)
	at py4j.commands.ConstructorCommand.invokeConstructor(ConstructorCommand.java:80)
	at py4j.commands.ConstructorCommand.execute(ConstructorCommand.java:69)
	at py4j.GatewayConnection.run(GatewayConnection.java:251)
	at java.base/java.lang.Thread.run(Thread.java:832)
```

**Comment by ranadeepsingh** [comment]
Thank you for bringing this to our attention. The legacy `mmlspark` package and `mmlspark.train` module namespace have been deprecated and replaced by SynapseML (`synapse.ml`). Current releases are available via PyPI as `synapseml`. We are closing this obsolete issue.
