### ISSUE TITLE
No FileSystem for scheme: wasbs

### ISSUE THREAD

**Issue by cmbenda** [Azure/mmlspark#975]
**Describe the bug**
Py4JJavaError                             Traceback (most recent call last)
<ipython-input-2-715d2a9dbaf9> in <module>
----> 1 flightDelay = spark.read.parquet("wasbs://publicwasb@mmlspark.blob.core.windows.net/On_Time_Performance_2012_9.parquet")
      2 # print some basic info
      3 print("records read: " + str(flightDelay.count()))
      4 print("Schema: ")
      5 flightDelay.printSchema()

**To Reproduce**
import pandas as pd
flightDelay = spark.read.parquet("wasbs://publicwasb@mmlspark.blob.core.windows.net/On_Time_Performance_2012_9.parquet")
# print some basic info
print("records read: " + str(flightDelay.count()))
print("Schema: ")
flightDelay.printSchema()
flightDelay.limit(10).toPandas()

**Expected behavior**
Code should run however wasbs is a none local file system

** Stacktrace**
```
Py4JJavaError: An error occurred while calling o30.parquet.
: java.io.IOException: No FileSystem for scheme: wasbs
	at org.apache.hadoop.fs.FileSystem.getFileSystemClass(FileSystem.java:2660)
	at org.apache.hadoop.fs.FileSystem.createFileSystem(FileSystem.java:2667)
	at org.apache.hadoop.fs.FileSystem.access$200(FileSystem.java:94)
	at org.apache.hadoop.fs.FileSystem$Cache.getInternal(FileSystem.java:2703)
	at org.apache.hadoop.fs.FileSystem$Cache.get(FileSystem.java:2685)
	at org.apache.hadoop.fs.FileSystem.get(FileSystem.java:373)
	at org.apache.hadoop.fs.Path.getFileSystem(Path.java:295)
	at org.apache.spark.sql.execution.datasources.DataSource$$anonfun$org$apache$spark$sql$execut
```

**Additional context**
Is there a version of this example that will run locally?

https://github.com/Azure/mmlspark/blob/master/notebooks/samples/Regression%20-%20%20Flight%20Delays%20with%20DataCleaning.ipynb

**Comment by ranadeepsingh** [comment]
Thank you for reaching out. The error `No FileSystem for scheme: wasbs` indicates that the Apache Hadoop Azure filesystem connector (`hadoop-azure`) is not included in the Spark runtime classpath. Adding the `org.apache.hadoop:hadoop-azure` package to your Spark submission configuration resolves this scheme resolution error. We are closing this support question.
